import type {Config,World,Building,Enemy,Command,Effect,Shot} from './types';
import {random} from './random';
import {Spatial,distance,rayBox} from './systems/spatial';
const DT=1/60;
export class Engine {
 s:World; paused=false; effects:Effect[]=[]; message=''; demolition:{id:number;elapsed:number}|null=null;
 private index=new Spatial<Enemy>();
 constructor(public config:Config,seed=20260905,runId='run-'+seed,snapshot?:World){this.s=snapshot?structuredClone(snapshot):{schemaVersion:1,configVersion:config.configVersion,runId,seed:seed>>>0||1,rng:seed>>>0||1,nextEntityId:1,revision:0,tick:0,gold:config.world.initialGold,coreHp:config.world.coreHp,maxThreat:1,kills:0,bossKills:0,alive:true,buildings:[],enemies:[],shots:[],spawnCredit:0,bossRequests:0,bossWarning:-1,bossCount:0,lastBossDeath:-999,nextBoss:300,nextPerk:120,passive:0,perks:{},perkQueue:0,candidates:[],dropCooldown:0,commands:[]};if(snapshot)this.paused=true;}
 get time(){return this.s.tick/60;} get level(){return 1+Math.floor(this.time/60);} get running(){return !this.paused&&this.s.alive&&!this.s.candidates.length;}
 perk(id:string){return (this.s.perks[id]||0)*(this.config.perks[id]?.value||0);}
 stats(b:Building){const base=this.config.buildings[b.type];const p={...base,...(b.branch>=0?base.branches[b.branch]:{})};return {...p,hp:p.hp*(1+this.perk('durability'))};}
 emit(kind:string,x:number,y:number,tx=x,ty=y,text?:string){if(this.effects.length<500)this.effects.push({kind,x,y,tx,ty,life:kind==='explosion'?.55:.3,text});}
 command(c:Command){if(this.running)this.s.commands.push(c);}
 top(col:number){return Math.max(col===1||col===2?2:0,...this.s.buildings.filter(b=>b.hp>0&&b.settled&&Math.floor(b.x)===col).map(b=>b.y+.5));}
 invalid(kind:string,col:number){const c=this.config.buildings[kind];if(!c)return '请选择建筑';if(col<0||col>=this.config.world.columns)return '超出建造区域';if(this.s.gold<c.cost)return '金币不足';if(this.s.dropCooldown>1e-7)return '吊装冷却中';if(this.s.buildings.some(b=>Math.floor(b.x)===col&&!b.settled&&b.hp>0))return '该列正在下落 / 坍塌';if(this.top(col)>=this.config.world.layers)return '该列已达到最高层';return '';}
 refund(b:Building){return Math.floor(b.spent*.6*b.hp/this.stats(b).hp);}
 private commands(){for(const c of this.s.commands.splice(0)){if(c.type==='drop'){const reason=this.invalid(c.kind,c.column);if(reason){this.message=reason;continue;}const p=this.config.buildings[c.kind];this.s.gold-=p.cost;const id=this.s.nextEntityId++;const b:Building={id,type:c.kind,branch:-1,spent:p.cost,x:c.column+.5,y:this.config.world.dropY,v:0,hp:p.hp*(1+this.perk('durability')),settled:false,fallId:1,hit:[],cooldown:c.kind==='mine'?p.interval:0};this.s.buildings.push(b);this.s.dropCooldown=Math.max(.6,this.config.world.deployCooldown-this.perk('deployment'));this.emit('drop',b.x,b.y);}else if(c.type==='cancelDemolish')this.demolition=null;else{const b=this.s.buildings.find(b=>b.id===c.id&&b.hp>0&&b.settled);if(!b)continue;if(c.type==='demolish'){this.demolition={id:b.id,elapsed:0};}else if(b.branch<0&&(c.branch===0||c.branch===1)&&this.s.gold>=this.stats(b).upgradeCost){const old=this.stats(b),ratio=b.hp/old.hp;this.s.gold-=old.upgradeCost;b.spent+=old.upgradeCost;b.branch=c.branch;b.hp=this.stats(b).hp*ratio;this.emit('upgrade',b.x,b.y);}}}}
 private structure(){for(let col=0;col<this.config.world.columns;col++){let top=col===1||col===2?2:0;let supportSettled=true;const stack=this.s.buildings.filter(b=>b.hp>0&&Math.floor(b.x)===col).sort((a,b)=>a.y-b.y||a.id-b.id);for(const b of stack){if(b.settled&&(!supportSettled||b.y-.5>top+1e-6)){b.settled=false;b.v=0;b.fallId++;b.hit=[];}
 if(!b.settled){const prev=b.y;b.v=Math.min(this.config.world.maxVelocity,b.v+this.config.world.gravity*DT);b.y=Math.max(top+.5,b.y-b.v*DT);for(const e of this.index.query(b.x,(prev+b.y)/2,Math.max(2,prev-b.y+2))){const p=this.config.enemies[e.type];if(e.hp>0&&!b.hit.includes(e.id)&&Math.abs(e.x-b.x)<=.5+p.width/2&&e.y+p.height/2>=b.y-.5&&e.y-p.height/2<=prev+.5){b.hit.push(e.id);this.hurtEnemy(e,this.stats(b).impact*(1+this.perk('impact')),'impact');}}if(supportSettled&&b.y<=top+.5+1e-7){b.y=top+.5;b.v=0;b.settled=true;this.emit('dust',b.x,b.y);}}
 top=b.y+.5;supportSettled=b.settled;}}
 for(const e of this.s.enemies){const p=this.config.enemies[e.type];if(p.air||e.hp<=0)continue;let changed=true;while(changed){changed=false;for(const b of this.obstacles()){if(e.x-p.width/2<b.x+b.w/2-1e-7&&e.x+p.width/2>b.x-b.w/2+1e-7){e.x=b.x+b.w/2+p.width/2;changed=true;}}}}
 }
 private obstacles(){return [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0&&b.settled&&b.y<.51).map(b=>({id:b.id,x:b.x,y:b.y,w:1,h:1}))].sort((a,b)=>b.x-a.x);}
 private hurtEnemy(e:Enemy,damage:number,kind='physical'){if(e.hp<=0||!this.s.alive)return;const shield=Math.min(e.shield,damage);e.shield-=shield;damage-=shield;if(damage>0)e.hp-=Math.max(1,damage*(kind==='physical'?1-e.armor:1));if(e.hp<=0){e.hp=0;this.s.gold+=e.reward;this.s.kills++;if(this.config.enemies[e.type].boss){this.s.bossKills++;this.s.lastBossDeath=this.time;this.s.perkQueue++;this.s.shots=this.s.shots.filter(s=>s.owner!==e.id);}this.emit('kill',e.x,e.y,e.x,e.y,'+'+e.reward);}}
 private hurtFriend(id:number,amount:number,attacker?:Enemy){if(!this.s.alive)return;if(id===0){this.s.coreHp=Math.max(0,this.s.coreHp-amount);if(this.s.coreHp<=0){this.s.alive=false;this.s.candidates=[];this.s.perkQueue=0;this.demolition=null;this.emit('failure',2,1);}return;}const b=this.s.buildings.find(b=>b.id===id);if(!b||b.hp<=0)return;b.hp=Math.max(0,b.hp-amount);this.emit('hit',b.x,b.y);if(attacker&&this.stats(b).thorns)this.hurtEnemy(attacker,this.stats(b).thorns,'true');}
 private explosion(x:number,y:number,r:number,damage:number){this.emit('explosion',x,y);for(const b of [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0).map(b=>({...b,w:1,h:1}))]){if(!this.s.alive)break;const dx=Math.max(Math.abs(x-b.x)-b.w/2,0),dy=Math.max(Math.abs(y-b.y)-b.h/2,0);if(dx*dx+dy*dy<=r*r)this.hurtFriend(b.id,damage);}}
 spawn(type:string,eliteAllowed=true,x=35.5,y?:number){const p=this.config.enemies[type];if(!p)return;if(!p.boss&&this.s.enemies.filter(e=>e.hp>0&&!this.config.enemies[e.type].boss).length>=this.config.schedule.enemyCap)return;const l=this.level-1;let maxHp=p.hp*(1+this.config.schedule.hpGrowth*l),attackScale=1+this.config.schedule.damageGrowth*l,reward=p.reward,armor=p.armor,shield=0,elite='';if(p.boss){this.s.bossCount++;maxHp*=1+.15*(this.s.bossCount-1);}else if(eliteAllowed&&this.level>=6&&random(this.s)<this.config.schedule.eliteChance){maxHp*=1.8;attackScale*=1.25;reward*=2;elite=random(this.s)<.5?'shield':'armor';if(elite==='shield')shield=maxHp*.3;else armor=Math.min(.6,armor+.2);}
 this.s.enemies.push({id:this.s.nextEntityId++,type,x,y:y??(type==='carrier'?11:type==='bombardier'?10:p.air?5:p.height/2),hp:maxHp,maxHp,shield,armor,attackScale,speedScale:Math.min(1.3,1+this.config.schedule.speedGrowth*l),reward,elite,cooldown:type==='bombardier'?4:0,slows:[],skill:12,summon:15,state:'walk',timer:0,distance:0,target:0});}
 private schedule(){const s=this.s,c=this.config.schedule,t=this.time; if(s.tick===c.firstEnemy*60)this.spawn('grunt');if(t>=c.firstEnemy){const phase=t%60<35?1:t%60<50?1.6:.55;const boss=s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss);s.spawnCredit+=Math.min(c.maxRate,c.baseRate+c.rateGrowth*(this.level-1))*phase*(s.bossRequests?1.2:boss?.8:1)*DT;while(s.spawnCredit>=1){s.spawnCredit--;const pool=Object.entries(this.config.enemies).filter(([,p])=>p.weight&&p.unlock<=t);let n=random(s)*pool.reduce((a,[,p])=>a+p.weight,0);for(const [key,p] of pool){n-=p.weight;if(n<=0){this.spawn(key);break;}}}}
 if(t>=s.nextBoss-10&&s.bossWarning<0&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&t-s.lastBossDeath>=30){s.bossWarning=10;}
 if(t>=s.nextBoss){s.bossRequests=1;s.nextBoss+=c.bossEvery;}
 if(s.bossRequests&&s.bossWarning<0&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&t-s.lastBossDeath>=30)s.bossWarning=10;
 if(s.bossWarning>=0){s.bossWarning=Math.max(0,s.bossWarning-DT);if(s.bossWarning<=1e-7&&(s.bossRequests||t>=s.nextBoss)){this.spawn(s.bossCount%2===0?'beast':'carrier',false);s.bossWarning=-1;s.bossRequests=0;}}
 }
 private move(){const obstacles=this.obstacles();for(const e of this.s.enemies){if(e.hp<=0)continue;const p=this.config.enemies[e.type];e.cooldown=Math.max(0,e.cooldown-DT);e.slows=e.slows.filter(a=>a.until>this.time);const slow=Math.max(0,...e.slows.map(a=>a.amount))*(p.boss?.5:1),speed=p.speed*e.speedScale*(1-slow);if(p.air){const tx=e.type==='carrier'?18:2,ty=e.type==='flyer'?3:e.y;const d=Math.hypot(tx-e.x,ty-e.y);if(d>.01){const f=Math.min(1,speed*DT/d);e.x+=(tx-e.x)*f;e.y+=(ty-e.y)*f;}continue;}
 const obstacle=obstacles.find(b=>b.x+b.w/2<=e.x-p.width/2+.001);e.target=obstacle?.id??-1;
 if(e.state==='charge'){e.timer-=DT;if(e.timer<=0){e.state='dash';e.distance=0;}continue;}if(e.state==='fuse')continue;
 const dx=(e.state==='dash'?4:speed)*DT;const bound=obstacle?obstacle.x+obstacle.w/2+p.width/2:p.width/2;e.x=Math.max(bound,e.x-dx);if(e.state==='dash'){e.distance+=dx;if(e.x<=bound+1e-6||e.distance>=8){if(obstacle&&e.x<=bound+1e-6)this.hurtFriend(obstacle.id,300*e.attackScale,undefined);this.emit('explosion',e.x,e.y);e.state='walk';e.skill=12;}}}}
 private clearRay(b:Building,e:Enemy){let nearest=Infinity,hit=-1;for(const f of [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(f=>f.hp>0&&f.id!==b.id).map(f=>({...f,w:1,h:1}))])nearest=Math.min(nearest,rayBox(b.x,b.y,e.x,e.y,f.x,f.y,f.w,f.h));for(const a of this.index.query(b.x,b.y,this.stats(b).range+2)){if(a.hp<=0)continue;const p=this.config.enemies[a.type],t=rayBox(b.x,b.y,e.x,e.y,a.x,a.y,p.width,p.height);if(t<nearest){nearest=t;hit=a.id;}}return hit===e.id;}
 private buildings(){for(const b of this.s.buildings){if(!this.s.alive)break;if(!b.settled||b.hp<=0)continue;const p=this.stats(b);b.cooldown=Math.max(0,b.cooldown-DT);if(b.cooldown>1e-8)continue;
 if(b.type==='mine'){const n=Math.floor(p.production*(1+this.perk('mining')));this.s.gold+=n;b.cooldown=p.interval;this.emit('gold',b.x,b.y,b.x,b.y,'+'+n);continue;}
 if(b.type==='repair'){const targets=[{id:0,x:2,y:1,hp:this.s.coreHp,max:this.config.world.coreHp},...this.s.buildings.filter(f=>f.hp>0&&f.id!==b.id).map(f=>({...f,max:this.stats(f).hp}))].filter(f=>f.hp<f.max&&distance(b,f)<=p.range).sort((a,c)=>a.hp/a.max-c.hp/c.max||a.id-c.id);const f=targets[0];if(f){const hp=Math.min(f.max,f.hp+p.damage*(1+this.perk('repair_efficiency')));if(f.id===0)this.s.coreHp=hp;else this.s.buildings.find(a=>a.id===f.id)!.hp=hp;b.cooldown=p.interval;this.emit('repair',b.x,b.y,f.x,f.y);}continue;}
 if(!p.damage)continue;const targets=this.index.query(b.x,b.y,p.range).filter(e=>e.hp>0&&this.config.enemies[e.type].air===(b.type==='anti_air')&&distance(b,e)<=p.range&&distance(b,e)>=p.minRange).sort((a,c)=>Math.hypot(a.x-2,a.y-1)-Math.hypot(c.x-2,c.y-1)||a.id-c.id);const e=b.type==='ballista'?targets.find(e=>this.clearRay(b,e)):targets[0];if(!e)continue;
 const boost=Math.max(0,...this.s.buildings.filter(f=>f.hp>0&&f.settled&&f.type==='amplifier'&&distance(f,b)<=this.stats(f).range).map(f=>this.stats(f).boost));const damage=p.damage*(1+this.perk('attack'))*(1+boost);b.cooldown=p.interval;
 if(b.type==='mortar'){this.s.shots.push({id:this.s.nextEntityId++,owner:b.id,kind:'mortar',x:e.x,y:e.y,remaining:.8,duration:.8,damage,radius:p.radius});this.emit('mortar',b.x,b.y,e.x,e.y);}else if(b.type==='frost'){for(const a of targets){this.hurtEnemy(a,damage,'cold');a.slows.push({amount:p.slow,until:this.time+p.slowDuration});}this.emit('frost',b.x,b.y,b.x+p.range,b.y);}else{this.hurtEnemy(e,damage);this.emit(b.type,b.x,b.y,e.x,e.y);}}
 }
 private bomb(e:Enemy,col:number,delay:number,damage:number){this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',x:col+.5,y:0,remaining:delay,duration:delay,damage,radius:.8});}
 private enemies(){for(const e of this.s.enemies){if(e.hp<=0||!this.s.alive)continue;const p=this.config.enemies[e.type];if(e.type==='carrier'){if(e.x>18.01)continue;e.skill-=DT;e.summon-=DT;if(e.skill<=0){let best=0,count=-1;for(let col=0;col<=21;col++){const n=this.s.buildings.filter(b=>b.hp>0&&b.x>=col&&b.x<col+3).length;if(n>count){count=n;best=col;}}for(let c=best;c<best+3;c++)this.bomb(e,c,2,p.damage*e.attackScale);e.skill=8;}if(e.summon<=0){for(let i=0;i<3;i++)this.spawn('flyer',false,e.x,e.y);e.summon=15;}continue;}
 if(e.type==='bombardier'){if(e.x<24&&e.cooldown<=0){const b=this.s.buildings.filter(b=>b.hp>0&&b.settled&&Math.abs(b.x-e.x)<=6).sort((a,b)=>b.spent-a.spent||a.id-b.id)[0];if(b||e.x<=2.01){this.bomb(e,b?Math.floor(b.x):1,1.5,p.damage*e.attackScale);e.cooldown=4;}}continue;}
 if(e.type==='flyer'){if(distance(e,{x:2,y:3})<.05&&e.cooldown<=0){this.hurtFriend(0,p.damage*e.attackScale);e.cooldown=p.interval;this.emit('enemyShot',e.x,e.y,2,1);}continue;}
 const o=this.obstacles().find(b=>b.id===e.target);if(e.type==='beast'&&e.state==='walk'){e.skill-=DT;if(e.skill<=0&&o&&e.x-p.width/2-o.x-o.w/2<=8){e.state='charge';e.timer=2;continue;}}
 if(e.state==='charge'||e.state==='dash')continue;
 if(e.state==='fuse'){e.timer-=DT;if(e.timer<=0){this.explosion(e.x,e.y,1.4,p.damage*e.attackScale);e.hp=0;}continue;}
 if(o&&e.x-p.width/2<=o.x+o.w/2+.001&&e.cooldown<=0){if(e.type==='bomber'){e.state='fuse';e.timer=1.2;}else{this.hurtFriend(o.id,p.damage*e.attackScale,e);e.cooldown=p.interval;this.emit('enemyShot',e.x,e.y,o.x,o.y);}}}}
 private projectiles(){for(const s of [...this.s.shots]){if(!this.s.alive)break;s.remaining-=DT;if(s.remaining>1e-7)continue;if(s.kind==='mortar'){this.emit('explosion',s.x,s.y);for(const e of this.index.query(s.x,s.y,s.radius))if(!this.config.enemies[e.type].air&&distance(s,e)<=s.radius)this.hurtEnemy(e,s.damage,'explosion');}else{const col=Math.floor(s.x),top=Math.max(col===1||col===2?2:0,...this.s.buildings.filter(b=>b.hp>0&&Math.floor(b.x)===col).map(b=>b.y+.5));this.explosion(s.x,top,s.radius,s.damage);}this.s.shots=this.s.shots.filter(a=>a.id!==s.id);}}
 private offer(){if(!this.s.perkQueue||this.s.candidates.length||!this.s.alive)return;const pool=Object.keys(this.config.perks).filter(k=>(this.s.perks[k]||0)<this.config.perks[k].max);while(pool.length&&this.s.candidates.length<3)this.s.candidates.push(pool.splice(Math.floor(random(this.s)*pool.length),1)[0]);if(!this.s.candidates.length)this.s.candidates=['supply'];}
 choose(id:string){if(!this.s.alive||!this.s.candidates.includes(id))return;const ratios=this.s.buildings.map(b=>b.hp/this.stats(b).hp);if(id==='supply')this.s.gold+=100;else this.s.perks[id]=(this.s.perks[id]||0)+1;if(id==='durability')this.s.buildings.forEach((b,i)=>b.hp=this.stats(b).hp*ratios[i]);if(id==='core_repair')this.s.coreHp=Math.min(this.config.world.coreHp,this.s.coreHp+this.config.perks[id].value);this.s.candidates=[];this.s.perkQueue--;this.offer();}
 step(){if(!this.running)return;this.s.tick++;this.effects=this.effects.map(e=>({...e,life:e.life-DT})).filter(e=>e.life>0);this.commands();this.s.dropCooldown=Math.max(0,this.s.dropCooldown-DT);this.schedule();this.index.rebuild(this.s.enemies);this.structure();this.move();if(!this.s.alive)return;this.index.rebuild(this.s.enemies);this.buildings();this.enemies();this.projectiles();this.s.buildings=this.s.buildings.filter(b=>b.hp>0);this.s.enemies=this.s.enemies.filter(e=>e.hp>0);if(!this.s.alive)return;
 if(this.demolition){const b=this.s.buildings.find(b=>b.id===this.demolition!.id&&b.settled);if(!b)this.demolition=null;else{this.demolition.elapsed+=DT;if(this.demolition.elapsed>=1){this.s.gold+=this.refund(b);this.s.buildings=this.s.buildings.filter(a=>a.id!==b.id);this.demolition=null;}}}
 this.s.passive+=DT;if(this.s.passive+1e-8>=this.config.schedule.passiveEvery){this.s.passive-=this.config.schedule.passiveEvery;this.s.gold+=this.config.schedule.passiveGold+this.perk('subsidy');}this.s.maxThreat=Math.max(this.s.maxThreat,this.level);if(this.time>=this.s.nextPerk){this.s.perkQueue++;this.s.nextPerk+=this.config.schedule.perkEvery;}this.offer();}
 snapshot(){const s=structuredClone(this.s);s.commands=s.commands.filter(c=>c.type!=='demolish'&&c.type!=='cancelDemolish');return s;}
}
