import {EVENTS} from './incidents';
import {migrateBalance} from './balance';
import {enemyProjectilePosition} from './enemy-projectiles';
import {supportedBuildings} from './systems/support';
import {shellPath,mortarLaunch} from './trajectory';
import type {Config,World,Building,Enemy,Command,Effect,Shot,Difficulty} from './types';
import {random} from './random';
import {Spatial,distance,rayBox} from './systems/spatial';
const DT=1/60;
export class Engine {
 s:World; controlled=0; aim:{x:number;y:number;fire:boolean}={x:0,y:0,fire:false}; alert={title:'',detail:'',until:0}; paused=false; effects:Effect[]=[]; sounds:string[]=[]; message='';messageUntil=0; demolition:{id:number;elapsed:number}|null=null;
 private index=new Spatial<Enemy>();
 constructor(public config:Config,seed=20260905,runId='run-'+seed,snapshot?:World){this.s=snapshot?structuredClone(snapshot):{balanceRevision:config.balanceRevision??1,schemaVersion:1,configVersion:config.configVersion,runId,seed:seed>>>0||1,rng:seed>>>0||1,nextEntityId:1,revision:0,tick:0,gold:config.world.initialGold,coreHp:config.world.coreHp,maxThreat:1,kills:0,bossKills:0,alive:true,buildings:[],enemies:[],shots:[],spawnCredit:0,bossRequests:0,bossWarning:-1,bossCount:0,lastBossDeath:-999,nextBoss:300,nextPerk:120,passive:0,perks:{},perkQueue:0,candidates:[],dropCooldown:0,commands:[]};if(snapshot)migrateBalance(this.s,config);this.s.difficulty??='easy';this.s.nextEvent??=Math.max(this.config.schedule.eventFirst,this.time+20);this.s.eventCount??=0;this.s.eventDebt??=0;this.s.event??=null;if(snapshot)this.paused=true;}
 difficultyStats(d:Difficulty=this.s.difficulty??'easy'){const c=this.config.schedule;return d==='easy'?{hp:1,damage:1,rate:1}:{hp:c[d+'Hp'],damage:c[d+'Damage'],rate:c[d+'Rate']};}
 setDifficulty(d:Difficulty){if(!['easy','normal','hard'].includes(d))return;const old=this.difficultyStats(),next=this.difficultyStats(d);for(const e of this.s.enemies){e.hp*=next.hp/old.hp;e.maxHp*=next.hp/old.hp;e.shield*=next.hp/old.hp;e.attackScale*=next.damage/old.damage;}this.s.difficulty=d;}
 blocksFriendly(type:string,kind:string){return this.s.difficulty==='hard'&&type==='wall'&&kind!=='bullet';}
 wallBetween(b:Building,e:Enemy){return this.s.buildings.some(f=>f.id!==b.id&&f.hp>0&&this.blocksFriendly(f.type,b.type)&&rayBox(b.x,b.y,e.x,e.y,f.x,f.y,1,1)<=1);}
 notify(text:string){this.message=text;this.messageUntil=this.time+3;}
 get time(){return this.s.tick/60;} get level(){return 1+Math.floor(this.time/60);} get running(){return !this.paused&&this.s.alive&&!this.s.candidates.length;}
 perk(id:string){return (this.s.perks[id]||0)*(this.config.perks[id]?.value||0);}
 stats(b:Building){const base=this.config.buildings[b.type];const p={...base,...(b.branch>=0?base.branches[b.branch]:{})};return {...p,hp:p.hp*(1+this.perk('durability'))};}
 emit(kind:string,x:number,y:number,tx=x,ty=y,text?:string){if(this.sounds.length<64)this.sounds.push(kind);if(this.effects.length<500)this.effects.push({kind,x,y,tx,ty,life:kind==='explosion'?.55:.3,text});}
 command(c:Command){if(this.running)this.s.commands.push(c);}
 top(col:number){return Math.max(col===1||col===2?2:0,...this.s.buildings.filter(b=>b.hp>0&&b.settled&&Math.floor(b.x)===col).map(b=>b.y+.5));}
 buildingCount(kind:string){return this.s.buildings.filter(b=>b.type===kind&&b.hp>0).length;}
 buildingLimit(kind:string){const p=this.config.buildings[kind];return (this.s.difficulty==='easy'?p?.easyLimit:undefined)??p?.limit??Infinity;}
 targetable(e:Enemy){return e.hp>0&&!(e.type==='sandworm'&&e.state==='burrow');}
 invalid(kind:string,col:number,layer?:number){const c=this.config.buildings[kind];if(!c)return '请选择建筑';if(this.buildingCount(kind)>=this.buildingLimit(kind))return `${c.name}已达上限 ${this.buildingLimit(kind)} 座`; if(col<0||col>=this.config.world.columns)return '超出建造区域';if(this.s.gold<c.cost)return '金币不足';if(this.s.dropCooldown>1e-7)return '吊装冷却中';if(this.s.buildings.some(b=>Math.floor(b.x)===col&&!b.settled&&b.hp>0))return '该列正在下落 / 坍塌';if(kind==='bridge'){if(layer===undefined||!Number.isInteger(layer)||layer<0||layer>=this.config.world.layers)return '请选择桥梁高度';if((col===1||col===2)&&layer<2||this.s.buildings.some(b=>b.hp>0&&Math.floor(b.x)===col&&Math.abs(b.y-(layer+.5))<1))return '该格已被占用';const candidate:Building={id:-1,type:'bridge',x:col+.5,y:layer+.5,hp:1,settled:true,branch:-1,spent:0,v:0,fallId:1,hit:[],cooldown:0};if(!supportedBuildings([...this.s.buildings,candidate]).has(-1))return '需要连接地面、核心或已支撑建筑';return '';}if(this.top(col)>=this.config.world.layers)return '该列已达到最高层';return '';}
 refund(b:Building){return Math.floor(b.spent*.6*b.hp/this.stats(b).hp);}
 isAir(e:Enemy){return this.config.enemies[e.type].air||!!e.descent;}
 control(id:number){const b=this.s.buildings.find(b=>b.id===id&&b.hp>0&&b.settled);this.controlled=b&&['ballista','mortar','cannon','sniper','anti_air','frost'].includes(b.type)?id:0;this.aim.fire=false;}
 upgradeSelection(ids:number[],branch:number){const buildings=this.s.buildings.filter(b=>ids.includes(b.id)&&b.hp>0&&b.settled&&b.branch<0);return {buildings,cost:buildings.reduce((n,b)=>n+this.stats(b).upgradeCost,0),branch};}
 announce(title:string,detail:string){this.alert={title,detail,until:this.time+4};this.emit('alarm',2,1);}
 private commands(){for(const c of this.s.commands.splice(0)){if(c.type==='upgradeMany'){const group=this.upgradeSelection(c.ids,c.branch);if(![0,1].includes(c.branch)||!group.buildings.length||this.s.gold<group.cost){this.notify('批量升级失败：金币不足或没有可升级建筑');continue;}for(const b of group.buildings){const p=this.stats(b),ratio=b.hp/p.hp;this.s.gold-=p.upgradeCost;b.spent+=p.upgradeCost;b.branch=c.branch;b.hp=this.stats(b).hp*ratio;this.emit('upgrade',b.x,b.y);}continue;}if(c.type==='drop'){const reason=this.invalid(c.kind,c.column,c.layer);if(reason){this.notify(reason);continue;}const p=this.config.buildings[c.kind];this.s.gold-=p.cost;const id=this.s.nextEntityId++;const b:Building={id,type:c.kind,branch:-1,spent:p.cost,x:c.column+.5,y:c.kind==='bridge'?c.layer!+.5:this.config.world.dropY,v:0,hp:p.hp*(1+this.perk('durability')),settled:c.kind==='bridge',fallId:1,hit:[],cooldown:c.kind==='mine'?p.interval:0};this.s.buildings.push(b);this.s.dropCooldown=Math.max(.6,this.config.world.deployCooldown-this.perk('deployment'));this.emit('drop',b.x,b.y);}else if(c.type==='cancelDemolish')this.demolition=null;else{const b=this.s.buildings.find(b=>b.id===c.id&&b.hp>0&&b.settled);if(!b)continue;if(c.type==='demolish'){this.demolition={id:b.id,elapsed:0};}else if(b.branch<0&&(c.branch===0||c.branch===1)&&this.s.gold>=this.stats(b).upgradeCost){const old=this.stats(b),ratio=b.hp/old.hp;this.s.gold-=old.upgradeCost;b.spent+=old.upgradeCost;b.branch=c.branch;b.hp=this.stats(b).hp*ratio;this.emit('upgrade',b.x,b.y);}}}}
 private structure(){const supported=supportedBuildings(this.s.buildings);for(const b of this.s.buildings){if(b.hp>0&&b.settled&&!supported.has(b.id)){b.settled=false;b.v=0;b.fallId++;b.hit=[];}}for(let col=0;col<this.config.world.columns;col++){let top=col===1||col===2?2:0;let supportSettled=true;const stack=this.s.buildings.filter(b=>b.hp>0&&Math.floor(b.x)===col).sort((a,b)=>a.y-b.y||a.id-b.id);for(const b of stack){if(b.settled&&!supported.has(b.id)&&(!supportSettled||b.y-.5>top+1e-6)){b.settled=false;b.v=0;b.fallId++;b.hit=[];}
 if(!b.settled){const prev=b.y;b.v=Math.min(this.config.world.maxVelocity,b.v+this.config.world.gravity*DT);b.y=Math.max(top+.5,b.y-b.v*DT);for(const e of this.index.query(b.x,(prev+b.y)/2,Math.max(2,prev-b.y+2))){const p=this.config.enemies[e.type];if(e.hp>0&&!b.hit.includes(e.id)&&Math.abs(e.x-b.x)<=.5+p.width/2&&e.y+p.height/2>=b.y-.5&&e.y-p.height/2<=prev+.5){b.hit.push(e.id);this.hurtEnemy(e,this.stats(b).impact*(1+this.perk('impact')),'impact');}}if(supportSettled&&b.y<=top+.5+1e-7){b.y=top+.5;b.v=0;b.settled=true;this.emit('dust',b.x,b.y);}}
 top=b.y+.5;supportSettled=b.settled;}}
 for(const e of this.s.enemies){const p=this.config.enemies[e.type];if(this.isAir(e)||e.hp<=0||e.type==='sandworm')continue;let changed=true;while(changed){changed=false;for(const b of this.obstacles()){if(e.x-p.width/2<b.x+b.w/2-1e-7&&e.x+p.width/2>b.x-b.w/2+1e-7){e.x=b.x+b.w/2+p.width/2;changed=true;}}}}
 }
 private obstacles(){return [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0&&b.settled&&b.y<.51).map(b=>({id:b.id,x:b.x,y:b.y,w:1,h:1}))].sort((a,b)=>b.x-a.x);}
 private hurtEnemy(e:Enemy,damage:number,kind='physical'){if(!this.targetable(e)||!this.s.alive)return;if(kind==='explosion'&&e.type==='blastbeetle')damage*=1-this.config.schedule.blastResistance;const shield=Math.min(e.shield,damage);e.shield-=shield;if(shield>0&&e.shield===0)this.emit('shieldBreak',e.x,e.y);damage-=shield;if(damage>0)e.hp-=Math.max(1,damage*(kind==='physical'?1-e.armor:1));if(e.hp<=0){e.hp=0;this.s.gold+=e.reward;this.s.kills++;if(this.config.enemies[e.type].boss){this.s.bossKills++;this.s.lastBossDeath=this.time;this.s.perkQueue++;this.s.shots=this.s.shots.filter(s=>s.owner!==e.id||s.phase==='flight');}this.emit('kill',e.x,e.y,e.x,e.y,'+'+e.reward);}}
 private hurtFriend(id:number,amount:number,attacker?:Enemy){if(!this.s.alive)return;if(id===0){this.s.coreHp=Math.max(0,this.s.coreHp-amount);if(this.s.coreHp<=0){this.s.alive=false;this.s.candidates=[];this.s.perkQueue=0;this.demolition=null;this.emit('failure',2,1);}return;}const b=this.s.buildings.find(b=>b.id===id);if(!b||b.hp<=0)return;b.hp=Math.max(0,b.hp-amount);this.emit('hit',b.x,b.y);if(attacker&&this.stats(b).thorns)this.hurtEnemy(attacker,this.stats(b).thorns,'true');}
 private explosion(x:number,y:number,r:number,damage:number){this.emit('explosion',x,y);for(const b of [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0).map(b=>({...b,w:1,h:1}))]){if(!this.s.alive)break;const dx=Math.max(Math.abs(x-b.x)-b.w/2,0),dy=Math.max(Math.abs(y-b.y)-b.h/2,0);if(dx*dx+dy*dy<=r*r)this.hurtFriend(b.id,damage);}}
 spawn(type:string,eliteAllowed=true,x=35.5,y?:number){const p=this.config.enemies[type];if(!p)return;if(p.boss&&this.s.enemies.some(a=>a.hp>0&&this.config.enemies[a.type].boss))return;if(!p.boss&&this.s.enemies.filter(e=>e.hp>0&&!this.config.enemies[e.type].boss).length>=this.config.schedule.enemyCap)return;const l=this.level-1,difficulty=this.difficultyStats(),growth=this.enemyGrowth(l);let maxHp=p.hp*difficulty.hp*growth.hp,attackScale=growth.damage*difficulty.damage,reward=p.reward,armor=p.armor,shield=0,elite='';if(p.boss){this.s.bossCount++;maxHp*=1+(this.config.schedule.bossHpGrowth??.15)*(this.s.bossCount-1);attackScale*=1+(this.config.schedule.bossDamageGrowth??0)*(this.s.bossCount-1);}else if(eliteAllowed&&this.level>=6&&random(this.s)<this.config.schedule.eliteChance){maxHp*=1.8;attackScale*=1.25;reward*=2;elite=random(this.s)<.5?'shield':'armor';if(elite==='shield')shield=maxHp*.3;else armor=Math.min(.6,armor+.2);}
 if(type==='reflector')shield=maxHp/ p.hp*this.config.schedule.reflectShield;if(p.boss)this.announce(p.name+' · 已抵达',type==='sandworm'?'地下钻出 / 沿途摧毁 · 注意垂直危险通道':type==='queen'?'孵化虫群 / 酸液喷射 · 配置混合火力':type==='tempest'?'连锁落雷 / 等离子弹 · 广域防空就位':type==='beast'?'破城冲撞 / 范围震击 · 分散后排、加固前墙':'空域封锁 / 导弹齐射 · 防空火力就位');
 this.s.enemies.push({id:this.s.nextEntityId++,type,x,y:y??(type==='carrier'?11:type==='tempest'?9:type==='bombardier'?10:p.air?5:p.height/2),hp:maxHp,maxHp,shield,armor,attackScale,speedScale:Math.min(1.3,1+this.config.schedule.speedGrowth*l),reward,elite,cooldown:type==='bombardier'?4:0,slows:[],skill:type==='carrier'?4:12,summon:type==='carrier'?3:15,state:'walk',timer:0,distance:0,target:0});}
 enemyGrowth(minutes=this.level-1){const c=this.config.schedule,ramp=Math.max(0,minutes-(c.growthRampMinute??10));return {hp:1+c.hpGrowth*minutes+(c.hpAcceleration??0)*ramp*ramp,damage:1+c.damageGrowth*minutes+(c.damageAcceleration??0)*ramp*ramp};}
 private growEnemies(before:number,after:number){const a=this.enemyGrowth(before),b=this.enemyGrowth(after);for(const e of this.s.enemies){if(e.hp<=0)continue;e.hp*=b.hp/a.hp;e.maxHp*=b.hp/a.hp;e.shield*=b.hp/a.hp;e.attackScale*=b.damage/a.damage;e.speedScale=Math.min(1.3,e.speedScale*Math.min(1.3,1+this.config.schedule.speedGrowth*after)/Math.min(1.3,1+this.config.schedule.speedGrowth*before));}}
 private schedule(){const s=this.s,c=this.config.schedule,t=this.time; if(s.tick===c.firstEnemy*60)this.spawn('grunt');if(t>=c.firstEnemy){const phase=t%60<35?1:t%60<50?1.6:.55;const boss=s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss);s.spawnCredit+=Math.min(c.maxRate,c.baseRate+c.rateGrowth*(this.level-1))*this.difficultyStats().rate*phase*(s.bossRequests?1.2:boss?.8:1)*DT;while(s.spawnCredit>=1){s.spawnCredit--;if((s.eventDebt??0)>0){s.eventDebt!--;continue;}const pool=Object.entries(this.config.enemies).filter(([,p])=>p.weight&&p.unlock<=t);let n=random(s)*pool.reduce((a,[,p])=>a+p.weight,0);for(const [key,p] of pool){n-=p.weight;if(n<=0){this.spawn(key);break;}}}}
 if(t>=s.nextBoss-10&&s.bossWarning<0&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&t-s.lastBossDeath>=30){s.bossWarning=10;}
 if(t>=s.nextBoss){s.bossRequests=1;s.nextBoss+=c.bossEvery;}
 if(s.bossRequests&&s.bossWarning<0&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&t-s.lastBossDeath>=30)s.bossWarning=10;
 if(s.bossWarning>=0){s.bossWarning=Math.max(0,s.bossWarning-DT);if(s.bossWarning<=1e-7&&(s.bossRequests||t>=s.nextBoss)){this.spawn(Object.entries(this.config.enemies).filter(([,p])=>p.boss).sort((a,b)=>a[1].unlock-b[1].unlock)[s.bossCount%Object.values(this.config.enemies).filter(p=>p.boss).length][0],false);s.bossWarning=-1;s.bossRequests=0;}}
 }
 private events(){
 const s=this.s,c=this.config.schedule;
 if(!s.event&&this.time>=s.nextEvent!&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&s.bossWarning<0&&s.nextBoss-this.time>20){
  const kind=(['missiles','airdrop','meteor','breach'] as const)[s.eventCount!%4];const cols=this.s.buildings.filter(b=>b.hp>0).sort((a,b)=>b.spent-a.spent||a.id-b.id).map(b=>Math.floor(b.x));
  s.event={kind,remaining:c.eventWarning,columns:(kind==='missiles'||kind==='meteor')?[...new Set([...cols,1,5,9])].slice(0,3):[10,16,22]};s.eventCount!++;this.announce(EVENTS[kind].title,EVENTS[kind].detail);
 }
 if(!s.event)return;s.event.remaining-=DT;if(s.event.remaining>0)return;const event=s.event;
 if(event.kind==='missiles')for(const col of event.columns){const delay=1+random(s)*.4;s.shots.push({id:s.nextEntityId++,owner:2147483647,kind:'bomb',phase:'flight',visual:'missile',originX:35,originY:15,x:col+.5,y:0,remaining:delay,duration:delay,damage:c.eventMissileDamage*this.difficultyStats().damage*(1+.04*(this.level-1)),radius:c.eventMissileRadius});}
 else if(event.kind==='meteor')for(const col of event.columns){const duration=1.7+random(s)*.5;s.shots.push({id:s.nextEntityId++,owner:2147483647,kind:'rock',phase:'flight',visual:'meteor',originX:col+6,originY:16,x:col+.5,y:0,remaining:duration,duration,damage:c.meteorDamage*this.difficultyStats().damage,radius:c.meteorRadius});}
 else if(event.kind==='breach')for(const col of event.columns){for(const type of ['leaper','spitter']){const before=s.enemies.length;this.spawn(type,false,col+.5);if(s.enemies.length>before)s.eventDebt!++;}this.emit('rift',col+.5,.1);}
 else for(const col of event.columns.slice(0,c.eventDropCount)){const before=s.enemies.length;this.spawn('grunt',false,col+.5,14);if(s.enemies.length>before){s.enemies[s.enemies.length-1].descent=true;s.eventDebt!++;}}
 this.announce(EVENTS[event.kind].active,EVENTS[event.kind].detail);s.event=null;s.nextEvent=this.time+c.eventEvery;
 }
 private reflect(s:Shot,x:number,y:number){const e=this.s.enemies.filter(e=>e.type==='reflector'&&e.hp>0&&e.shield>0&&distance(e,{x,y})<=Math.max(.9,s.radius)).sort((a,b)=>distance(a,{x,y})-distance(b,{x,y})||a.id-b.id)[0];if(!e)return false;
  e.shield=Math.max(0,e.shield-s.damage);const owner=this.s.buildings.find(b=>b.id===s.owner&&b.hp>0),target=owner??{x:2,y:1};s.kind='rock';s.visual='reflected';s.phase='flight';s.originX=x;s.originY=y;s.x=target.x;s.y=target.y;s.duration=Math.max(.4,distance({x,y},target)/12);s.remaining=s.duration;s.owner=e.id;s.damage*=.65;this.emit('reflect',x,y,target.x,target.y);if(e.shield===0)this.emit('shieldBreak',e.x,e.y);return true;
 }
 private move(){const obstacles=this.obstacles(),marshals=this.s.enemies.filter(a=>a.hp>0&&a.type==='marshal');for(const e of this.s.enemies){if(e.hp<=0)continue;const p=this.config.enemies[e.type];if(e.type==='sandworm'){this.wormMove(e);continue;}if(e.descent){e.y=Math.max(p.height/2,e.y-2*DT);if(e.y<=p.height/2)e.descent=false;continue;}e.cooldown=Math.max(0,e.cooldown-DT);e.attackAnim=Math.max(0,(e.attackAnim||0)-DT);e.slows=e.slows.filter(a=>a.until>this.time);const slow=Math.max(0,...e.slows.map(a=>a.amount))*(p.boss?.5:1),speed=p.speed*e.speedScale*(1-slow);if(p.air){const tx=e.type==='carrier'?18:e.type==='tempest'?22:2,ty=e.type==='flyer'?3:e.y;const d=Math.hypot(tx-e.x,ty-e.y);if(d>.01){const f=Math.min(1,speed*DT/d);e.x+=(tx-e.x)*f;e.y+=(ty-e.y)*f;}continue;}
 const obstacle=obstacles.find(b=>b.x+b.w/2<=e.x-p.width/2+.001);e.target=obstacle?.id??-1;
 if(e.state==='charge'){e.timer-=DT;if(e.timer<=0){e.state='dash';e.distance=0;}continue;}if(e.state==='fuse')continue;
 if(e.type==='spitter'&&obstacle&&distance(e,obstacle)<=this.config.schedule.spitterRange)continue;
 if(e.type==='leaper'){e.skill-=DT;if(e.state==='walk'&&e.skill<=0){e.state='leap';e.timer=.65;e.skill=this.config.schedule.leapCooldown;this.emit('dust',e.x,e.y);}if(e.state==='leap'){e.timer-=DT;if(e.timer<=0){e.state='recover';e.timer=.4;this.emit('dust',e.x,e.y);}}else if(e.state==='recover'){e.timer-=DT;if(e.timer<=0)e.state='walk';continue;}}
 const marshal=marshals.some(a=>distance(a,e)<this.config.schedule.marshalRadius);if(marshal&&!p.boss&&e.type!=='marshal'&&e.state==='walk'&&this.s.enemies.some(a=>a.id!==e.id&&a.hp>0&&!this.isAir(a)&&a.x<e.x&&e.x-a.x<this.config.schedule.marshalGap))continue;
 const dx=(e.state==='dash'?4:e.state==='leap'?this.config.schedule.leapSpeed*(1-slow):speed)*DT;const bound=obstacle?obstacle.x+obstacle.w/2+p.width/2:p.width/2;e.x=Math.max(bound,e.x-dx);if(e.state==='dash'){e.distance+=dx;if(e.x<=bound+1e-6||e.distance>=8){if(obstacle&&e.x<=bound+1e-6)this.explosion(obstacle.x,obstacle.y,this.config.schedule.beastChargeRadius,(this.config.schedule.beastChargeDamage??300)*e.attackScale);this.emit('explosion',e.x,e.y);e.state='walk';e.skill=12;}}}}
 private clearRay(b:Building,e:Enemy){let nearest=Infinity,hit=-1;for(const f of this.s.buildings.filter(f=>f.hp>0&&f.id!==b.id&&this.blocksFriendly(f.type,b.type==='sniper'?'bullet':b.type)).map(f=>({...f,w:1,h:1})))nearest=Math.min(nearest,rayBox(b.x,b.y,e.x,e.y,f.x,f.y,f.w,f.h));for(const a of this.index.query(b.x,b.y,this.stats(b).range+2)){if(!this.targetable(a))continue;const p=this.config.enemies[a.type],t=rayBox(b.x,b.y,e.x,e.y,a.x,a.y,p.width,p.height);if(t<nearest){nearest=t;hit=a.id;}}return hit===e.id;}
 private buildings(){for(const b of this.s.buildings){if(!this.s.alive)break;if(!b.settled||b.hp<=0)continue;const p=this.stats(b);b.cooldown=Math.max(0,b.cooldown-DT);if(b.cooldown>1e-8)continue;
 if(b.type==='mine'){const n=Math.floor(p.production*(1+this.perk('mining')));this.s.gold+=n;b.cooldown=p.interval;this.emit('gold',b.x,b.y,b.x,b.y,'+'+n);continue;}
 if(b.type==='repair'){const targets=[{id:0,x:2,y:1,hp:this.s.coreHp,max:this.config.world.coreHp},...this.s.buildings.filter(f=>f.hp>0&&f.id!==b.id).map(f=>({...f,max:this.stats(f).hp}))].filter(f=>f.hp<f.max&&distance(b,f)<=p.range).sort((a,c)=>a.hp/a.max-c.hp/c.max||a.id-c.id);const f=targets[0];if(f){const hp=Math.min(f.max,f.hp+p.damage*(1+this.perk('repair_efficiency')));if(f.id===0)this.s.coreHp=hp;else this.s.buildings.find(a=>a.id===f.id)!.hp=hp;b.cooldown=p.interval;this.emit('repair',b.x,b.y,f.x,f.y);}continue;}
 if(!p.damage)continue;const targets=this.index.query(b.x,b.y,p.range).filter(e=>this.targetable(e)&&(b.type!=='frost'||!this.wallBetween(b,e))&&this.isAir(e)===(b.type==='anti_air')&&distance(b,e)<=p.range&&distance(b,e)>=p.minRange).sort((a,c)=>Math.hypot(a.x-2,a.y-1)-Math.hypot(c.x-2,c.y-1)||a.id-c.id);const manual=this.controlled===b.id;if(manual&&!this.aim.fire)continue;const chosen=manual?targets.filter(e=>distance(e,this.aim)<=Math.max(.8,this.config.enemies[e.type].width/2)).sort((a,c)=>distance(a,this.aim)-distance(c,this.aim)):targets;const e=['ballista','cannon','sniper'].includes(b.type)?chosen.find(e=>this.clearRay(b,e)):chosen[0];if(!e)continue;
 const boost=Math.max(0,...this.s.buildings.filter(f=>f.hp>0&&f.settled&&f.type==='amplifier'&&distance(f,b)<=this.stats(f).range).map(f=>this.stats(f).boost));const damage=p.damage*(1+this.perk('attack'))*(1+boost);b.cooldown=p.interval;
 if(b.type==='cannon'||b.type==='ballista'||b.type==='sniper'){const d=distance(b,e),dx=(e.x-b.x)/d,dy=(e.y-b.y)/d;const duration=Math.max(.08,(d-.48)/(b.type==='sniper'?this.config.schedule.bulletSpeed:b.type==='cannon'?this.config.schedule.cannonSpeed:this.config.schedule.arrowSpeed));this.s.shots.push({id:this.s.nextEntityId++,owner:b.id,kind:b.type==='sniper'?'bullet':b.type==='ballista'?'arrow':'cannon',phase:'flight',originX:b.x+dx*.48,originY:b.y+dy*.48,x:e.x,y:e.y,remaining:duration,duration,damage,radius:p.radius});this.emit(b.type,b.x,b.y,e.x,e.y);}else if(b.type==='mortar'){this.s.shots.push({id:this.s.nextEntityId++,owner:b.id,kind:'mortar',...mortarLaunch(b.x,b.y,e.x,e.y),x:e.x,y:e.y,remaining:.8,duration:.8,damage,radius:p.radius});this.emit('mortar',b.x,b.y,e.x,e.y);}else if(b.type==='frost'){for(const a of targets){this.hurtEnemy(a,damage,'cold');a.slows.push({amount:p.slow,until:this.time+p.slowDuration});}this.emit('frost',b.x,b.y,b.x+p.range,b.y);}else{this.hurtEnemy(e,damage);this.emit(b.type,b.x,b.y,e.x,e.y);}}
 }
 private bomb(e:Enemy,col:number,delay:number,damage:number){this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',phase:'warning',originX:e.x,originY:e.y-.4,x:col+.5,y:0,remaining:delay,duration:delay,damage,radius:e.type==='carrier'?this.config.schedule.carrierBombRadius:.8});}
 private wormMove(e:Enemy){
  const c=this.config.schedule,p=this.config.enemies[e.type];e.cooldown=Math.max(0,e.cooldown-DT);
  if(e.state==='walk'||e.state==='exposed'&&e.timer<=0){const targets=this.s.buildings.filter(b=>b.hp>0).sort((a,b)=>b.spent-a.spent||a.id-b.id);e.x=Math.max(5,Math.min(22,targets[0]?.x??10.5));e.y=0;e.state='burrow';e.timer=c.wormWarning;this.announce('裂地沙虫 / 地下巨震','红色通道内建筑将被逐层摧毁 · 出土后集火');}
  if(e.state==='burrow'){e.timer-=DT;if(e.timer<=0){e.state='erupt';e.timer=0;this.emit('rift',e.x,0);}return;}
  if(e.state==='erupt'){const before=e.y;e.y=Math.min(13,e.y+c.wormRiseSpeed*DT);for(const b of this.s.buildings){if(b.hp>0&&Math.abs(b.x-e.x)<p.width/2+.5&&b.y+.5>=before-p.height/2&&b.y-.5<=e.y+p.height/2){b.hp=0;this.emit('explosion',b.x,b.y);}}if(e.y>=13){e.y=p.height/2;e.state='exposed';e.timer=c.wormExpose;this.announce('沙虫出土 / 集火窗口','躯体已暴露 · 下一次钻地前尽快击杀');}return;}
  e.timer-=DT;
 }
 private newBoss(e:Enemy){
  const c=this.config.schedule,p=this.config.enemies[e.type];if(!['sandworm','queen','tempest'].includes(e.type))return false;
  const targets=[{id:0,x:2,y:1},...this.s.buildings.filter(b=>b.hp>0&&b.settled)].sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id);
  if(e.type==='sandworm'){if(e.state==='exposed'&&e.cooldown<=0){const target=targets.find(b=>distance(b,e)<5);if(target){this.explosion(target.x,target.y,1.5,p.damage*e.attackScale);e.cooldown=p.interval;}}return true;}
  if(e.type==='tempest'&&e.x>30)return true;e.special=(e.special??5)-DT;e.secondary=(e.secondary??8)-DT;
  if(e.special<=0){if(e.type==='queen'){for(const [i,type] of ['leaper','blastbeetle','leaper','grunt'].entries())this.spawn(type,false,Math.min(38,e.x+i*.6));this.emit('summon',e.x,e.y);e.special=c.queenBroodEvery;}
   else{for(const target of targets.slice(0,3))this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'laser',phase:'warning',visual:'lightning',originX:e.x,originY:e.y,x:target.x,y:0,remaining:2.8,duration:2.8,damage:p.damage*e.attackScale,radius:1.2});this.announce('雷暴巨兽 / 连锁落雷','三处落雷区域已标记 · 保留维修与重建资金');e.special=c.tempestLightningEvery;}}
  if(e.secondary<=0){for(const [i,target] of targets.slice(0,3).entries())this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',phase:'warning',visual:e.type==='queen'?'acid':'plasma',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:1.6+i*.2,duration:1.6+i*.2,damage:(e.type==='queen'?40:60)*e.attackScale,radius:1.2});e.secondary=e.type==='queen'?c.queenAcidEvery:c.tempestOrbEvery;}return true;
 }
 private bossExtras(e:Enemy){if(this.newBoss(e))return;
 const c=this.config.schedule,beast=e.type==='beast';
 if(!beast&&e.x>c.carrierEngageX)return;
 e.special=(e.special??(beast?c.beastStompCooldown:c.carrierLaserCooldown))-DT;
 e.secondary=(e.secondary??(beast?c.beastRockCooldown:c.carrierMissileCooldown))-DT;
 const friends=[{id:0,x:2,y:1},...this.s.buildings.filter(b=>b.hp>0&&b.settled)].filter(b=>!beast||b.x<e.x&&distance(b,e)<=10).sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id);
 const target=friends[0];if(!target)return;
 if(e.special<=0&&(!beast||distance(target,e)<=4)&&e.state==='walk'){
  const kind=beast?'shockwave':'laser',delay=beast?1.4:2;
  this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind,phase:'warning',originX:e.x,originY:e.y,x:beast?e.x:Math.floor(target.x)+.5,y:beast?.3:0,remaining:delay,duration:delay,damage:(beast?c.beastStompDamage:c.carrierLaserDamage)*e.attackScale,radius:beast?c.beastStompRadius:.7});
  e.special=beast?c.beastStompCooldown:c.carrierLaserCooldown;
 }
 if(e.secondary<=0&&e.state==='walk'){
  if(beast){this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'rock',phase:'warning',originX:e.x,originY:e.y+.4,x:target.x,y:target.y,remaining:1.1,duration:1.1,damage:c.beastRockDamage*e.attackScale,radius:1.1});e.secondary=c.beastRockCooldown;}
  else{for(let i=0;i<4;i++){const t=friends[i%friends.length];this.bomb(e,Math.floor(t.x),1.2+i*.25,c.carrierMissileDamage*e.attackScale);this.s.shots[this.s.shots.length-1].visual='missile';}e.secondary=c.carrierMissileCooldown;}
 }
 }
 private enemies(){for(const e of this.s.enemies){if(e.hp<=0||!this.s.alive)continue;const p=this.config.enemies[e.type];if(e.descent)continue;if(p.boss)this.bossExtras(e);if(e.type==='sandworm'||e.type==='tempest')continue;if(e.type==='spitter'){const target=[{id:0,x:2,y:1},...this.s.buildings.filter(b=>b.hp>0&&b.settled)].filter(b=>distance(e,b)<=this.config.schedule.spitterRange).sort((a,b)=>distance(e,a)-distance(e,b)||a.id-b.id)[0];if(target&&e.cooldown<=0){const duration=Math.max(.35,distance(e,target)/8);this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',visual:'acid',phase:'flight',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:duration,duration,damage:p.damage*e.attackScale,radius:.35});e.cooldown=p.interval;e.attackAnim=.3;this.emit('enemyShot',e.x,e.y);}continue;}if(e.type==='carrier'){if(e.x>this.config.schedule.carrierEngageX)continue;e.skill-=DT;e.summon-=DT;if(e.skill<=0){let best=0,count=-1;for(let col=0;col<=21;col++){const n=this.s.buildings.filter(b=>b.hp>0&&b.x>=col&&b.x<col+3).length;if(n>count){count=n;best=col;}}for(let c=best;c<best+3;c++)this.bomb(e,c,2,p.damage*e.attackScale);e.skill=this.config.schedule.carrierBombEvery;this.announce('母舰 / 地毯轰炸','连续三列遭到锁定 · 注意上层防御');}if(e.summon<=0){for(let i=0;i<3;i++)this.spawn('flyer',false,e.x+i*.6,e.y);const before=this.s.enemies.length;this.spawn('spitter',false,Math.min(23,e.x-3),e.y-1);if(this.s.enemies.length>before)this.s.enemies[this.s.enemies.length-1].descent=true;this.emit('summon',e.x,e.y);e.summon=this.config.schedule.carrierSummonEvery;}continue;}
 if(e.type==='bombardier'){if(e.x<24&&e.cooldown<=0){const b=this.s.buildings.filter(b=>b.hp>0&&b.settled&&Math.abs(b.x-e.x)<=6).sort((a,b)=>b.spent-a.spent||a.id-b.id)[0];if(b||e.x<=2.01){this.bomb(e,b?Math.floor(b.x):1,1.5,p.damage*e.attackScale);e.cooldown=p.interval;}}continue;}
 if(e.type==='flyer'){if(distance(e,{x:2,y:3})<.05&&e.cooldown<=0){this.hurtFriend(0,p.damage*e.attackScale);e.cooldown=p.interval;e.attackAnim=.3;this.emit('flyerAttack',e.x,e.y,2,1);}continue;}
 const o=this.obstacles().find(b=>b.id===e.target);if(e.type==='beast'&&e.state==='walk'){e.skill-=DT;if(e.skill<=0&&o&&e.x-p.width/2-o.x-o.w/2<=8){e.state='charge';e.timer=2;continue;}}
 if(e.state==='charge'||e.state==='dash')continue;
 if(e.state==='fuse'){e.timer-=DT;if(e.timer<=0){this.explosion(e.x,e.y,1.4,p.damage*e.attackScale);e.hp=0;}continue;}
 if(o&&e.x-p.width/2<=o.x+o.w/2+.001&&e.cooldown<=0){if(e.type==='bomber'){e.state='fuse';e.timer=1.2;}else{if(p.boss)this.explosion(o.x,o.y,this.config.schedule.beastMeleeRadius,p.damage*e.attackScale);else this.hurtFriend(o.id,p.damage*e.attackScale,e);e.cooldown=p.interval;e.attackAnim=.3;this.emit(e.type==='siege'?'siegeAttack':e.type==='beast'?'beastAttack':e.type==='runner'?'runnerAttack':'clawAttack',e.x,e.y,o.x,o.y);}}}}
 private projectiles(){for(const s of [...this.s.shots]){
 if(!this.s.alive)break;if(!this.s.shots.includes(s))continue;
 if(s.kind==='arrow'||s.kind==='cannon'||s.kind==='bullet'){
 const ox=s.originX??s.x,oy=s.originY??s.y,previous=1-s.remaining/s.duration;
 s.remaining=Math.max(0,s.remaining-DT);const t=1-s.remaining/s.duration;
 const x=ox+(s.x-ox)*previous,y=oy+(s.y-oy)*previous,tx=ox+(s.x-ox)*t,ty=oy+(s.y-oy)*t;
 let first=Infinity,victim:Enemy|undefined;
 for(const b of this.s.buildings.filter(b=>b.hp>0&&b.id!==s.owner&&this.blocksFriendly(b.type,s.kind)).map(b=>({...b,w:1,h:1})))first=Math.min(first,rayBox(x,y,tx,ty,b.x,b.y,b.w,b.h));
 for(const enemy of this.index.query((x+tx)/2,(y+ty)/2,Math.hypot(tx-x,ty-y)/2+2)){const p=this.config.enemies[enemy.type];if(!this.targetable(enemy)||this.isAir(enemy))continue;const hit=rayBox(x,y,tx,ty,enemy.x,enemy.y,p.width+.08,p.height+.08);if(hit<first){first=hit;victim=enemy;}}
 if(first<=1||s.remaining<=1e-7){const hx=first<=1?x+(tx-x)*first:tx,hy=first<=1?y+(ty-y)*first:ty;
 if(s.kind==='cannon'&&this.reflect(s,hx,hy))continue;
 if(s.kind==='cannon'){this.emit('explosion',hx,hy);for(const enemy of this.index.query(hx,hy,s.radius))if(!this.isAir(enemy)&&distance({x:hx,y:hy},enemy)<=s.radius)this.hurtEnemy(enemy,s.damage,'explosion');}
 else if(victim){this.hurtEnemy(victim,s.damage);this.emit('arrowHit',hx,hy);}else this.emit('dust',hx,hy);
 this.s.shots=this.s.shots.filter(a=>a.id!==s.id);}continue;
 }
 if(s.kind==='mortar'){
 const prev=shellPath(s,1-s.remaining/s.duration);s.remaining=Math.max(0,s.remaining-DT);const next=shellPath(s,1-s.remaining/s.duration);let first=Infinity;
 for(const b of this.s.buildings.filter(b=>b.hp>0&&b.id!==s.owner&&this.blocksFriendly(b.type,s.kind)))first=Math.min(first,rayBox(prev.x,prev.y,next.x,next.y,b.x,b.y,1.1,1.1));
 if(first<=1){s.x=prev.x+(next.x-prev.x)*first;s.y=prev.y+(next.y-prev.y)*first;s.remaining=0;}if(s.remaining>1e-7)continue;
 if(this.reflect(s,s.x,s.y))continue;this.emit('explosion',s.x,s.y);for(const a of this.index.query(s.x,s.y,s.radius))if(!this.isAir(a)&&distance(s,a)<=s.radius)this.hurtEnemy(a,s.damage,'explosion');this.s.shots=this.s.shots.filter(a=>a.id!==s.id);continue;
 }
 const physical=['bomb','rock'].includes(s.kind);
 if(physical&&s.phase==='flight'){
  const prev=enemyProjectilePosition(s,1-s.remaining/s.duration);s.remaining=Math.max(0,s.remaining-DT);const next=enemyProjectilePosition(s,1-s.remaining/s.duration);
  let first=Infinity;
  for(const b of [{x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0).map(b=>({...b,w:1,h:1}))]){first=Math.min(first,rayBox(prev.x,prev.y,next.x,next.y,b.x,b.y,b.w+.22,b.h+.22));}
  if(first<=1||s.remaining<=1e-7){const hit=first<=1?{x:prev.x+(next.x-prev.x)*first,y:prev.y+(next.y-prev.y)*first}:next;this.explosion(hit.x,hit.y,s.radius,s.damage);this.s.shots=this.s.shots.filter(a=>a.id!==s.id);}continue;
 }
 s.remaining-=DT;if(s.remaining>1e-7)continue;
 if(physical){const owner=this.s.enemies.find(e=>e.id===s.owner&&e.hp>0);if(!owner){this.s.shots=this.s.shots.filter(a=>a.id!==s.id);continue;}
  s.phase='flight';s.originX=owner.x;s.originY=owner.y+(s.kind==='rock'?.4:-.35);s.duration=this.config.schedule.enemyBombFlight??.9;s.remaining=s.duration;owner.attackAnim=.3;this.emit('bombRelease',s.originX,s.originY);continue;
 }
 if(s.kind==='shockwave'){this.explosion(s.x,s.y,s.radius,s.damage);this.emit('shockwave',s.x,s.y,s.x+s.radius,s.y);}
 else{const col=Math.floor(s.x),top=Math.max(col===1||col===2?2:0,...this.s.buildings.filter(b=>b.hp>0&&Math.floor(b.x)===col).map(b=>b.y+.5));this.explosion(s.x,top,s.radius,s.damage);if(s.kind==='laser')this.emit('bossLaser',s.originX??s.x,s.originY??11,s.x,top);}
 this.s.shots=this.s.shots.filter(a=>a.id!==s.id);
 }}
 private offer(){if(!this.s.perkQueue||this.s.candidates.length||!this.s.alive)return;const pool=Object.keys(this.config.perks).filter(k=>(this.s.perks[k]||0)<this.config.perks[k].max);while(pool.length&&this.s.candidates.length<3)this.s.candidates.push(pool.splice(Math.floor(random(this.s)*pool.length),1)[0]);if(!this.s.candidates.length)this.s.candidates=['supply'];}
 choose(id:string){if(!this.s.alive||!this.s.candidates.includes(id))return;const ratios=this.s.buildings.map(b=>b.hp/this.stats(b).hp);if(id==='supply')this.s.gold+=100;else this.s.perks[id]=(this.s.perks[id]||0)+1;if(id==='durability')this.s.buildings.forEach((b,i)=>b.hp=this.stats(b).hp*ratios[i]);if(id==='core_repair')this.s.coreHp=Math.min(this.config.world.coreHp,this.s.coreHp+this.config.perks[id].value);this.s.candidates=[];this.s.perkQueue--;this.offer();}
 step(){if(!this.running)return;const previousLevel=this.level;this.s.tick++;if(this.level!==previousLevel&&this.config.schedule.liveGrowth)this.growEnemies(previousLevel-1,this.level-1);if(this.time>=this.messageUntil)this.message='';this.effects=this.effects.map(e=>({...e,life:e.life-DT})).filter(e=>e.life>0);this.commands();this.s.dropCooldown=Math.max(0,this.s.dropCooldown-DT);this.schedule();this.events();if(!this.s.buildings.some(b=>b.id===this.controlled&&b.hp>0&&b.settled))this.controlled=0;this.index.rebuild(this.s.enemies);this.structure();this.move();if(!this.s.alive)return;this.index.rebuild(this.s.enemies);this.buildings();this.enemies();this.projectiles();this.s.buildings=this.s.buildings.filter(b=>b.hp>0);this.s.enemies=this.s.enemies.filter(e=>e.hp>0);if(!this.s.alive)return;
 if(this.demolition){const b=this.s.buildings.find(b=>b.id===this.demolition!.id&&b.settled);if(!b)this.demolition=null;else{this.demolition.elapsed+=DT;if(this.demolition.elapsed>=1){this.s.gold+=this.refund(b);this.s.buildings=this.s.buildings.filter(a=>a.id!==b.id);this.demolition=null;}}}
 this.s.passive+=DT;if(this.s.passive+1e-8>=this.config.schedule.passiveEvery){this.s.passive-=this.config.schedule.passiveEvery;this.s.gold+=this.config.schedule.passiveGold+this.perk('subsidy');}this.s.maxThreat=Math.max(this.s.maxThreat,this.level);if(this.time>=this.s.nextPerk){this.s.perkQueue++;this.s.nextPerk+=this.config.schedule.perkEvery;}this.offer();}
 snapshot(){const s=structuredClone(this.s);s.commands=s.commands.filter(c=>c.type!=='demolish'&&c.type!=='cancelDemolish');return s;}
}
