import {lordHealth} from './lord-balance';
import {CAMPAIGNS,campaignFor} from './campaigns';
import {EVENTS} from './incidents';
import {migrateBalance} from './balance';
import {enemyProjectilePosition} from './enemy-projectiles';
import {supportedBuildings} from './systems/support';
import {shellPath,mortarLaunch} from './trajectory';
import type {Config,World,Building,Enemy,Command,Effect,Shot,Difficulty} from './types';
import {random} from './random';
import {Spatial,distance,rayBox} from './systems/spatial';
const DT=1/60;
export class Engine {
 s:World; viewSide:"left"|"right"="right"; relocating=0; partTarget:'auto'|'hull'|'hangar'|'missiles'|'core'='auto'; controlled=0; controlledIds:number[]=[]; aim:{x:number;y:number;fire:boolean}={x:0,y:0,fire:false}; alert={title:'',detail:'',until:0}; paused=false; effects:Effect[]=[]; sounds:string[]=[]; message='';messageUntil=0; demolition:{id:number;elapsed:number}|null=null;
 private index=new Spatial<Enemy>();
 constructor(public config:Config,seed=20260905,runId='run-'+seed,snapshot?:World){this.s=snapshot?structuredClone(snapshot):{balanceRevision:config.balanceRevision??1,schemaVersion:1,configVersion:config.configVersion,runId,seed:seed>>>0||1,rng:seed>>>0||1,nextEntityId:1,revision:0,tick:0,gold:config.world.initialGold,coreHp:config.world.coreHp,maxThreat:1,kills:0,bossKills:0,alive:true,buildings:[],enemies:[],shots:[],spawnCredit:0,bossRequests:0,bossWarning:-1,bossCount:0,lastBossDeath:-999,nextBoss:300,nextPerk:120,passive:0,perks:{},perkQueue:0,candidates:[],dropCooldown:0,commands:[]};if(snapshot)migrateBalance(this.s,config);this.s.difficulty??='easy';this.s.nextEvent??=Math.max(this.config.schedule.eventFirst,this.time+20);this.s.eventCount??=0;this.s.eventDebt??=0;this.s.event??=null;for(const a of this.s.enemies)if(a.type==='carrier'&&!a.parts&&config.schedule.carrierParts){const max=a.maxHp*config.schedule.carrierParts;a.parts={hangar:max,missiles:max,max};}for(const a of this.s.enemies)if(a.type==='leviathan'&&a.maxHp!==lordHealth(this.config)){a.hp=lordHealth(this.config)*Math.max(0,Math.min(1,a.hp/a.maxHp));a.maxHp=lordHealth(this.config);a.shield=0;}if(snapshot)this.paused=true;}
 difficultyStats(d:Difficulty=this.s.difficulty??'easy'){const c=this.config.schedule;return d==='easy'?{hp:1,damage:1,rate:1}:{hp:c[d+'Hp'],damage:c[d+'Damage'],rate:c[d+'Rate']};}
 setDifficulty(d:Difficulty){if(!['easy','normal','hard'].includes(d))return;const old=this.difficultyStats(),next=this.difficultyStats(d);for(const e of this.s.enemies){e.hp*=next.hp/old.hp;e.maxHp*=next.hp/old.hp;e.shield*=next.hp/old.hp;if(e.parts){e.parts.hangar*=next.hp/old.hp;e.parts.missiles*=next.hp/old.hp;e.parts.max*=next.hp/old.hp;}e.attackScale*=next.damage/old.damage;}this.s.difficulty=d;}
 blocksFriendly(type:string,kind:string){return this.s.difficulty==='hard'&&type==='wall'&&kind!=='bullet';}
 wallBetween(b:Building,e:Enemy){return this.s.buildings.some(f=>f.id!==b.id&&f.hp>0&&this.blocksFriendly(f.type,b.type)&&rayBox(b.x,b.y,e.x,e.y,f.x,f.y,1,1)<=1);}
 notify(text:string){this.message=text;this.messageUntil=this.time+3;}
 get chapter(){return this.s.campaign?campaignFor(this.s.campaign.stage,this.s.campaign.timelineVersion):undefined;}
 buildingUnlocked(kind:string){return !this.chapter||this.chapter.buildings.includes(kind);}
 startCampaign(stage:number){const c=CAMPAIGNS[stage];if(!c||this.s.tick!==0)return;this.s.campaign={stage,spawned:0,won:false,timelineVersion:3};this.s.testMode=false;this.s.gold=c.gold;this.setDifficulty(c.difficulty);this.s.nextBoss=c.bossAt;this.s.nextEvent=c.events.length?75:999999999;}
 get leftOpen(){return !!this.s.testMode&&this.time>=600;} get minColumn(){return this.leftOpen?-20:0;}
 get time(){return this.s.tick/60;} get level(){return 1+Math.floor(this.time/60);} get cinematic(){const m=this.s.campaign;return m?.timelineVersion===3&&m.revealFrame!==null&&m.revealFrame!==undefined&&m.revealFrame<720;} get running(){return !this.cinematic&&!this.paused&&this.s.alive&&!this.s.candidates.length&&!this.s.campaign?.won;}
 perk(id:string){return (this.s.perks[id]||0)*(this.config.perks[id]?.value||0);}
 stats(b:Building){const base=this.config.buildings[b.type];const p={...base,...(b.branch>=0?base.branches[b.branch]:{})};return {...p,hp:p.hp*(1+this.perk('durability'))};}
 emit(kind:string,x:number,y:number,tx=x,ty=y,text?:string){if(this.sounds.length<64)this.sounds.push(kind);if(this.effects.length<500)this.effects.push({kind,x,y,tx,ty,life:kind==='tidalRise'?3:kind==='tidalBurst'?1.5:kind==='hatch'?1.5:kind==='rift'?3:kind==='wreckBlast'?1.5:kind==='mechBurst'?.9:kind==='explosion'?.55:.3,text});}
 command(c:Command){if(this.running)this.s.commands.push(c);}
 top(col:number){return Math.max(col===1||col===2?2:0,...this.s.buildings.filter(b=>b.hp>0&&b.settled&&Math.floor(b.x)===col).map(b=>b.y+.5));}
 buildingCount(kind:string){return this.s.buildings.filter(b=>b.type===kind&&b.hp>0).length;}
 buildingLimit(kind:string){const p=this.config.buildings[kind];return (this.s.difficulty==='easy'?p?.easyLimit:undefined)??p?.limit??Infinity;}
 targetable(e:Enemy){return e.hp>0&&!(['sandworm','burrow_nest'].includes(e.type)&&e.state==='burrow');}
 invalid(kind:string,col:number,layer?:number){const c=this.config.buildings[kind];if(!c)return '请选择建筑';if(!this.buildingUnlocked(kind))return '此建筑尚未在本关解锁';if(this.buildingCount(kind)>=this.buildingLimit(kind))return `${c.name}已达上限 ${this.buildingLimit(kind)} 座`; if(!Number.isInteger(col)||col<this.minColumn||col>=this.config.world.columns)return '超出建造区域';if(this.s.gold<c.cost)return '金币不足';if(this.s.dropCooldown>1e-7)return '吊装冷却中';if(this.s.buildings.some(b=>Math.floor(b.x)===col&&!b.settled&&b.hp>0))return '该列正在下落 / 坍塌';if(kind==='bridge'){if(layer===undefined||!Number.isInteger(layer)||layer<0||layer>=this.config.world.layers)return '请选择桥梁高度';if((col===1||col===2)&&layer<2||this.s.buildings.some(b=>b.hp>0&&Math.floor(b.x)===col&&Math.abs(b.y-(layer+.5))<1))return '该格已被占用';const candidate:Building={id:-1,type:'bridge',x:col+.5,y:layer+.5,hp:1,settled:true,branch:-1,spent:0,v:0,fallId:1,hit:[],cooldown:0};if(!supportedBuildings([...this.s.buildings,candidate]).has(-1))return '需要连接地面、核心或已支撑建筑';return '';}if(this.top(col)>=this.config.world.layers)return '该列已达到最高层';return '';}
 refund(b:Building){return Math.floor(b.spent*.6*b.hp/this.stats(b).hp);}
 isAir(e:Enemy){return this.config.enemies[e.type].air||!!e.descent;}
 squadMembers(slot:number){return [...new Set(this.s.squads?.[slot]??[])].filter(id=>this.s.buildings.some(b=>b.id===id&&b.hp>0));}
 assignSquad(slot:number,ids:number[],append=false){if(!Number.isInteger(slot)||slot<0||slot>=5)return;this.s.squads=Array.from({length:5},(_,i)=>this.squadMembers(i));this.s.squads[slot]=[...new Set([...(append?this.squadMembers(slot):[]),...ids])].filter(id=>this.s.buildings.some(b=>b.id===id&&b.hp>0));}
 controlMany(ids:number[]){this.controlledIds=[...new Set(ids)].filter(id=>{const b=this.s.buildings.find(b=>b.id===id&&b.hp>0&&b.settled);return b&&['ballista','mortar','cannon','sniper','anti_air','frost'].includes(b.type);});this.controlled=this.controlledIds[0]??0;this.aim.fire=false;}
 control(id:number){const b=this.s.buildings.find(b=>b.id===id&&b.hp>0&&b.settled);this.controlled=b&&['ballista','mortar','cannon','sniper','anti_air','frost'].includes(b.type)?id:0;this.controlledIds=this.controlled?[this.controlled]:[];this.aim.fire=false;}
 upgradeSelection(ids:number[],branch:number){const buildings=this.s.buildings.filter(b=>ids.includes(b.id)&&b.hp>0&&b.settled&&b.branch<0);return {buildings,cost:buildings.reduce((n,b)=>n+this.stats(b).upgradeCost,0),branch};}
 announce(title:string,detail:string){this.alert={title,detail,until:this.time+4};this.emit('alarm',2,1);}
 private commands(){for(const c of this.s.commands.splice(0)){if(c.type==='relocate'){this.relocate(c.id,c.column,c.layer);continue;}if(c.type==='upgradeMany'){const group=this.upgradeSelection(c.ids,c.branch);if(![0,1].includes(c.branch)||!group.buildings.length||this.s.gold<group.cost){this.notify('批量升级失败：金币不足或没有可升级建筑');continue;}for(const b of group.buildings){const p=this.stats(b),ratio=b.hp/p.hp;this.s.gold-=p.upgradeCost;b.spent+=p.upgradeCost;b.branch=c.branch;b.hp=this.stats(b).hp*ratio;this.emit('upgrade',b.x,b.y);}continue;}if(c.type==='drop'){const reason=this.invalid(c.kind,c.column,c.layer);if(reason){this.notify(reason);continue;}const p=this.config.buildings[c.kind];this.s.gold-=p.cost;const id=this.s.nextEntityId++;const b:Building={id,type:c.kind,branch:-1,spent:p.cost,x:c.column+.5,y:c.kind==='bridge'?c.layer!+.5:this.config.world.dropY,v:0,hp:p.hp*(1+this.perk('durability')),settled:c.kind==='bridge',fallId:1,hit:[],cooldown:c.kind==='mine'?p.interval:0};this.s.buildings.push(b);this.s.dropCooldown=Math.max(.6,this.config.world.deployCooldown-this.perk('deployment'));this.emit('drop',b.x,b.y);}else if(c.type==='cancelDemolish')this.demolition=null;else{const b=this.s.buildings.find(b=>b.id===c.id&&b.hp>0&&b.settled);if(!b)continue;if(c.type==='demolish'){this.demolition={id:b.id,elapsed:0};}else if(b.branch<0&&(c.branch===0||c.branch===1)&&this.s.gold>=this.stats(b).upgradeCost){const old=this.stats(b),ratio=b.hp/old.hp;this.s.gold-=old.upgradeCost;b.spent+=old.upgradeCost;b.branch=c.branch;b.hp=this.stats(b).hp*ratio;this.emit('upgrade',b.x,b.y);}}}}
 private structure(){const supported=supportedBuildings(this.s.buildings);for(const b of this.s.buildings){if(b.hp>0&&b.settled&&!supported.has(b.id)){b.settled=false;b.v=0;b.fallId++;b.hit=[];}}for(let col=this.minColumn;col<this.config.world.columns;col++){let top=col===1||col===2?2:0;let supportSettled=true;const stack=this.s.buildings.filter(b=>b.hp>0&&Math.floor(b.x)===col).sort((a,b)=>a.y-b.y||a.id-b.id);for(const b of stack){if(b.settled&&!supported.has(b.id)&&(!supportSettled||b.y-.5>top+1e-6)){b.settled=false;b.v=0;b.fallId++;b.hit=[];}
 if(!b.settled){const prev=b.y;b.v=Math.min(this.config.world.maxVelocity,b.v+this.config.world.gravity*DT);b.y=Math.max(top+.5,b.y-b.v*DT);for(const e of this.index.query(b.x,(prev+b.y)/2,Math.max(2,prev-b.y+2))){const p=this.config.enemies[e.type];if(e.hp>0&&!b.hit.includes(e.id)&&Math.abs(e.x-b.x)<=.5+p.width/2&&e.y+p.height/2>=b.y-.5&&e.y-p.height/2<=prev+.5){b.hit.push(e.id);this.hurtEnemy(e,this.stats(b).impact*(1+this.perk('impact')),'impact');}}if(supportSettled&&b.y<=top+.5+1e-7){b.y=top+.5;b.v=0;b.settled=true;this.emit('dust',b.x,b.y);}}
 top=b.y+.5;supportSettled=b.settled;}}
 for(const e of this.s.enemies){const p=this.config.enemies[e.type];if(this.isAir(e)||e.hp<=0||e.type==='sandworm'||e.type==='leviathan'&&this.s.campaign?.timelineVersion===3||e.type==='burrow_nest'&&e.state==='burrow')continue;let changed=true;while(changed){changed=false;for(const b of this.obstacles()){if(e.x-p.width/2<b.x+b.w/2-1e-7&&e.x+p.width/2>b.x-b.w/2+1e-7){e.x=e.side==='left'?b.x-b.w/2-p.width/2:b.x+b.w/2+p.width/2;changed=true;}}}}
 }
 private obstacles(){return [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0&&b.settled&&b.y<.51).map(b=>({id:b.id,x:b.x,y:b.y,w:1,h:1}))].sort((a,b)=>b.x-a.x);}
 private hurtEnemy(e:Enemy,damage:number,kind='physical'){if(!this.targetable(e)||!this.s.alive)return;if(kind==='explosion'&&e.type==='blastbeetle')damage*=1-this.config.schedule.blastResistance;const cover=kind==='friendlyBlast'?undefined:this.escortAnchor(e,true);if(cover){const intercepted=Math.min(cover.shield,damage*(this.config.schedule.shieldCoverShare??.7));cover.shield-=intercepted;damage-=intercepted;if(cover.shield<=0)this.emit('shieldBreak',cover.x,cover.y);}const shield=Math.min(e.shield,damage);e.shield-=shield;if(shield>0&&e.shield===0)this.emit('shieldBreak',e.x,e.y);damage-=shield;if(damage>0){let hit=Math.max(1,damage*(kind==='physical'?1-e.armor:1));if(e.type==='leviathan'&&e.hp<=e.maxHp*.5)hit*=1.15;if(e.type==='carrier'&&e.parts){if(this.partTarget==='core')hit*=this.time<(e.weakUntil??0)?1.6:.65;else if(this.partTarget==='hangar'||this.partTarget==='missiles'){const part=this.partTarget;if(e.parts[part]>0){e.parts[part]=Math.max(0,e.parts[part]-hit);if(e.parts[part]===0){this.emit('mechBurst',e.x,e.y);this.announce('母舰部位摧毁',part==='hangar'?'机库失效 · 召唤显著减少':'导弹舱失效 · 停止后续齐射');}hit*=.65;}}}e.hp-=hit;}if(e.hp<=0){e.hp=0;this.s.gold+=e.reward;this.s.kills++;if(this.config.enemies[e.type].boss){this.s.bossKills++;this.s.lastBossDeath=this.time;if(!this.s.campaign)this.s.perkQueue++;this.s.shots=this.s.shots.filter(s=>s.owner!==e.id||s.phase==='flight');}this.mechanicalDeath(e);if(e.type==='leviathan')this.emit('tidalRise',e.x,0);this.emit('kill',e.x,e.y,e.x,e.y,'+'+e.reward);}}
 private hurtFriend(id:number,amount:number,attacker?:Enemy){if(!this.s.alive)return;if(id===0){this.s.coreHp=Math.max(0,this.s.coreHp-amount);if(this.s.coreHp<=0){this.s.alive=false;this.s.candidates=[];this.s.perkQueue=0;this.demolition=null;this.emit('failure',2,1);}return;}const b=this.s.buildings.find(b=>b.id===id);if(!b||b.hp<=0)return;b.hp=Math.max(0,b.hp-amount);this.emit('hit',b.x,b.y);if(attacker&&this.stats(b).thorns)this.hurtEnemy(attacker,this.stats(b).thorns,'true');}
 private explosion(x:number,y:number,r:number,damage:number){this.emit('explosion',x,y);if(this.s.crate&&distance(this.s.crate,{x,y})<=r+.5){this.s.crate.hp-=damage;if(this.s.crate.hp<=0){this.emit('explosion',this.s.crate.x,this.s.crate.y);this.s.crate=null;this.announce('军械箱损毁','本次回收失败');}}for(const b of [{id:0,x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0).map(b=>({...b,w:1,h:1}))]){if(!this.s.alive)break;const dx=Math.max(Math.abs(x-b.x)-b.w/2,0),dy=Math.max(Math.abs(y-b.y)-b.h/2,0);if(dx*dx+dy*dy<=r*r)this.hurtFriend(b.id,damage);}}
 spawn(type:string,eliteAllowed=true,x=35.5,y?:number,eventUnit=false){if(type==='leviathan'&&(!this.s.campaign||this.s.campaign.timelineVersion===3&&(this.s.campaign.revealFrame??0)<720))return;if(type==='sandworm'&&!this.s.campaign&&this.time<900)return;if(!this.s.campaign&&this.s.difficulty==='hard'&&this.s.bossCount===0&&this.config.enemies[type]?.boss&&this.config.enemies.beast){type='beast';y=undefined;}const p=this.config.enemies[type];if(!p)return;if(this.chapter&&!this.chapter.enemies.includes(type)&&!this.chapter.bosses.includes(type))return;if(type==='burrow_nest'&&this.s.enemies.filter(a=>a.type===type&&a.hp>0).length>=2)return;if(type==='burrow_nest'){x=this.s.buildings.filter(b=>b.hp>0&&b.settled&&b.x>=0).sort((a,b)=>b.spent-a.spent||a.id-b.id)[0]?.x??18.5;y=0;}if(type==='fortress'&&this.s.enemies.filter(a=>a.type==='fortress'&&a.hp>0).length>=(this.config.schedule.fortressCap??2))return;if(p.boss&&this.s.enemies.filter(a=>a.hp>0&&this.config.enemies[a.type].boss).length>=(this.chapter?.bosses.length??1))return;if(!p.boss&&this.s.enemies.filter(e=>e.hp>0&&!this.config.enemies[e.type].boss).length>=this.config.schedule.enemyCap-(eventUnit?0:(this.config.schedule.eventReserve??0)))return;const l=this.level-1,difficulty=this.difficultyStats(),growth=this.enemyGrowth(l);let maxHp=p.hp*difficulty.hp*growth.hp,attackScale=growth.damage*difficulty.damage,reward=p.reward,armor=p.armor,shield=0,elite='';if(p.boss){this.s.bossCount++;maxHp*=1+(this.config.schedule.bossHpGrowth??.15)*(this.s.bossCount-1);attackScale*=1+(this.config.schedule.bossDamageGrowth??0)*(this.s.bossCount-1);}else if(eliteAllowed&&this.level>=6&&random(this.s)<Math.min(.45,this.config.schedule.eliteChance+(this.config.schedule.eliteGrowth??0)*l)){maxHp*=1.8;attackScale*=1.25;reward*=2;elite=random(this.s)<.5?'shield':'armor';if(elite==='shield')shield=maxHp*.3;else armor=Math.min(.6,armor+.2);}
 if(type==='leviathan')maxHp=lordHealth(this.config);if(p.boss)shield=maxHp*(this.config.schedule.bossEntryShield??0);if(type==='reflector')shield=maxHp/ p.hp*this.config.schedule.reflectShield;if(type==='leviathan'){if(this.s.campaign)this.s.campaign.storm=true;shield=0;this.emit('tidalRise',x,0);}if(p.boss)this.announce(p.name+' · 已抵达',type==='leviathan'?'深海巨影 / 潮汐冲击 · 注意蓝色落点，准备拦截深水雷':type==='sandworm'?'地下钻出 / 沿途摧毁 · 注意垂直危险通道':type==='queen'?'孵化虫群 / 酸液喷射 · 配置混合火力':type==='tempest'?'连锁落雷 / 等离子弹 · 广域防空就位':type==='beast'?'破城冲撞 / 范围震击 · 分散后排、加固前墙':'空域封锁 / 导弹齐射 · 防空火力就位');
 this.s.enemies.push({parts:type==='carrier'&&this.config.schedule.carrierParts?{hangar:maxHp*this.config.schedule.carrierParts,missiles:maxHp*this.config.schedule.carrierParts,max:maxHp*this.config.schedule.carrierParts}:undefined,id:this.s.nextEntityId++,type,x,y:y??(type==='carrier'?11:type==='tempest'?9:type==='bombardier'?10:type==='suicide_ship'?8:type==='fortress'?6.5:p.air?5:p.height/2),hp:maxHp,maxHp,shield,armor,attackScale,speedScale:Math.min(1.3,1+this.config.schedule.speedGrowth*l),reward,elite,special:p.boss?this.config.schedule.bossOpeningDelay:undefined,secondary:p.boss?(this.config.schedule.bossOpeningDelay===undefined?undefined:this.config.schedule.bossOpeningDelay+1):undefined,cooldown:type==='bombardier'?4:0,slows:[],skill:type==='carrier'?4:12,summon:type==='leviathan'?6:type==='carrier'?3:type==='fortress'?4:15,state:type==='burrow_nest'?'burrow':'walk',timer:type==='burrow_nest'?6:0,distance:0,target:0});if(type==='burrow_nest'){this.s.enemies[this.s.enemies.length-1].elite='brood';this.announce('地渊孵化兽 / 地底巢穴接近','6 秒后破土摧毁出土区域建筑 · 立即吊装撤离，出土后集火');}}
 enemyGrowth(minutes=this.level-1){const c=this.config.schedule,ramp=Math.max(0,minutes-(c.growthRampMinute??10));return {hp:1+c.hpGrowth*minutes+(c.hpAcceleration??0)*ramp*ramp,damage:1+c.damageGrowth*minutes+(c.damageAcceleration??0)*ramp*ramp};}
 private growEnemies(before:number,after:number){const a=this.enemyGrowth(before),b=this.enemyGrowth(after);for(const e of this.s.enemies){if(e.hp<=0)continue;if(e.type!=='leviathan'){e.hp*=b.hp/a.hp;e.maxHp*=b.hp/a.hp;e.shield*=b.hp/a.hp;}if(e.parts){e.parts.hangar*=b.hp/a.hp;e.parts.missiles*=b.hp/a.hp;e.parts.max*=b.hp/a.hp;}e.attackScale*=b.damage/a.damage;e.speedScale=Math.min(1.3,e.speedScale*Math.min(1.3,1+this.config.schedule.speedGrowth*after)/Math.min(1.3,1+this.config.schedule.speedGrowth*before));}}
 private schedule(){if(this.chapter){this.campaignSchedule();return;}const s=this.s,c=this.config.schedule,t=this.time; if(s.tick===c.firstEnemy*60)this.spawn('grunt');if(t>=c.firstEnemy){const phase=t%60<35?1:t%60<50?1.6:.55;const boss=s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss);s.spawnCredit+=Math.min(c.maxRate,c.baseRate+c.rateGrowth*(this.level-1)+(c.lateRateGrowth??0)*Math.max(0,this.level-11))*this.difficultyStats().rate*phase*(s.bossRequests?1.2:boss?.8:1)*DT;while(s.spawnCredit>=1){s.spawnCredit--;if((s.eventDebt??0)>0){s.eventDebt!--;continue;}const pool=Object.entries(this.config.enemies).filter(([,p])=>p.weight&&!p.boss&&p.unlock<=t).map(([key,p])=>[key,{...p,weight:p.weight*(['siege','reflector','blastbeetle','spitter','bombardier'].includes(key)?1+(c.lateHeavyGrowth??0)*Math.min(3,Math.max(0,t-600)/600):1)}] as const);let n=random(s)*pool.reduce((a,[,p])=>a+p.weight,0);for(const [key,p] of pool){n-=p.weight;if(n<=0){this.spawn(key);break;}}}}
 if(t>=s.nextBoss-10&&s.bossWarning<0&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&t-s.lastBossDeath>=30){s.bossWarning=10;}
 if(t>=s.nextBoss){s.bossRequests=1;s.nextBoss+=c.bossEvery;}
 if(s.bossRequests&&s.bossWarning<0&&!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)&&t-s.lastBossDeath>=30)s.bossWarning=10;
 if(s.bossWarning>=0){s.bossWarning=Math.max(0,s.bossWarning-DT);if(s.bossWarning<=1e-7&&(s.bossRequests||t>=s.nextBoss)){const pool=Object.entries(this.config.enemies).filter(([type,p])=>p.boss&&type!=='leviathan'&&(type!=='sandworm'||t>=900)).sort((a,b)=>a[1].unlock-b[1].unlock);if(pool.length)this.spawn(pool[s.bossCount%pool.length][0],false);s.bossWarning=-1;s.bossRequests=0;}}
 }
 get campaignRelief(){const c=this.chapter;return !!c&&c.reliefStart!==undefined&&this.time>=c.reliefStart&&this.time<c.reliefEnd!;}
 get nextCampaignBossAt(){const c=this.chapter,m=this.s.campaign;return c&&m&&!(m.timelineVersion===3&&m.stage===4&&m.spawned>=2)&&m.spawned<c.bosses.length?(c.bossTimes?.[m.spawned]??c.bossAt):null;}
 private campaignSchedule(){const chapter=this.chapter!,s=this.s,mission=s.campaign!;
 if(mission.spawned===chapter.bosses.length&&s.bossKills>=chapter.bosses.length)return;
 if(chapter.reliefStart!==undefined&&s.tick===chapter.reliefStart*60)this.announce('港湾整备窗口 / 8:00—10:00','普通刷怪降至 35% · 修复防线，10:00 双统领合围');
 if(this.time>=10){s.spawnCredit+=(.22+mission.stage*.075+this.time*.0006)*(s.enemies.some(e=>this.config.enemies[e.type].boss)?.65:1)*(this.campaignRelief?.35:1)*DT;while(s.spawnCredit>=1){s.spawnCredit--;const pool=chapter.enemies.map(type=>[type,this.config.enemies[type].weight] as const);let n=random(s)*pool.reduce((sum,[,w])=>sum+w,0);for(const [type,w] of pool){n-=w;if(n<=0){this.spawn(type,false);break;}}}}
 const next=this.nextCampaignBossAt;s.nextBoss=next??999999999;
 if(next!==null&&this.time>=next-10){s.bossWarning=Math.max(0,next-this.time);let spawned=0;while(mission.spawned<chapter.bosses.length&&this.time>=(chapter.bossTimes?.[mission.spawned]??chapter.bossAt)){const before=s.enemies.length;this.spawn(chapter.bosses[mission.spawned],false,chapter.bosses[mission.spawned]==='leviathan'?30:35.5);if(s.enemies.length===before)break;mission.spawned++;spawned++;}if(spawned){s.bossWarning=-1;s.nextBoss=this.nextCampaignBossAt??999999999;this.announce(spawned>1?'终章 / 海空双统领降临':'战役目标 / '+this.config.enemies[chapter.bosses[mission.spawned-1]].name,chapter.bossTimes?(spawned>1?'母舰与潮汐领主合围 · 躲避蓝色落点、拦截深水雷':'女王虫巢已激活 · 8:00 整备，10:00 海空合围'):chapter.hint);}}
 }

 private startReveal(){const m=this.s.campaign;if(!this.s.alive||m?.stage!==4||m.timelineVersion!==3||!m.carrierCrashed||m.revealFrame!==undefined&&m.revealFrame!==null)return false;m.revealFrame=0;this.s.commands=[];this.effects=[];this.alert.until=0;this.control(0);this.aim.fire=false;this.demolition=null;this.relocating=0;this.sounds=['upgrade'];return true;}
 advanceReveal(){const m=this.s.campaign;if(!this.cinematic||this.paused||!this.s.alive||!m)return;m.revealFrame!++;if(m.revealFrame===180)this.sounds.push('hullCollision');if(m.revealFrame===240)this.sounds.push('oceanSurge');if(m.revealFrame===500)this.sounds.push('hullCollision');if(m.revealFrame===720){const before=this.s.enemies.length;this.spawn('leviathan',false,12,7);if(this.s.enemies.length>before){m.spawned++;m.storm=true;this.sounds.push('thunder');this.announce('真正的终战 / 深渊潮汐领主','沉船中的巨影已占据中央 · 暴雨将至，恢复战斗 · 经济产能 ×3');}else m.revealFrame=719;}}
 private campaignVictory(){const c=this.chapter,m=this.s.campaign;if(!c||!m||!this.s.alive||m.won||m.spawned<c.bosses.length||this.s.bossKills<c.bosses.length||this.s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss))return;if(this.s.shots.some(s=>s.kind==='wreck')){this.notify('统领已击败 · 躲过残骸坠爆后完成战役');return;}m.won=true;this.s.enemies=[];this.s.shots=[];this.s.event=null;this.s.candidates=[];this.s.perkQueue=0;this.s.commands=[];this.control(0);this.announce('战役胜利',c.outro);}
 private leftFront(){if(!this.s.testMode)return;if(this.s.tick===570*60)this.announce('测试模式 / 左翼即将开放','30 秒后开启左侧建造区 · 准备双线防守');if(!this.leftOpen)return;if(!this.s.leftOpened){this.s.leftOpened=true;this.s.nextLeft=this.time+20;this.announce('左侧战场开启 / 双线防守','点击左侧战场部署 · 20 秒后敌军抵达，两边持续战斗');}if(this.time<(this.s.nextLeft??620))return;const pool=['grunt','runner','siege','spitter','flyer'];const type=pool[Math.floor(random(this.s)*pool.length)],before=this.s.enemies.length;this.spawn(type,true,-31.5);if(this.s.enemies.length>before)this.s.enemies[this.s.enemies.length-1].side='left';this.s.nextLeft=this.time+(this.s.enemies.length>before?Math.max(.8,3-(this.time-600)/300)/this.difficultyStats().rate:1);}
 private leftMove(e:Enemy){const p=this.config.enemies[e.type];e.cooldown=Math.max(0,e.cooldown-DT);e.attackAnim=Math.max(0,(e.attackAnim??0)-DT);e.slows=e.slows.filter(a=>a.until>this.time);const speed=p.speed*e.speedScale*(1-Math.max(0,...e.slows.map(a=>a.amount)));if(p.air){const d=distance(e,{x:2,y:3}),f=Math.min(1,speed*DT/Math.max(.001,d));e.x+=(2-e.x)*f;e.y+=(3-e.y)*f;return;}const obstacle=this.obstacles().filter(b=>b.x>=e.x).sort((a,b)=>a.x-b.x)[0];e.target=obstacle?.id??0;if(e.type==='spitter'&&obstacle&&distance(e,obstacle)<=this.config.schedule.spitterRange)return;const bound=obstacle?obstacle.x-obstacle.w/2-p.width/2:1-p.width/2;e.x=Math.min(bound,e.x+speed*DT);}
 private leftAttack(e:Enemy){const p=this.config.enemies[e.type];if(e.cooldown>0)return;if(p.air){if(distance(e,{x:2,y:3})<.05){this.hurtFriend(0,p.damage*e.attackScale);e.cooldown=p.interval;this.emit('flyerAttack',e.x,e.y,2,1);}return;}const target=this.obstacles().find(b=>b.id===e.target);if(!target)return;if(e.type==='spitter'){if(distance(e,target)>this.config.schedule.spitterRange)return;const duration=Math.max(.35,distance(e,target)/8);this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',visual:'acid',phase:'flight',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:duration,duration,damage:p.damage*e.attackScale,radius:.35});this.emit('enemyShot',e.x,e.y);}else{if(e.x+p.width/2<target.x-target.w/2-.001)return;this.hurtFriend(target.id,p.damage*e.attackScale,e);this.emit(e.type==='siege'?'siegeAttack':'clawAttack',e.x,e.y,target.x,target.y);}e.cooldown=p.interval;e.attackAnim=.3;}
 private events(){
 if(this.chapter&&!this.chapter.events.length)return;const s=this.s,c=this.config.schedule;
 if(!this.campaignRelief&&!s.event&&(!this.chapter||this.s.campaign!.spawned<this.chapter.bosses.length)&&this.time>=s.nextEvent!&&(!s.enemies.some(e=>e.hp>0&&this.config.enemies[e.type].boss)||this.time-s.nextEvent!>=(c.eventMaxDelay??Infinity))&&s.bossWarning<0&&s.nextBoss-this.time>20){
  const cycle=this.chapter?.events??(['supply','missiles','airdrop','meteor','sabotage','breach','siege'] as const);let kind=cycle[s.eventCount!%cycle.length];if(kind==='sabotage'&&!s.buildings.some(b=>b.type==='mine'&&b.hp>0))kind='siege';const cols=this.s.buildings.filter(b=>b.hp>0&&b.x>=0&&(kind!=='sabotage'||b.type==='mine')).sort((a,b)=>b.spent-a.spent||a.id-b.id).map(b=>Math.floor(b.x));
  s.event={kind,remaining:c.eventWarning,columns:kind==='supply'?[20]:(kind==='missiles'||kind==='meteor'||kind==='sabotage')?[...new Set([...cols,1,5,9])].slice(0,3):kind==='breach'?[...new Set([...cols,10,16,22])].slice(0,3):[10,16,22]};s.eventCount!++;this.announce(EVENTS[kind].title,EVENTS[kind].detail);
 }
 if(!s.event)return;s.event.remaining-=DT;if(s.event.remaining>0)return;const event=s.event;
 const reinforcements=['airdrop','breach','siege'].includes(event.kind)?event.columns.length*(event.kind==='siege'?3:2):0;
 if(reinforcements&&s.enemies.filter(e=>e.hp>0&&!this.config.enemies[e.type].boss).length+reinforcements>c.enemyCap){event.remaining=1;return;}
 if(event.kind==='supply'){s.crate={x:event.columns[0]+.5,y:14,hp:c.crateHp??350,remaining:c.crateDuration??45,progress:0,falling:true};}
 else if(event.kind==='missiles')for(const col of event.columns){const delay=1+random(s)*.4;s.shots.push({id:s.nextEntityId++,owner:2147483647,kind:'bomb',phase:'flight',visual:'missile',originX:35,originY:15,x:col+.5,y:0,remaining:delay,duration:delay,damage:c.eventMissileDamage*this.difficultyStats().damage*this.enemyGrowth().damage,radius:c.eventMissileRadius});}
 else if(event.kind==='meteor')for(const col of event.columns){const duration=3+random(s)*.6;s.shots.push({id:s.nextEntityId++,owner:2147483647,kind:'rock',phase:'flight',visual:'meteor',originX:col+.5,originY:14,x:col+.5,y:0,remaining:duration,duration,damage:c.meteorDamage*this.difficultyStats().damage*this.enemyGrowth().damage,radius:c.meteorRadius});}
 else if(event.kind==='breach')for(const col of event.columns){this.explosion(col+.5,.5,1.2,90*this.difficultyStats().damage*this.enemyGrowth().damage);for(const type of ['leaper','spitter']){const before=s.enemies.length;this.spawn(type,false,this.broodExit(col+.5),undefined,true);if(s.enemies.length>before){const a=s.enemies[s.enemies.length-1];a.state='erupt';a.timer=1.2;s.eventDebt!++;}}this.emit('rift',col+.5,.1);}
 else if(event.kind==='sabotage'){for(const b of [...s.buildings])if(b.hp>0&&b.type==='mine'&&event.columns.includes(Math.floor(b.x))){this.hurtFriend(b.id,(c.sabotageDamage??145)*this.difficultyStats().damage*this.enemyGrowth().damage);this.emit('explosion',b.x,b.y);}for(const col of event.columns)this.emit('rift',col+.5,.1);}
 else for(const col of event.columns.slice(0,c.eventDropCount)){for(const [i,type] of (event.kind==='siege'?['reflector','siege','flyer']:['grunt','spitter']).entries()){const before=s.enemies.length;this.spawn(type,false,col+.5+i*.15,13-i*.7,true);if(s.enemies.length>before){const unit=s.enemies[s.enemies.length-1];unit.descent=!this.config.enemies[type].air;if(event.kind==='siege'){unit.hp*=1.5;unit.maxHp*=1.5;unit.shield+=unit.maxHp*.3;unit.elite='shield';unit.reward*=2;}if(event.kind==='airdrop')s.eventDebt!++;}}}
 this.announce(EVENTS[event.kind].active,EVENTS[event.kind].detail);s.event=null;s.nextEvent=this.time+c.eventEvery;
 }
 private reflect(s:Shot,x:number,y:number){const e=this.s.enemies.filter(e=>e.type==='reflector'&&this.targetable(e)&&!e.descent&&e.hp>0&&e.shield>0&&distance(e,{x,y})<=Math.max(.9,s.radius)).sort((a,b)=>distance(a,{x,y})-distance(b,{x,y})||a.id-b.id)[0];if(!e)return false;
  e.shield=Math.max(0,e.shield-s.damage*.65);const owner=this.s.buildings.find(b=>b.id===s.owner&&b.hp>0),target=owner??{x:2,y:1};s.kind='rock';s.visual='reflected';s.phase='flight';s.originX=x;s.originY=y;s.x=target.x;s.y=target.y;s.duration=Math.max(.4,distance({x,y},target)/12);s.remaining=s.duration;s.owner=e.id;s.damage*=.8;this.emit('reflect',x,y,target.x,target.y);if(e.shield===0)this.emit('shieldBreak',e.x,e.y);return true;
 }
 private move(){const obstacles=this.obstacles();for(const e of this.s.enemies){if(e.hp<=0)continue;const p=this.config.enemies[e.type];if(e.side==='left'){this.leftMove(e);continue;}if(e.type==='leviathan'&&this.s.campaign?.timelineVersion===3)continue;if(e.type==='suicide_ship'){this.suicideMove(e);continue;}if(e.type==='burrow_nest'){this.broodMove(e);continue;}if(e.state==='erupt'&&e.type!=='sandworm'){e.timer=Math.max(0,e.timer-DT);if(e.timer<=0)e.state='walk';continue;}if(e.type==='sandworm'){this.wormMove(e);continue;}if(e.descent){e.y=Math.max(p.height/2,e.y-2*DT);if(e.y<=p.height/2)e.descent=false;continue;}e.cooldown=Math.max(0,e.cooldown-DT);e.attackAnim=Math.max(0,(e.attackAnim||0)-DT);e.slows=e.slows.filter(a=>a.until>this.time);const slow=Math.max(0,...e.slows.map(a=>a.amount))*(p.boss?.5:1),speed=p.speed*e.speedScale*(1-slow);if(p.air){const tx=e.type==='fortress'?Math.max(6,Math.min(22,Math.max(5,...this.s.buildings.filter(b=>b.hp>0&&b.settled).map(b=>b.x))+1)):e.type==='carrier'?18:e.type==='tempest'?22:2,ty=e.type==='flyer'?3:e.y;const d=Math.hypot(tx-e.x,ty-e.y);if(d>.01){const f=Math.min(1,speed*DT/d);e.x+=(tx-e.x)*f;e.y+=(ty-e.y)*f;}continue;}
 const obstacle=obstacles.find(b=>b.x+b.w/2<=e.x-p.width/2+.001);e.target=obstacle?.id??-1;
 if(e.state==='charge'){e.timer-=DT;if(e.timer<=0){e.state='dash';e.distance=0;}continue;}if(e.state==='fuse')continue;
 if(e.type==='spitter'&&obstacle&&distance(e,obstacle)<=this.config.schedule.spitterRange)continue;
 if(e.type==='leaper'){e.skill-=DT;if(e.state==='walk'&&e.skill<=0){e.state='leap';e.timer=.65;e.skill=this.config.schedule.leapCooldown;this.emit('dust',e.x,e.y);}if(e.state==='leap'){e.timer-=DT;if(e.timer<=0){e.state='recover';e.timer=.4;this.emit('dust',e.x,e.y);}}else if(e.state==='recover'){e.timer-=DT;if(e.timer<=0)e.state='walk';continue;}}
 // Formation adjusts forward speed only: never halt or retreat to a moving slot.
 const escort=e.state==='walk'?this.escortAnchor(e):undefined;
 let dx=(e.state==='dash'?4:e.state==='leap'?this.config.schedule.leapSpeed*(1-slow):speed)*DT;
 if(escort){const gap=e.x-(escort.x+.8);if(gap>1.2)dx+=Math.min(speed*.6*DT,(gap-1.2)*DT);}
 const bound=obstacle?obstacle.x+obstacle.w/2+p.width/2:p.width/2;e.x=Math.max(bound,e.x-dx);if(e.state==='dash'){e.distance+=dx;if(e.x<=bound+1e-6||e.distance>=8){if(obstacle&&e.x<=bound+1e-6)this.explosion(obstacle.x,obstacle.y,this.config.schedule.beastChargeRadius,(this.config.schedule.beastChargeDamage??300)*e.attackScale);this.emit('explosion',e.x,e.y);e.state='walk';e.skill=12;}}}}
 private clearRay(b:Building,e:Enemy){let nearest=Infinity,hit=-1;for(const f of this.s.buildings.filter(f=>f.hp>0&&f.id!==b.id&&this.blocksFriendly(f.type,b.type==='sniper'?'bullet':b.type)).map(f=>({...f,w:1,h:1})))nearest=Math.min(nearest,rayBox(b.x,b.y,e.x,e.y,f.x,f.y,f.w,f.h));for(const a of this.index.query(b.x,b.y,this.stats(b).range+2)){if(!this.targetable(a))continue;const p=this.config.enemies[a.type],t=rayBox(b.x,b.y,e.x,e.y,a.x,a.y,p.width,p.height);if(t<nearest){nearest=t;hit=a.id;}}return hit===e.id;}
 private buildings(){for(const b of this.s.buildings){if(!this.s.alive)break;if(!b.settled||b.hp<=0)continue;const p=this.stats(b);b.cooldown=Math.max(0,b.cooldown-DT);if(b.cooldown>1e-8)continue;
 if(b.type==='crane')continue;if(b.type==='interceptor'){this.intercept(b);continue;}if(b.type==='mine'){const n=this.mineIncome(b);this.s.gold+=n;b.cooldown=p.interval;this.emit('gold',b.x,b.y,b.x,b.y,'+'+n);continue;}
 if(b.type==='repair'){const targets=[{id:0,x:2,y:1,hp:this.s.coreHp,max:this.config.world.coreHp},...this.s.buildings.filter(f=>f.hp>0&&f.id!==b.id).map(f=>({...f,max:this.stats(f).hp}))].filter(f=>f.hp<f.max&&distance(b,f)<=p.range).sort((a,c)=>a.hp/a.max-c.hp/c.max||a.id-c.id);const f=targets[0];if(f){const hp=Math.min(f.max,f.hp+p.damage*(1+this.perk('repair_efficiency')));if(f.id===0)this.s.coreHp=hp;else this.s.buildings.find(a=>a.id===f.id)!.hp=hp;b.cooldown=p.interval;this.emit('repair',b.x,b.y,f.x,f.y);}continue;}
 if(!p.damage)continue;const targets=this.index.query(b.x,b.y,p.range).filter(e=>this.targetable(e)&&(b.type!=='frost'||!this.wallBetween(b,e))&&this.isAir(e)===(b.type==='anti_air')&&distance(b,e)<=p.range&&distance(b,e)>=p.minRange).sort((a,c)=>Math.hypot(a.x-2,a.y-1)-Math.hypot(c.x-2,c.y-1)||a.id-c.id);if(b.type==='anti_air')targets.sort((a,c)=>Number(c.type==='fortress'&&!!this.commanderFor(c))-Number(a.type==='fortress'&&!!this.commanderFor(a)));if(this.partTarget!=='auto')targets.sort((a,c)=>Number(c.type==='carrier')-Number(a.type==='carrier'));const manual=this.controlled===b.id||this.controlledIds.includes(b.id);if(manual&&!this.aim.fire)continue;const chosen=manual?targets.filter(e=>distance(e,this.aim)<=Math.max(.8,this.config.enemies[e.type].width/2)).sort((a,c)=>distance(a,this.aim)-distance(c,this.aim)):targets;const e=['ballista','cannon','sniper'].includes(b.type)?chosen.find(e=>this.clearRay(b,e)):chosen[0];if(!e)continue;
 const boost=Math.max(0,...this.s.buildings.filter(f=>f.hp>0&&f.settled&&f.type==='amplifier'&&distance(f,b)<=this.stats(f).range).map(f=>this.stats(f).boost));const damage=p.damage*(1+this.perk('attack'))*(1+boost);b.cooldown=p.interval;
 if(b.type==='cannon'||b.type==='ballista'||b.type==='sniper'){const d=distance(b,e),dx=(e.x-b.x)/d,dy=(e.y-b.y)/d;const duration=Math.max(.08,(d-.48)/(b.type==='sniper'?this.config.schedule.bulletSpeed:b.type==='cannon'?this.config.schedule.cannonSpeed:this.config.schedule.arrowSpeed));this.s.shots.push({id:this.s.nextEntityId++,owner:b.id,kind:b.type==='sniper'?'bullet':b.type==='ballista'?'arrow':'cannon',phase:'flight',originX:b.x+dx*.48,originY:b.y+dy*.48,x:e.x,y:e.y,remaining:duration,duration,damage,radius:p.radius});this.emit(b.type,b.x,b.y,e.x,e.y);}else if(b.type==='mortar'){this.s.shots.push({id:this.s.nextEntityId++,owner:b.id,kind:'mortar',...mortarLaunch(b.x,b.y,e.x,e.y),x:e.x,y:e.y,remaining:.8,duration:.8,damage,radius:p.radius});this.emit('mortar',b.x,b.y,e.x,e.y);}else if(b.type==='frost'){for(const a of targets){this.hurtEnemy(a,damage,'cold');a.slows.push({amount:p.slow,until:this.time+p.slowDuration});}this.emit('frost',b.x,b.y,b.x+p.range,b.y);}else{this.hurtEnemy(e,damage);this.emit(b.type,b.x,b.y,e.x,e.y);}}
 }
 get economyMultiplier(){return this.s.campaign?.storm?3:1;}
 // Earlier surviving mines reserve their production tier, including while falling.
 mineOutput(b:Building){const c=this.config.schedule,p=this.stats(b),earlier=this.s.buildings.filter(a=>a.type==='mine'&&a.hp>0&&a.id<b.id),stack=earlier.filter(a=>Math.floor(a.x)===Math.floor(b.x)).length;
 const base=p.production,unboosted=base*(1+this.perk('mining')),raw=unboosted*this.economyMultiplier,efficiency=1/(1+(c.mineSaturation??0)*Math.max(0,earlier.length+1-(c.mineSoftCap??6)))/(1+(c.mineStackPenalty??0)*stack),actual=Math.max(1,Math.floor(unboosted*efficiency))*this.economyMultiplier;
 return {base,raw,actual,loss:Math.max(0,raw-actual),interval:p.interval,rate:actual/p.interval*60,rank:earlier.length+1,stack:stack+1};}
 mineIncome(b:Building){return this.mineOutput(b).actual;}
 economy(){const mines=this.s.buildings.filter(b=>b.type==='mine'&&b.hp>0&&b.settled),outputs=mines.map(b=>this.mineOutput(b)),raw=outputs.reduce((n,p)=>n+p.raw/p.interval*60,0),actual=outputs.reduce((n,p)=>n+p.rate,0),passive=(this.config.schedule.passiveGold+this.perk('subsidy'))*this.economyMultiplier/this.config.schedule.passiveEvery*60;return {count:mines.length,raw,actual,loss:raw-actual,passive,total:actual+passive,multiplier:this.economyMultiplier};}
 minePreview(column:number){const p=this.config.buildings.mine;return this.mineOutput({id:this.s.nextEntityId,type:'mine',branch:-1,spent:p.cost,x:column+.5,y:0,v:0,hp:p.hp,settled:false,fallId:1,hit:[],cooldown:p.interval});}

 private bomb(e:Enemy,col:number,delay:number,damage:number){this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',phase:'warning',originX:e.x,originY:e.y-.4,x:col+.5,y:0,remaining:delay,duration:delay,damage,radius:e.type==='carrier'?this.config.schedule.carrierBombRadius:.8});}
 relocationError(id:number,column:number,layer=this.top(column)){
  const b=this.s.buildings.find(a=>a.id===id&&a.hp>0&&a.settled);if(!b||b.type==='crane')return '请选择落稳的其他建筑';
  if(!Number.isInteger(column)||column<this.minColumn||column>=24||!Number.isInteger(layer)||layer<0||layer>=12)return '超出建造区域';
  if(b.x===column+.5&&b.y===layer+.5)return '请选择其他空格';
  if((column===1||column===2)&&layer<2||this.s.buildings.some(a=>a.id!==id&&a.hp>0&&Math.abs(a.x-(column+.5))<1&&Math.abs(a.y-(layer+.5))<1))return '目标格已被占用';
  if(this.s.buildings.some(a=>a.hp>0&&!a.settled&&Math.floor(a.x)===column))return '目标列正在下落，请稍后移位';
  const candidate={...b,x:column+.5,y:layer+.5};if(!supportedBuildings([...this.s.buildings.filter(a=>a.id!==id),candidate]).has(id))return '目标格需要地面或稳定建筑支撑';
  if(this.s.gold<(this.config.schedule.craneCost??35))return '吊装需要 35 金币';if(this.s.dropCooldown>1e-7)return '吊装冷却中';
  if(!this.craneFor(b,column,layer))return '起点和落点须在已就绪吊装站范围内';return '';
 }
 craneFor(b:Building,column=Math.floor(b.x),layer=b.y-.5){return this.s.buildings.filter(a=>a.type==='crane'&&a.hp>0&&a.settled&&a.cooldown<=1e-7&&distance(a,b)<=this.stats(a).range&&distance(a,{x:column+.5,y:layer+.5})<=this.stats(a).range).sort((a,c)=>distance(a,b)-distance(c,b)||a.id-c.id)[0];}
 private relocate(id:number,column:number,layer=this.top(column)){const error=this.relocationError(id,column,layer);if(error){this.notify(error);return;}const b=this.s.buildings.find(a=>a.id===id)!,crane=this.craneFor(b,column,layer)!;this.s.gold-=this.config.schedule.craneCost??35;crane.cooldown=this.stats(crane).interval;this.emit('lift',b.x,b.y,column+.5,layer+.5);b.x=column+.5;b.y=layer+.5;b.v=0;b.settled=true;b.hit=[];this.s.dropCooldown=this.config.world.deployCooldown;this.controlled=0;this.demolition=null;}
 private intercept(b:Building){const p=this.stats(b);const shot=this.s.shots.filter(a=>['bomb','rock'].includes(a.kind)&&a.phase==='flight'&&a.radius<=2.1).map(a=>({shot:a,point:enemyProjectilePosition(a,1-a.remaining/a.duration)})).filter(a=>distance(b,a.point)<=p.range).sort((a,c)=>a.shot.remaining-c.shot.remaining||a.shot.id-c.shot.id)[0];if(!shot)return;this.s.shots=this.s.shots.filter(a=>a.id!==shot.shot.id);b.cooldown=p.interval;this.emit('intercept',b.x,b.y,shot.point.x,shot.point.y);this.emit('mechBurst',shot.point.x,shot.point.y);}
 private mechanicalDeath(e:Enemy){if(!['carrier','suicide_ship','fortress'].includes(e.type))return;this.emit('mechBurst',e.x,e.y);if((e.type==='carrier'&&this.config.schedule.carrierCrashDamage)||e.type==='fortress'){this.s.shots.push({id:this.s.nextEntityId++,owner:2147483646,kind:'wreck',visual:e.type==='fortress'?'fortress':undefined,phase:'warning',originX:e.x,originY:e.y,x:e.x,y:0,remaining:this.config.schedule.carrierCrashWarning??3,duration:this.config.schedule.carrierCrashWarning??3,damage:(e.type==='fortress'?this.config.schedule.fortressCrashDamage:this.config.schedule.carrierCrashDamage)*e.attackScale,radius:(e.type==='fortress'?this.config.schedule.fortressCrashRadius:this.config.schedule.carrierCrashRadius)??4});this.announce(e.type==='fortress'?'空中堡垒失控 / 坠爆预警':'母舰失控 / 残骸即将坠落',e.type==='fortress'?'爆炸将波及建筑与地面虫群 · 利用落点反击':'下方大范围高伤爆炸 · 立即吊装撤离或回收建筑');}}
 commanderFor(e:Enemy){if(!this.config.schedule.commandRange)return undefined;return this.s.enemies.filter(a=>a.type==='marshal'&&a.hp>0&&distance(a,e)<=this.config.schedule.commandRange).sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id)[0];}
 escortAnchor(e:Enemy,coverOnly=false){if(this.isAir(e)||this.config.enemies[e.type].boss||e.type==='reflector'||e.hp<=0)return undefined;const commander=this.commanderFor(e);if(!coverOnly&&!commander)return undefined;return this.s.enemies.filter(a=>a.type==='reflector'&&!a.descent&&a.hp>0&&a.shield>0&&(coverOnly||!!commander&&distance(a,commander)<=this.config.schedule.commandRange)&&distance(a,e)<=(coverOnly?this.config.schedule.shieldCoverRadius:this.config.schedule.commandRange)).sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id)[0];}
 private coordinate(){if(!this.config.schedule.commandRange)return;const ships=this.s.enemies.filter(a=>a.hp>0&&a.type==='suicide_ship');const launch=(group:Enemy[],broken=false)=>{if(!group.length)return;const target=this.suicideTarget(group[0]);for(const ship of group){ship.state='charge';ship.target=target.id;ship.timer=this.config.enemies.suicide_ship.interval;ship.squad=undefined;}this.announce(broken?'指挥中断 / 飞船提前出击':'集群突击 / 自爆飞船齐袭',`${group.length} 艘飞船锁定同一目标 · 手动防空可绕过堡垒掩护`);};
  for(const ship of ships.filter(a=>a.state==='rally'))if(!this.s.enemies.some(a=>a.id===ship.squad&&a.type==='marshal'&&a.hp>0&&distance(a,ship)<=this.config.schedule.commandRange))launch([ship],true);
  for(const commander of this.s.enemies.filter(a=>a.type==='marshal'&&a.hp>0)){const group=ships.filter(a=>a.state==='rally'?a.squad===commander.id:a.state==='walk'&&a.x<=31&&this.commanderFor(a)?.id===commander.id);if(!group.length)continue;for(const ship of group){if(ship.state!=='rally'){ship.state='rally';ship.timer=this.config.schedule.squadWait??10;ship.squad=commander.id;}ship.timer-=DT;}if(group.length>=(this.config.schedule.squadSize??3)||group.some(a=>a.timer<=0))launch(group);}
 }
 private fortressDrop(e:Enemy){if(e.x>27)return;e.summon-=DT;if(e.summon>0)return;let spawned=0;for(const [i,type] of ['grunt','spitter','reflector','grunt'].entries()){const before=this.s.enemies.length;this.spawn(type,false,Math.min(38,e.x+(i-1.5)*.35),Math.max(1,e.y-.8-i*.18));if(this.s.enemies.length>before){this.s.enemies[this.s.enemies.length-1].descent=true;spawned++;}}e.summon=spawned?this.config.schedule.fortressDropEvery:3;if(spawned){this.emit('summon',e.x,e.y-.5);this.announce('空中堡垒 / 舱门开启',`空投 ${spawned} 只地面虫 · 防空拦截降落部队`);}}
 private suicideTarget(e:Enemy){const buildings=this.s.buildings.filter(b=>b.hp>0&&b.settled),valuable=buildings.filter(b=>!['wall','bridge'].includes(b.type));return (valuable.length?valuable:buildings).sort((a,b)=>b.spent-a.spent||distance(a,e)-distance(b,e)||a.id-b.id)[0]??{id:0,x:2,y:1};}
 private suicideMove(e:Enemy){if(e.state==='rally'){const fortress=this.s.enemies.filter(a=>a.type==='fortress'&&a.hp>0&&distance(a,e)<14).sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id)[0];const x=fortress?Math.min(34,fortress.x+2+(e.id%3)*.5):30+(e.id%3)*.5,y=fortress?Math.min(12,fortress.y+1+(e.id%3)*.5):8+(e.id%3)*.5;const d=distance(e,{x,y}),t=Math.min(1,2*DT/Math.max(.001,d));e.x+=(x-e.x)*t;e.y+=(y-e.y)*t;return;}const p=this.config.enemies[e.type];e.attackAnim=Math.max(0,(e.attackAnim??0)-DT);if(e.state==='walk'){e.x-=p.speed*e.speedScale*DT;if(e.x<=30){const target=this.suicideTarget(e);e.target=target.id;e.state='charge';e.timer=p.interval;this.announce('自爆飞船 / 冲撞锁定','锁定线已显示 · 防空击落可阻止撞击爆炸');}return;}if(e.target!==0&&!this.s.buildings.some(b=>b.id===e.target&&b.hp>0)){e.target=this.suicideTarget(e).id;e.state='charge';e.timer=p.interval;this.announce('自爆飞船 / 重新锁定','原目标已失效 · 重新标记高价值设施');return;}if(e.state==='charge'){e.timer-=DT;if(e.timer>0)return;e.state='dash';}const target=this.s.buildings.find(b=>b.id===e.target&&b.hp>0)??{x:2,y:1};const d=distance(e,target),travel=Math.min(d,p.speed*1.6*e.speedScale*DT),tx=e.x+(target.x-e.x)*travel/Math.max(.001,d),ty=e.y+(target.y-e.y)*travel/Math.max(.001,d);let first=Infinity;for(const b of [{x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0).map(b=>({...b,w:1,h:1}))])first=Math.min(first,rayBox(e.x,e.y,tx,ty,b.x,b.y,b.w+.5,b.h+.4));if(first<=1||d<.2){e.x+= (tx-e.x)*Math.min(1,first);e.y+=(ty-e.y)*Math.min(1,first);this.explosion(e.x,e.y,this.config.schedule.suicideRadius??1.65,p.damage*e.attackScale);this.emit('mechBurst',e.x,e.y);e.hp=0;}else{e.x=tx;e.y=ty;}}
 private salvage(){const box=this.s.crate;if(!box)return;const c=this.config.schedule;if(box.falling){box.y=Math.max(this.top(Math.floor(box.x))+.6,box.y-2.5*DT);if(box.y<=this.top(Math.floor(box.x))+.61)box.falling=false;return;}box.y=Math.min(box.y,Math.max(.6,this.top(Math.floor(box.x))+.6));box.remaining-=DT;const threats=this.s.enemies.filter(a=>a.hp>0&&this.targetable(a)&&distance(a,box)<3);if(threats.length){box.hp-=threats.reduce((sum,a)=>sum+8*a.attackScale,0)*DT;if(this.s.tick%30===0)this.emit('hit',box.x,box.y);}else if(this.s.buildings.some(b=>b.hp>0&&b.settled&&distance(b,box)<=4))box.progress+=DT;if(box.hp<=0||box.remaining<=0){this.emit('explosion',box.x,box.y);this.announce('军械箱回收失败','箱体损毁或回收时间耗尽');this.s.crate=null;}else if(box.progress>=(c.crateCollect??20)){this.s.gold+=c.crateReward??150;this.s.perkQueue++;this.emit('upgrade',box.x,box.y);this.announce('军械回收成功','获得 150 金币与一次三选一强化');this.s.crate=null;}}
 private broodExit(x:number){const positions=Array.from({length:69},(_,i)=>3.5+i*.5).sort((a,b)=>Math.abs(a-x)-Math.abs(b-x)||a-b);return positions.find(px=>!this.s.buildings.some(b=>b.hp>0&&b.y<1.5&&Math.abs(b.x-px)<1))??Math.min(35,x+2);}
 private broodMove(e:Enemy){if(e.state==='burrow'){e.timer-=DT;if(e.timer>0)return;e.state='exposed';e.y=this.config.enemies[e.type].height/2;for(const building of this.s.buildings)if(building.hp>0&&Math.abs(building.x-e.x)<(this.config.enemies[e.type].width+1)/2&&Math.abs(building.y-e.y)<(this.config.enemies[e.type].height+1)/2)this.hurtFriend(building.id,building.hp);e.summon=0;e.skill=1;this.explosion(e.x,.5,1.5,this.config.enemies[e.type].damage*e.attackScale);this.emit('rift',e.x,.1);this.announce('地渊孵化兽 / 巢穴展开','首批 4 只虫群涌出 · 每 12 秒孵化 2 只，优先击杀本体');}e.summon-=DT;if(e.summon>0)return;let count=0;const batch=e.skill===1?['grunt','leaper','grunt','spitter']:['grunt','spitter'];for(const type of batch){const before=this.s.enemies.length;this.spawn(type,false,this.broodExit(e.x+(count%3-1)*.8));if(this.s.enemies.length>before){const child=this.s.enemies[this.s.enemies.length-1];child.state='erupt';child.timer=.8;count++;}}if(count){e.skill=0;this.emit('summon',e.x,e.y);e.summon=this.config.enemies[e.type].interval;}else e.summon=1;}
 private wormMove(e:Enemy){
  const c=this.config.schedule,p=this.config.enemies[e.type];e.cooldown=Math.max(0,e.cooldown-DT);
  if(e.state==='walk'||e.state==='exposed'&&e.timer<=0){const targets=this.s.buildings.filter(b=>b.hp>0&&b.x>=0).sort((a,b)=>b.spent-a.spent||a.id-b.id);e.x=Math.max(5,Math.min(22,targets[0]?.x??10.5));e.y=0;e.state='burrow';e.timer=c.wormWarning;this.announce('裂地沙虫 / 地下巨震','红色通道内建筑将被逐层摧毁 · 出土后集火');}
  if(e.state==='burrow'){e.timer-=DT;if(e.timer<=0){e.state='erupt';e.timer=0;this.emit('rift',e.x,0);}return;}
  if(e.state==='erupt'){const before=e.y;e.y=Math.min(13,e.y+c.wormRiseSpeed*DT);for(const b of this.s.buildings){if(b.hp>0&&Math.abs(b.x-e.x)<p.width/2+.5&&b.y+.5>=before-p.height/2&&b.y-.5<=e.y+p.height/2){b.hp=0;this.emit('explosion',b.x,b.y);}}if(e.y>=13){e.y=p.height/2;e.state='exposed';e.timer=c.wormExpose;this.announce('沙虫出土 / 集火窗口','躯体已暴露 · 下一次钻地前尽快击杀');}return;}
  e.timer-=DT;
 }
 queenNestX(e:Enemy){return Math.max(4,Math.min(28,e.x-2));}
 private newBoss(e:Enemy){
  const c=this.config.schedule,p=this.config.enemies[e.type];if(e.type==='leviathan'){this.tidalBoss(e);return true;}if(!['sandworm','queen','tempest'].includes(e.type))return false;
  const targets=[{id:0,x:2,y:1},...this.s.buildings.filter(b=>b.hp>0&&b.settled)].sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id);
  if(e.type==='sandworm'){if(e.state==='exposed'&&e.cooldown<=0){const target=targets.find(b=>distance(b,e)<5);if(target){this.explosion(target.x,target.y,1.5,p.damage*e.attackScale);e.cooldown=p.interval;}}return true;}
  if(e.type==='tempest'&&e.x>30&&c.bossOpeningDelay===undefined)return true;e.special=(e.special??5)-DT;e.secondary=(e.secondary??8)-DT;
  if(e.type==='queen'&&e.special<=3&&e.special+DT>3)this.announce('虫巢女王 / 虫卵即将破裂','共生虫巢已标记 · 幼虫将从巢口涌出，集火女王停止孵化');
  if(e.special<=0){if(e.type==='queen'){const x=this.queenNestX(e);for(const [i,type] of ['leaper','blastbeetle','leaper','grunt'].entries())this.spawn(type,false,x+(i-1.5)*.3);this.emit('summon',x,.5);this.emit('hatch',x,.5);e.special=c.queenBroodEvery;}
   else{for(const target of targets.slice(0,3))this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'laser',phase:'warning',visual:'lightning',originX:e.x,originY:e.y,x:target.x,y:0,remaining:2.8,duration:2.8,damage:p.damage*e.attackScale,radius:1.2});this.announce('雷暴巨兽 / 连锁落雷','三处落雷区域已标记 · 保留维修与重建资金');e.special=c.tempestLightningEvery;}}
  if(e.secondary<=0){for(const [i,target] of targets.slice(0,3).entries())this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',phase:'warning',visual:e.type==='queen'?'acid':'plasma',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:1.6+i*.2,duration:1.6+i*.2,damage:(e.type==='queen'?40:60)*e.attackScale,radius:1.2});e.secondary=e.type==='queen'?c.queenAcidEvery:c.tempestOrbEvery;}return true;
 }
 private tidalBoss(e:Enemy){const rage=e.hp<=e.maxHp*.5,p=this.config.enemies[e.type];if(rage&&e.skill!==-1){e.skill=-1;this.emit('tidalRise',e.x,0);this.announce('深渊潮汐领主 / 狂潮阶段','甲壳核心暴露 · 潮汐与深水雷施放加快');}
 e.special=(e.special??4)-DT;e.secondary=(e.secondary??7)-DT;e.cooldown-=DT;e.summon-=DT;e.attackAnim=Math.max(0,(e.attackAnim??0)-DT);
 const targets=[...this.s.buildings.filter(b=>b.hp>0&&b.settled).sort((a,b)=>b.spent-a.spent||a.id-b.id),{x:2,y:1}];
 if(e.summon<=0){for(let i=0;i<(rage?6:4);i++){const x=4+random(this.s)*19;this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'shockwave',visual:'tidalDrop',phase:'warning',originX:e.x,originY:15.5,x,y:.5,remaining:2.5+i*.2,duration:2.5+i*.2,damage:0,radius:.65});}e.summon=rage?9:13;this.emit('summon',e.x,14);}
 if(e.cooldown<=0){const target=targets[Math.floor(random(this.s)*Math.min(3,targets.length))];for(let i=-1;i<=1;i++)this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'shockwave',visual:'tidalClaw',phase:'warning',originX:e.x,originY:e.y,x:Math.max(.5,Math.min(23.5,target.x+i*1.6)),y:target.y,remaining:2.4+(i+1)*.18,duration:2.4+(i+1)*.18,damage:p.damage*e.attackScale*.6,radius:1.15});e.cooldown=rage?8:12;e.attackAnim=3;this.emit('enemyShot',e.x,e.y);}
 if(e.special<=0){e.attackAnim=3.5;for(let i=0;i<3;i++){const target=targets[i%targets.length];this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'shockwave',visual:'tidal',phase:'warning',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:3.5+i*.65,duration:3.5+i*.65,damage:p.damage*e.attackScale*.75,radius:2.6});}e.special=rage?10:15;this.announce('潮汐冲击 / 三重浪涌','蓝色波纹落点即将爆发 · 吊装撤离、修复邻近设施');}
 if(e.secondary<=0){for(let i=0;i<3;i++){const target=targets[(i+1)%targets.length];this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',visual:'depthcharge',phase:'warning',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:2+i*.45,duration:2+i*.45,damage:p.damage*e.attackScale,radius:1.6});}e.secondary=rage?13:19;this.emit('enemyShot',e.x,e.y);}
 }
 private bossExtras(e:Enemy){if(this.newBoss(e))return;
 const c=this.config.schedule,beast=e.type==='beast';
 if(!beast&&e.x>c.carrierEngageX&&c.bossOpeningDelay===undefined)return;
 e.special=(e.special??(beast?c.beastStompCooldown:c.carrierLaserCooldown))-DT;
 e.secondary=(e.secondary??(beast?c.beastRockCooldown:c.carrierMissileCooldown))-DT;
 const friends=[{id:0,x:2,y:1},...this.s.buildings.filter(b=>b.hp>0&&b.settled)].filter(b=>!beast||b.x<e.x&&(c.bossOpeningDelay!==undefined||distance(b,e)<=10)).sort((a,b)=>distance(a,e)-distance(b,e)||a.id-b.id);
 const target=friends[0];if(!target)return;
 if(e.special<=0&&(!beast||distance(target,e)<=4)&&e.state==='walk'){
  const kind=beast?'shockwave':'laser',delay=beast?1.4:2;
  this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind,phase:'warning',originX:e.x,originY:e.y,x:beast?e.x:Math.floor(target.x)+.5,y:beast?.3:0,remaining:delay,duration:delay,damage:(beast?c.beastStompDamage:c.carrierLaserDamage)*e.attackScale,radius:beast?c.beastStompRadius:.7});
  e.special=beast?c.beastStompCooldown:c.carrierLaserCooldown;
 }
 if(e.secondary<=0&&e.state==='walk'&&(beast||!e.parts||e.parts.missiles>0)){
  if(beast){this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'rock',phase:'warning',originX:e.x,originY:e.y+.4,x:target.x,y:target.y,remaining:1.1,duration:1.1,damage:c.beastRockDamage*e.attackScale,radius:1.1});e.secondary=c.beastRockCooldown;}
  else{for(let i=0;i<4;i++){const t=friends[i%friends.length];this.bomb(e,Math.floor(t.x),1.2+i*.25,c.carrierMissileDamage*e.attackScale);this.s.shots[this.s.shots.length-1].visual='missile';}e.secondary=c.carrierMissileCooldown;}
 }
 }
 private enemies(){for(const e of this.s.enemies){if(e.hp<=0||!this.s.alive)continue;const p=this.config.enemies[e.type];if(e.descent)continue;if(e.side==='left'){this.leftAttack(e);continue;}if(p.boss)this.bossExtras(e);if(e.type==='leviathan'||e.type==='sandworm'||e.type==='tempest'||e.type==='suicide_ship'||e.type==='burrow_nest'||e.state==='erupt')continue;if(e.type==='fortress'){this.fortressDrop(e);continue;}if(e.type==='spitter'){const target=[{id:0,x:2,y:1},...this.s.buildings.filter(b=>b.hp>0&&b.settled)].filter(b=>distance(e,b)<=this.config.schedule.spitterRange).sort((a,b)=>distance(e,a)-distance(e,b)||a.id-b.id)[0];if(target&&e.cooldown<=0){const duration=Math.max(.35,distance(e,target)/8);this.s.shots.push({id:this.s.nextEntityId++,owner:e.id,kind:'bomb',visual:'acid',phase:'flight',originX:e.x,originY:e.y,x:target.x,y:target.y,remaining:duration,duration,damage:p.damage*e.attackScale,radius:.35});e.cooldown=p.interval;e.attackAnim=.3;this.emit('enemyShot',e.x,e.y);}continue;}if(e.type==='carrier'){if(e.x>this.config.schedule.carrierEngageX&&this.config.schedule.bossOpeningDelay===undefined)continue;e.skill-=DT;e.summon-=DT;if(e.skill<=0){let best=0,count=-1;for(let col=0;col<=21;col++){const n=this.s.buildings.filter(b=>b.hp>0&&b.x>=col&&b.x<col+3).length;if(n>count){count=n;best=col;}}for(let c=best;c<best+3;c++)this.bomb(e,c,2,p.damage*e.attackScale);e.skill=this.config.schedule.carrierBombEvery;this.announce('母舰 / 地毯轰炸','连续三列遭到锁定 · 注意上层防御');}if(e.summon<=0){for(let i=0;i<(e.parts?.hangar===0?1:3);i++)this.spawn('flyer',false,e.x+i*.6,e.y);const before=this.s.enemies.length;if(e.parts?.hangar!==0)this.spawn('spitter',false,Math.min(23,e.x-3),e.y-1);if(this.s.enemies.length>before)this.s.enemies[this.s.enemies.length-1].descent=true;this.emit('summon',e.x,e.y);e.summon=this.config.schedule.carrierSummonEvery*(e.parts?.hangar===0?2:1);}continue;}
 if(e.type==='bombardier'){if(e.x<24&&e.cooldown<=0){const b=this.s.buildings.filter(b=>b.hp>0&&b.settled&&Math.abs(b.x-e.x)<=6).sort((a,b)=>b.spent-a.spent||a.id-b.id)[0];if(b||e.x<=2.01){this.bomb(e,b?Math.floor(b.x):1,1.5,p.damage*e.attackScale);e.cooldown=p.interval;}}continue;}
 if(e.type==='flyer'){if(distance(e,{x:2,y:3})<.05&&e.cooldown<=0){this.hurtFriend(0,p.damage*e.attackScale);e.cooldown=p.interval;e.attackAnim=.3;this.emit('flyerAttack',e.x,e.y,2,1);}continue;}
 const o=this.obstacles().find(b=>b.id===e.target);if(e.type==='beast'&&e.state==='walk'){e.skill-=DT;if(e.skill<=0&&o&&e.x-p.width/2-o.x-o.w/2<=8){e.state='charge';e.timer=2;continue;}}
 if(e.state==='charge'||e.state==='dash')continue;
 if(e.state==='fuse'){e.timer-=DT;if(e.timer<=0){this.explosion(e.x,e.y,1.4,p.damage*e.attackScale);e.hp=0;}continue;}
 if(o&&e.x-p.width/2<=o.x+o.w/2+.001&&e.cooldown<=0){if(e.type==='bomber'){e.state='fuse';e.timer=1.2;}else{if(p.boss)this.explosion(o.x,o.y,this.config.schedule.beastMeleeRadius,p.damage*e.attackScale);else this.hurtFriend(o.id,p.damage*e.attackScale,e);e.cooldown=p.interval;e.attackAnim=.3;this.emit(e.type==='siege'?'siegeAttack':e.type==='beast'?'beastAttack':e.type==='runner'?'runnerAttack':'clawAttack',e.x,e.y,o.x,o.y);}}}}
 private projectiles(){for(const s of [...this.s.shots]){
 if(!this.s.alive)break;if(!this.s.shots.includes(s))continue;
 if(s.kind==='arrow'||s.kind==='cannon'||s.kind==='bullet'){
 const ox=s.originX??s.x,oy=s.originY??s.y,previous=1-s.remaining/s.duration;
 s.remaining=Math.max(0,s.remaining-DT);const t=1-s.remaining/s.duration;
 const x=ox+(s.x-ox)*previous,y=oy+(s.y-oy)*previous,tx=ox+(s.x-ox)*t,ty=oy+(s.y-oy)*t;
 let first=Infinity,victim:Enemy|undefined;
 for(const b of this.s.buildings.filter(b=>b.hp>0&&b.id!==s.owner&&this.blocksFriendly(b.type,s.kind)).map(b=>({...b,w:1,h:1})))first=Math.min(first,rayBox(x,y,tx,ty,b.x,b.y,b.w,b.h));
 for(const enemy of this.index.query((x+tx)/2,(y+ty)/2,Math.hypot(tx-x,ty-y)/2+2)){const p=this.config.enemies[enemy.type];if(!this.targetable(enemy)||this.isAir(enemy))continue;const hit=rayBox(x,y,tx,ty,enemy.x,enemy.y,p.width+.08,p.height+.08);if(hit<first){first=hit;victim=enemy;}}
 if(first<=1||s.remaining<=1e-7){const hx=first<=1?x+(tx-x)*first:tx,hy=first<=1?y+(ty-y)*first:ty;
 if(s.kind==='cannon'&&this.reflect(s,hx,hy))continue;
 if(s.kind==='cannon'){this.emit('explosion',hx,hy);for(const enemy of this.index.query(hx,hy,s.radius))if(!this.isAir(enemy)&&distance({x:hx,y:hy},enemy)<=s.radius)this.hurtEnemy(enemy,s.damage,'explosion');}
 else if(victim){this.hurtEnemy(victim,s.damage);this.emit('arrowHit',hx,hy);}else this.emit('dust',hx,hy);
 this.s.shots=this.s.shots.filter(a=>a.id!==s.id);}continue;
 }
 if(s.kind==='mortar'){
 const prev=shellPath(s,1-s.remaining/s.duration);s.remaining=Math.max(0,s.remaining-DT);const next=shellPath(s,1-s.remaining/s.duration);let first=Infinity;
 for(const b of this.s.buildings.filter(b=>b.hp>0&&b.id!==s.owner&&this.blocksFriendly(b.type,s.kind)))first=Math.min(first,rayBox(prev.x,prev.y,next.x,next.y,b.x,b.y,1.1,1.1));
 if(first<=1){s.x=prev.x+(next.x-prev.x)*first;s.y=prev.y+(next.y-prev.y)*first;s.remaining=0;}if(s.remaining>1e-7)continue;
 if(this.reflect(s,s.x,s.y))continue;this.emit('explosion',s.x,s.y);for(const a of this.index.query(s.x,s.y,s.radius))if(!this.isAir(a)&&distance(s,a)<=s.radius)this.hurtEnemy(a,s.damage,'explosion');this.s.shots=this.s.shots.filter(a=>a.id!==s.id);continue;
 }
 if(s.kind==='wreck'&&s.phase==='warning'){s.remaining-=DT;if(s.remaining<=0){s.phase='flight';s.duration=this.config.schedule.carrierCrashFlight??3;s.remaining=s.duration;}continue;}
 const physical=['bomb','rock','wreck'].includes(s.kind);
 if(physical&&s.phase==='flight'){
  const prev=enemyProjectilePosition(s,1-s.remaining/s.duration);s.remaining=Math.max(0,s.remaining-DT);const next=enemyProjectilePosition(s,1-s.remaining/s.duration);
  let first=Infinity;
  for(const b of [{x:2,y:1,w:2,h:2},...this.s.buildings.filter(b=>b.hp>0).map(b=>({...b,w:1,h:1}))]){first=Math.min(first,rayBox(prev.x,prev.y,next.x,next.y,b.x,b.y,b.w+.22,b.h+.22));}
  if(first<=1||s.remaining<=1e-7){const hit=first<=1?{x:prev.x+(next.x-prev.x)*first,y:prev.y+(next.y-prev.y)*first}:next;this.explosion(hit.x,hit.y,s.radius,s.damage);if(s.kind==='wreck'&&s.visual!=='fortress'&&this.s.campaign?.timelineVersion===3&&this.s.campaign.stage===4&&this.s.alive)this.s.campaign.carrierCrashed=true;if(s.visual==='depthcharge')this.emit('tidalBurst',hit.x,hit.y);if(s.kind==='wreck'){this.emit('wreckBlast',hit.x,hit.y,hit.x+s.radius,hit.y);if(s.visual==='fortress')for(const enemy of [...this.s.enemies])if(enemy.hp>0&&!this.isAir(enemy)&&distance(enemy,hit)<=s.radius)this.hurtEnemy(enemy,s.damage,'friendlyBlast');}this.s.shots=this.s.shots.filter(a=>a.id!==s.id);}continue;
 }
 s.remaining-=DT;if(s.remaining>1e-7)continue;
 if(physical){const owner=this.s.enemies.find(e=>e.id===s.owner&&e.hp>0);if(!owner){this.s.shots=this.s.shots.filter(a=>a.id!==s.id);continue;}
  s.phase='flight';s.originX=owner.x;s.originY=owner.y+(s.kind==='rock'?.4:-.35);s.duration=this.config.schedule.enemyBombFlight??.9;s.remaining=s.duration;owner.attackAnim=.3;if(owner.type==='carrier')owner.weakUntil=this.time+3;this.emit('bombRelease',s.originX,s.originY);continue;
 }
 if(s.visual==='tidalDrop'){const owner=this.s.enemies.find(a=>a.id===s.owner&&a.hp>0);if(owner){const pool=['grunt','runner','spitter'].filter(k=>this.chapter?.enemies.includes(k));const kind=pool[Math.floor(random(this.s)*pool.length)];if(kind){const before=this.s.enemies.length;this.spawn(kind,false,s.x,15.5,true);if(this.s.enemies.length>before){this.s.enemies[this.s.enemies.length-1].descent=true;this.emit('summon',s.x,15.5);}}}this.s.shots=this.s.shots.filter(a=>a.id!==s.id);continue;}
 if(s.kind==='shockwave'){if(s.visual==='tidalClaw')this.emit('tidalBurst',s.x,s.y);this.explosion(s.x,s.y,s.radius,s.damage);this.emit(s.visual==='tidal'?'tidalBurst':'shockwave',s.x,s.y,s.x+s.radius,s.y);}
 else{const col=Math.floor(s.x),top=Math.max(col===1||col===2?2:0,...this.s.buildings.filter(b=>b.hp>0&&Math.floor(b.x)===col).map(b=>b.y+.5));this.explosion(s.x,top,s.radius,s.damage);if(s.kind==='laser')this.emit('bossLaser',s.originX??s.x,s.originY??11,s.x,top);}
 this.s.shots=this.s.shots.filter(a=>a.id!==s.id);
 }}
 private offer(){if(!this.s.perkQueue||this.s.candidates.length||!this.s.alive)return;const pool=Object.keys(this.config.perks).filter(k=>(this.s.perks[k]||0)<this.config.perks[k].max);while(pool.length&&this.s.candidates.length<3)this.s.candidates.push(pool.splice(Math.floor(random(this.s)*pool.length),1)[0]);if(!this.s.candidates.length)this.s.candidates=['supply'];}
 choose(id:string){if(!this.s.alive||!this.s.candidates.includes(id))return;const ratios=this.s.buildings.map(b=>b.hp/this.stats(b).hp);if(id==='supply')this.s.gold+=100;else this.s.perks[id]=(this.s.perks[id]||0)+1;if(id==='durability')this.s.buildings.forEach((b,i)=>b.hp=this.stats(b).hp*ratios[i]);if(id==='core_repair')this.s.coreHp=Math.min(this.config.world.coreHp,this.s.coreHp+this.config.perks[id].value);this.s.candidates=[];this.s.perkQueue--;this.offer();}
 step(){if(this.cinematic){this.advanceReveal();return;}if(!this.running)return;const previousLevel=this.level;this.s.tick++;if(this.s.campaign?.storm&&this.s.tick%660===0)this.sounds.push('thunder');if(this.level!==previousLevel&&this.config.schedule.liveGrowth)this.growEnemies(previousLevel-1,this.level-1);if(this.time>=this.messageUntil)this.message='';this.effects=this.effects.map(e=>({...e,life:e.life-DT})).filter(e=>e.life>0);this.commands();this.s.dropCooldown=Math.max(0,this.s.dropCooldown-DT);this.leftFront();this.schedule();this.events();this.salvage();this.controlledIds=this.controlledIds.filter(id=>this.s.buildings.some(b=>b.id===id&&b.hp>0&&b.settled));if(!this.s.buildings.some(b=>b.id===this.controlled&&b.hp>0&&b.settled))this.controlled=this.controlledIds[0]??0;this.index.rebuild(this.s.enemies);this.structure();this.coordinate();this.move();if(!this.s.alive)return;this.index.rebuild(this.s.enemies);this.buildings();this.enemies();this.projectiles();this.s.buildings=this.s.buildings.filter(b=>b.hp>0);this.s.enemies=this.s.enemies.filter(e=>e.hp>0);if(this.startReveal())return;this.campaignVictory();if(!this.s.alive||this.s.campaign?.won)return;
 if(this.demolition){const b=this.s.buildings.find(b=>b.id===this.demolition!.id&&b.settled);if(!b)this.demolition=null;else{this.demolition.elapsed+=DT;if(this.demolition.elapsed+1e-8>=.3){this.s.gold+=this.refund(b);this.s.buildings=this.s.buildings.filter(a=>a.id!==b.id);this.demolition=null;}}}
 this.s.passive+=DT;if(this.s.passive+1e-8>=this.config.schedule.passiveEvery){this.s.passive-=this.config.schedule.passiveEvery;this.s.gold+=(this.config.schedule.passiveGold+this.perk('subsidy'))*this.economyMultiplier;}this.s.maxThreat=Math.max(this.s.maxThreat,this.level);if(this.time>=this.s.nextPerk){this.s.perkQueue++;this.s.nextPerk+=this.config.schedule.perkEvery;}this.offer();}
 snapshot(){const s=structuredClone(this.s);s.commands=s.commands.filter(c=>c.type!=='demolish'&&c.type!=='cancelDemolish');return s;}
}
