export interface Stats {limit?:number;easyLimit?:number;name:string;icon:string;description:string;cost:number;hp:number;impact:number;damage:number;interval:number;range:number;minRange:number;radius:number;production:number;slow:number;slowDuration:number;boost:number;thorns:number;upgradeCost:number;branches:(Partial<Stats>&{name:string})[]}
export interface EnemyStats {name:string;hp:number;speed:number;damage:number;interval:number;reward:number;unlock:number;weight:number;air:boolean;width:number;height:number;armor:number;boss:boolean}
export interface Config {balanceRevision?:number;configVersion:number;world:Record<string,number>;buildings:Record<string,Stats>;enemies:Record<string,EnemyStats>;perks:Record<string,{name:string;description:string;max:number;value:number}>;schedule:Record<string,number>}
export interface Building {id:number;type:string;branch:number;spent:number;x:number;y:number;v:number;hp:number;settled:boolean;fallId:number;hit:number[];cooldown:number}
export interface Enemy {side?:"left";squad?:number;parts?:{hangar:number;missiles:number;max:number};weakUntil?:number;descent?:boolean;special?:number;secondary?:number;attackAnim?:number;id:number;type:string;x:number;y:number;hp:number;maxHp:number;shield:number;armor:number;attackScale:number;speedScale:number;reward:number;elite:string;cooldown:number;slows:{amount:number;until:number}[];skill:number;summon:number;state:string;timer:number;distance:number;target:number}
export interface Shot {phase?:'warning'|'flight';visual?:string;originX?:number;originY?:number;id:number;owner:number;kind:string;x:number;y:number;remaining:number;duration:number;damage:number;radius:number}
export type Command={type:'relocate';id:number;column:number;layer?:number}|{type:'upgradeMany';ids:number[];branch:number}|{type:'drop';kind:string;column:number;layer?:number}|{type:'upgrade';id:number;branch:number}|{type:'demolish';id:number}|{type:'cancelDemolish'};
export type Difficulty='easy'|'normal'|'hard';
export interface World {campaign?:{timelineVersion?:2|3|null;revealFrame?:number|null;carrierCrashed?:boolean;storm?:boolean;stage:number;spawned:number;won:boolean}|null;testMode?:boolean;leftOpened?:boolean;nextLeft?:number;squads?:number[][];crate?:{x:number;y:number;hp:number;remaining:number;progress:number;falling:boolean}|null;balanceRevision?:number;difficulty?:Difficulty;nextEvent?:number;eventCount?:number;eventDebt?:number;event?:{kind:'missiles'|'airdrop'|'meteor'|'breach'|'sabotage'|'siege'|'supply';remaining:number;columns:number[]}|null;schemaVersion:number;configVersion:number;runId:string;seed:number;rng:number;nextEntityId:number;revision:number;tick:number;gold:number;coreHp:number;maxThreat:number;kills:number;bossKills:number;alive:boolean;buildings:Building[];enemies:Enemy[];shots:Shot[];spawnCredit:number;bossRequests:number;bossWarning:number;bossCount:number;lastBossDeath:number;nextBoss:number;nextPerk:number;passive:number;perks:Record<string,number>;perkQueue:number;candidates:string[];dropCooldown:number;commands:Command[]}
export interface Effect {kind:string;x:number;y:number;tx:number;ty:number;life:number;text?:string}
