export interface Stats {name:string;icon:string;description:string;cost:number;hp:number;impact:number;damage:number;interval:number;range:number;minRange:number;radius:number;production:number;slow:number;slowDuration:number;boost:number;thorns:number;upgradeCost:number;branches:(Partial<Stats>&{name:string})[]}
export interface EnemyStats {name:string;hp:number;speed:number;damage:number;interval:number;reward:number;unlock:number;weight:number;air:boolean;width:number;height:number;armor:number;boss:boolean}
export interface Config {configVersion:number;world:Record<string,number>;buildings:Record<string,Stats>;enemies:Record<string,EnemyStats>;perks:Record<string,{name:string;description:string;max:number;value:number}>;schedule:Record<string,number>}
export interface Building {id:number;type:string;branch:number;spent:number;x:number;y:number;v:number;hp:number;settled:boolean;fallId:number;hit:number[];cooldown:number}
export interface Enemy {id:number;type:string;x:number;y:number;hp:number;maxHp:number;shield:number;armor:number;attackScale:number;speedScale:number;reward:number;elite:string;cooldown:number;slows:{amount:number;until:number}[];skill:number;summon:number;state:string;timer:number;distance:number;target:number}
export interface Shot {id:number;owner:number;kind:string;x:number;y:number;remaining:number;duration:number;damage:number;radius:number}
export type Command={type:'drop';kind:string;column:number}|{type:'upgrade';id:number;branch:number}|{type:'demolish';id:number}|{type:'cancelDemolish'};
export interface World {schemaVersion:number;configVersion:number;runId:string;seed:number;rng:number;nextEntityId:number;revision:number;tick:number;gold:number;coreHp:number;maxThreat:number;kills:number;bossKills:number;alive:boolean;buildings:Building[];enemies:Enemy[];shots:Shot[];spawnCredit:number;bossRequests:number;bossWarning:number;bossCount:number;lastBossDeath:number;nextBoss:number;nextPerk:number;passive:number;perks:Record<string,number>;perkQueue:number;candidates:string[];dropCooldown:number;commands:Command[]}
export interface Effect {kind:string;x:number;y:number;tx:number;ty:number;life:number;text?:string}
