<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {CAMPAIGNS,campaignIntel} from '../game/campaigns';import {paintBackground} from '../game/render/backgrounds';import config from '../../../content/game-config.json' with {type:'json'};
const props=defineProps<{cleared:number;busy:boolean;unlocked?:boolean}>();defineEmits<{start:[stage:number];close:[]}>();const selected=ref(Math.min(props.cleared,4)),root=ref<HTMLElement>();const chapter=computed(()=>campaignIntel(CAMPAIGNS[selected.value],!!props.unlocked));
onMounted(()=>root.value?.querySelectorAll('canvas').forEach((canvas,i)=>{const c=canvas.getContext('2d')!;c.scale(canvas.width/36,canvas.height/16);paintBackground(c,CAMPAIGNS[i].background);}));
</script>
<template><div ref="root" class="campaign-map"><div class="eyebrow">战墙 / 黎明计划</div><h2>五道防线，一次归航。</h2><p>从荒原的一点火光，到照亮海岸的整片黎明。守住核心，击败各地统领，逐关解锁新的武器与敌人。</p><nav aria-label="战役地图"><button v-for="(c,i) in CAMPAIGNS" :class="{active:selected===i,locked:i>cleared}" @click="selected=i"><canvas width="288" height="128" aria-hidden="true"></canvas><small>CHAPTER {{i+1}} · {{i<cleared?'已通关':i===cleared?'可出击':'未解锁'}}</small><b>{{c.map}}</b><span>{{c.title}}</span></button></nav><article><div class="eyebrow">第 {{selected+1}} 战役 · {{ {easy:'简单',normal:'普通',hard:'困难'}[chapter.difficulty] }} · {{chapter.gold}} G 起始资金</div><h3>{{chapter.title}}</h3><p>{{chapter.story}}</p><div class="campaign-intel"><div><b>本关新增设施</b><p>{{chapter.newBuildings.map(k=>config.buildings[k as keyof typeof config.buildings].name).join('、')}}</p></div><div><b>本关统领 · 分阶段登场</b><p v-for="(boss,i) in chapter.bosses"><template v-if="(chapter.bossTimes?.[i]??chapter.bossAt)>=999999999">母舰坠毁后 · </template><template v-else>{{Math.floor((chapter.bossTimes?.[i]??chapter.bossAt)/60)}}:{{String((chapter.bossTimes?.[i]??chapter.bossAt)%60).padStart(2,'0')}} · </template>{{config.enemies[boss as keyof typeof config.enemies].name}}</p></div></div><p class="mission-tip">作战提示：{{chapter.hint}}</p><small>每关独立建设，通关永久解锁下一关。战役使用固定地图与难度，可随时保存续玩。</small></article><footer><button @click="$emit('close')">返回</button><button class="primary" :disabled="selected>cleared||busy" @click="$emit('start',selected)">{{selected>cleared?'先完成上一关':selected<cleared?'重玩此战役':'出击 · '+chapter.title}}</button></footer></div></template>
<style scoped>
.campaign-map h2{margin-bottom:12px}.campaign-map nav{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.campaign-map nav button{padding:5px;text-align:left;min-width:0}.campaign-map canvas{width:100%;height:auto;display:block}.campaign-map nav small,.campaign-map nav span,.campaign-map nav b{display:block;margin:7px 4px;font-size:11px}.campaign-map nav b{font-size:14px}.campaign-map nav .active{border-color:#dfca8f;background:#36422b}.campaign-map nav .locked{opacity:.55}.campaign-map article{margin-top:20px;padding:18px;background:#111e19;border:1px solid #4d5b3b}.campaign-map h3{font-size:24px}.campaign-intel{display:grid;grid-template-columns:1fr 1fr;gap:18px}.campaign-intel b{font-size:12px;color:#d5dbaa}.mission-tip{color:#dbc99a!important}.campaign-map footer{display:flex;justify-content:flex-end;gap:12px;margin-top:16px}
</style>
