<script setup lang="ts">
import {ref,shallowRef,computed,onMounted,onUnmounted,nextTick} from 'vue';
import changelog from '../../../content/changelog.json';
import {invitationLinks} from '../game/lan-address';
import {CoopGame,type Player,type Options} from '../game/coop';
import {Engine} from '../game/engine';
import {Renderer} from '../game/render/canvas';
import CampaignVictory from './CampaignVictory.vue';
import {AudioSystem} from '../game/render/audio';
import {CAMPAIGNS,campaignIntel} from '../game/campaigns';
import type {Config} from '../game/types';
const props=defineProps<{config:Config}>(),emit=defineEmits(['close','achievement']);
const server=ref(location.protocol==='file:'?'http://192.168.1.100:8000':`${location.protocol}//${location.hostname}:8000`),name=ref('指挥官'),code=ref(new URLSearchParams(location.search).get('lan')||''),id=ref(''),host=ref(''),players=ref<Player[]>([]),connected=ref(false),error=ref(''),status=ref(''),options=ref<Options>({mode:'endless',difficulty:'easy',stage:0}),e=shallowRef<Engine>(),canvas=ref<HTMLCanvasElement>(),revision=ref(0),kind=ref(''),selection=ref<number[]>([]),relocate=ref(false),volume=ref(.65);
const lanAddresses=ref<string[]>([]);
const invitations=computed(()=>invitationLinks(server.value,code.value,lanAddresses.value));
const income=computed(()=>{void revision.value;const engine=e.value;if(!engine)return 0;return engine.s.buildings.filter(b=>b.owner===id.value&&b.type==='mine'&&b.hp>0&&b.settled).reduce((sum,b)=>sum+engine.mineOutput(b).rate,0)+engine.economy().passive;});
const isHost=computed(()=>id.value===host.value),s=computed(()=>{void revision.value;return e.value?{...e.value.s}:undefined;}),me=computed(()=>s.value?.coop?.players.find(p=>p.id===id.value)),selected=computed(()=>s.value?.buildings.find(b=>b.id===selection.value[0]&&b.hp>0&&b.owner===id.value)),intel=computed(()=>campaignIntel(CAMPAIGNS[options.value.stage],false));
const squads=ref<number[][]>([[],[],[],[],[]]);
const ownedBuildings=computed(()=>s.value?.buildings.filter(b=>b.owner===id.value&&b.hp>0)??[]);
const liveSelection=computed(()=>ownedBuildings.value.filter(b=>selection.value.includes(b.id)));
const liveSquads=computed(()=>squads.value.map(group=>ownedBuildings.value.filter(b=>group.includes(b.id)).map(b=>b.id)));
const canAct=computed(()=>{void revision.value;return connected.value&&!!e.value?.running;});
const modeLabel=computed(()=>relocate.value?'吊装位移':kind.value?'建造 · '+props.config.buildings[kind.value]?.name:liveSelection.value.length?'手动接管 · '+liveSelection.value.length+' 座':'自动防御');
function selectKind(k:string){if(k==='decoy'&&!isHost.value){error.value='投影塔仅房主可建造';return;}relocate.value=false;kind.value=k;selection.value=[];error.value='';stop();}
function selectSquad(i:number){relocate.value=false;kind.value='';selection.value=[...liveSquads.value[i]];stop();}
function saveSquad(i:number,replace=false){const ids=liveSelection.value.map(b=>b.id);squads.value[i]=replace?ids:[...new Set([...liveSquads.value[i],...ids])];}
function buildStatus(k:string){if(k==='decoy'&&!isHost.value)return '仅房主可建造';const b=props.config.buildings[k];if(e.value&&e.value.buildingCount(k)>=e.value.buildingLimit(k))return '全队已达上限';if((me.value?.gold??0)<b.cost)return '金币不足';return '';}
function upgradeGroup(branch:number){void revision.value;return e.value?.upgradeSelection(liveSelection.value.map(b=>b.id),branch);}
function upgradeDisabled(branch:number){const group=upgradeGroup(branch);return !canAct.value||!group?.buildings.length||(me.value?.gold??0)<group.cost;}
let ws:WebSocket|undefined,game:CoopGame|undefined,renderer:Renderer|undefined,raf=0,last=0,acc=0,lastSend=0,lastAim=0,lastState=0;let achievementSent=false;let hover=-999,layer=0,aim={x:0,y:0,fire:false};const audio=new AudioSystem();
function send(data:unknown){if(ws?.readyState===WebSocket.OPEN&&ws.bufferedAmount<2_000_000)ws.send(JSON.stringify(data));}
function command(c:unknown){if(!connected.value)return;if(isHost.value&&game){error.value=game.apply(id.value,c);}else send({type:'command',command:c});}
function aimCommand(){command({type:'aim',ids:kind.value?[]:selection.value,x:aim.x,y:aim.y,fire:aim.fire});}
function connect(create:boolean){
 error.value='';try{const url=new URL(server.value);if(!['http:','https:'].includes(url.protocol))throw Error('请输入 http://电脑IP:8000');url.protocol=url.protocol==='https:'?'wss:':'ws:';url.pathname='/api/lan';url.search='';ws?.close();const socket=new WebSocket(url);ws=socket;
 socket.onopen=()=>send({type:create?'create':'join',version:'1.0.0',code:code.value,name:name.value});
 socket.onerror=()=>error.value='无法连接联机服务，请检查地址、同一局域网及 Windows 防火墙。';
 socket.onclose=()=>{if(ws!==socket)return;connected.value=false;if(e.value)e.value.paused=true;status.value='连接已断开。本局停止，请返回大厅重新组队。';};
 socket.onmessage=async event=>{const m=JSON.parse(event.data);if(m.type==='error'){error.value=m.message;return;}if(m.type==='welcome'){lanAddresses.value=m.lanAddresses??[];id.value=m.id;host.value=m.host;code.value=m.code;connected.value=true;status.value='等待房主开战';}if(m.type==='roster')players.value=m.players;
 if(m.type==='feedback')error.value=m.message;
 if(m.type==='left'&&game){delete game.e.coopOrders[m.player];status.value='一名队友离开：建筑自动作战，人数强度维持开局设置。';}
 if(m.type==='ended'){status.value=m.message;connected.value=false;if(e.value)e.value.paused=true;}
 if(m.type==='start'){options.value=m.options;selection.value=[];kind.value='';relocate.value=false;squads.value=[[],[],[],[],[]];game=isHost.value?new CoopGame(props.config,m.players,m.options,m.seed,host.value):undefined;e.value=game?.e??new Engine(props.config,m.seed);lastState=performance.now();status.value='联合作战';await nextTick();if(canvas.value)renderer=new Renderer(canvas.value);audio.unlock();}
 if(m.type==='command'&&game){if(m.command?.type==='choose'){if(m.player===host.value)game.e.choose(m.command.id);}else {const message=game.apply(m.player,m.command);if(message)send({type:'feedback',player:m.player,message});}}
 if(m.type==='state'&&!isHost.value&&e.value){e.value.s=m.world;e.value.paused=m.paused;e.value.effects=m.effects;e.value.alert=m.alert;e.value.message=m.message;lastState=performance.now();if(status.value.startsWith('等待房主同步'))status.value='联合作战';for(const sound of m.sounds??[])audio.play(sound,volume.value);revision.value++;}
 };
 }catch(err){error.value=String(err);}
}
function start(){send({type:'start',options:options.value});}
function choose(k:string){if(isHost.value)game?.e.choose(k);}
function stop(){aim.fire=false;aimCommand();}
function cancel(){kind.value='';selection.value=[];relocate.value=false;stop();}
function pointer(ev:PointerEvent){if(!renderer)return;const p=renderer.point(ev.clientX,ev.clientY);hover=Math.floor(p.x);layer=Math.floor(p.y);aim={...p,fire:aim.fire};if(performance.now()-lastAim>50){lastAim=performance.now();aimCommand();}}
function down(ev:PointerEvent){if(ev.button!==0||!e.value?.running||!connected.value)return;audio.unlock();pointer(ev);if(ev.isTrusted)canvas.value?.setPointerCapture(ev.pointerId);if(relocate.value&&selected.value){command({type:'relocate',id:selected.value.id,column:hover,layer});relocate.value=false;return;}if(kind.value){command({type:'drop',kind:kind.value,column:hover,layer});return;}
 const b=e.value.s.buildings.find(b=>b.hp>0&&Math.abs(b.x-aim.x)<.5&&Math.abs(b.y-aim.y)<.5);
 if(b){if(b.owner!==id.value){error.value='这是队友的建筑';return;}selection.value=ev.shiftKey?[...new Set([...selection.value,b.id])]:[b.id];aimCommand();}else{aim.fire=true;aimCommand();}}
function same(){if(selected.value){selection.value=e.value!.s.buildings.filter(b=>b.owner===id.value&&b.type===selected.value!.type&&b.hp>0).map(b=>b.id);aimCommand();}}
function keyboard(ev:KeyboardEvent){if(!e.value||(ev.target as HTMLElement)?.matches('input,select,textarea'))return;if(ev.key==='Escape'){cancel();return;}const n=/^F[1-5]$/.test(ev.key)?Number(ev.key.slice(1))-1:ev.ctrlKey&&/^[1-5]$/.test(ev.key)?Number(ev.key)-1:-1;if(n>=0){ev.preventDefault();if(ev.ctrlKey)saveSquad(n,ev.shiftKey);else selectSquad(n);}if(ev.ctrlKey&&ev.key.toLowerCase()==='a'){ev.preventDefault();relocate.value=false;kind.value='';selection.value=ownedBuildings.value.filter(b=>e.value!.stats(b).damage>0).map(b=>b.id);stop();}if(ev.code==='Space'){if((ev.target as HTMLElement)?.closest('button,summary'))return;ev.preventDefault();if(isHost.value&&connected.value)e.value.paused=!e.value.paused;}}
function blur(){stop();if(isHost.value&&e.value)e.value.paused=true;}
function frame(now:number){const dt=Math.min(.1,(now-last)/1000);last=now;const engine=e.value;if(engine){if(isHost.value&&game&&connected.value){acc+=dt;while(acc>=1/60){game.step();acc-=1/60;}if(now-lastSend>100){lastSend=now;send({type:'state',world:engine.s,paused:engine.paused,effects:engine.effects,sounds:engine.sounds,alert:engine.alert,message:engine.message});for(const sound of engine.sounds.splice(0))audio.play(sound,volume.value);}}if(!achievementSent&&engine.s.campaign?.revealFrame!=null&&engine.s.campaign.revealFrame>=-360){achievementSent=true;emit('achievement');}const p=engine.s.coop?.players.find(p=>p.id===id.value);if(p){engine.s.gold=p.gold;engine.s.dropCooldown=p.cooldown;}engine.controlledIds=kind.value?[]:selection.value;engine.controlled=engine.controlledIds[0]??0;engine.aim=aim;renderer?.draw(engine,hover,kind.value,selection.value[0]??0,false,layer,selection.value,engine.chapter?.background??'city');audio.music(volume.value,engine.running);audio.storm(volume.value,!!engine.s.campaign?.storm);revision.value++;if(!isHost.value&&now-lastState>4000)status.value='等待房主同步，请房主保持游戏窗口打开';}raf=requestAnimationFrame(frame);}
onMounted(()=>{raf=requestAnimationFrame(frame);window.addEventListener('keydown',keyboard);window.addEventListener('blur',blur);});
onUnmounted(()=>{ws?.close();cancelAnimationFrame(raf);audio.close();window.removeEventListener('keydown',keyboard);window.removeEventListener('blur',blur);});
</script>
<template>
<main class="lan">
 <header><strong>战墙 · {{changelog.version}} 局域网合作</strong><span>{{status}}</span><button @click="emit('close')">{{isHost?'关闭房间 / 返回首页':'离开 / 返回首页'}}</button></header>
 <section v-if="!e" class="lobby">
  <h1>共筑一道防线。</h1><p>2—4 人共享地图与核心，各自拥有金币和建筑。房主电脑运行联机服务，队友打开同一局域网地址。</p>
  <p>下方服务地址用于本机连接；创建房间后，请分享单独列出的「邀请地址」。</p><label>服务地址<input v-model="server" placeholder="http://192.168.1.10:8000" :disabled="connected"></label><label>你的称呼<input v-model="name" maxlength="16" :disabled="connected"></label>
  <div v-if="!connected"><button @click="connect(true)">创建房间</button><input v-model="code" placeholder="六位房间码" maxlength="6"><button @click="connect(false)">加入房间</button></div>
  <template v-else><h2>房间码 {{code}}</h2><div class="invite"><b>发给队友的邀请地址</b><p v-for="link in invitations" :key="link"><a :href="link" target="_blank" rel="noopener">{{link}}</a></p><p v-if="!invitations.length">未识别到局域网地址。请从房主启动窗口查找 IP，用该地址重新打开游戏并创建房间；不要向队友发送 127.0.0.1 或 localhost。</p><small v-else>请复制上面的地址给队友。若有多个地址，选择当前 Wi-Fi / 热点对应的 IP。127.0.0.1 和 localhost 仅供本机访问。</small></div><p v-for="p in players" :style="{color:p.color}">● {{p.name}} {{p.id===host?' / 房主':''}}</p>
   <template v-if="isHost"><label>模式<select v-model="options.mode"><option value="endless">无限模式</option><option value="test">双线测试 · 10 分钟开启左翼</option><option value="campaign">故事战役</option></select></label><label v-if="options.mode!=='campaign'">难度<select v-model="options.difficulty"><option value="easy">简单</option><option value="normal">普通</option><option value="hard">困难</option></select></label><label v-else>关卡<select v-model="options.stage"><option v-for="(c,i) in CAMPAIGNS" :value="i">{{i+1}}. {{c.title}}</option></select></label><p v-if="options.mode==='campaign'">{{intel.story}}<br>{{intel.hint}}</p><button @click="start">开始合作（{{players.length}} 人）</button></template>
  </template>
  <p>每增加一人：敌人生命 +65%、伤害 +20%、刷怪速率 +35%。狙击塔 20 座、诱饵塔 1 座为全队上限，投影塔仅房主可建造。击杀与军械箱金币平分；矿场收入归建造者，基础收入每人独立领取。</p><p>房主负责模拟，请保持窗口打开；切出自动暂停。队友掉线后建筑自动防御，本局不能中途加入，房主离开则结束。联机不覆盖单人存档。</p>
 </section>
 <template v-else-if="s">
  <div class="bar"><b>你的金币 {{Math.floor(me?.gold??0)}} G</b><span>产能 {{income.toFixed(1)}} G/分</span><span>核心 {{Math.ceil(s.coreHp)}} · {{Math.floor(s.tick/3600)}}:{{String(Math.floor(s.tick/60)%60).padStart(2,'0')}}</span><span v-for="p in s.coop?.players" :key="p.id" class="player-chip" :style="{color:p.color}">● {{p.name}} {{Math.floor(p.gold)}} G</span><button v-if="isHost" :disabled="!connected||!s.alive||!!s.campaign?.won||e.cinematic" @click="e.paused=!e.paused">{{e.paused?'继续战斗':'暂停'}}</button><button v-if="e.leftOpen" @click="e.viewSide=e.viewSide==='left'?'right':'left'">切换左右战场</button><label>音量<input v-model.number="volume" type="range" min="0" max="1" step=".05"></label></div>
  <details v-if="e.chapter"><summary>关卡简报 · {{e.chapter.title}}</summary><p>{{campaignIntel(e.chapter,false).story}}</p><p>{{campaignIntel(e.chapter,false).hint}}</p></details><div class="arena"><canvas ref="canvas" @pointermove="pointer" @pointerdown="down" @pointerup="stop" @pointercancel="stop" @lostpointercapture="stop" @dblclick="same" @contextmenu.prevent="cancel"></canvas>
   <div class="notice" v-if="e.cinematic"><h2>{{(s.campaign?.revealFrame??0)<-360?'正在确认战场……':(s.campaign?.revealFrame??0)<180?'成就达成 · 结束了？':'沉船……在动。'}}</h2><p>战斗暂停 · 操作锁定</p></div>
   <div class="notice" v-else-if="!s.alive||s.campaign?.won||e.paused||s.candidates.length"><CampaignVictory v-if="s.campaign?.won" :stage="s.campaign.stage" :ticks="s.tick" :kills="s.kills" :boss-kills="s.bossKills" :saving="!isHost" @menu="emit('close')" @next="options.stage++;start()" @retry="start" /><h2 v-else>{{!s.alive?'防线失守':s.campaign?.won?'联合战役胜利':s.candidates.length?'全队强化 · 房主选择':'战斗已暂停'}}</h2><button v-if="isHost&&e.paused" @click="e.paused=false">继续</button><button v-for="k in s.candidates" :disabled="!isHost" @click="choose(k)">{{config.perks[k]?.name}} · {{config.perks[k]?.description}}</button><template v-if="isHost&&(!s.alive||s.campaign?.won)"><button @click="start">重玩本局</button><button v-if="s.campaign?.won&&options.stage<4" @click="options.stage++;start()">下一场战役</button></template></div>
   <div class="boss" v-for="b in s.enemies.filter(b=>b.type==='leviathan')"><b>{{config.enemies[b.type].name}} {{Math.ceil(b.hp)}} / {{Math.ceil(b.maxHp)}}</b><progress :value="b.hp" :max="b.maxHp"></progress></div>
  </div>
  <p class="message">{{error||e.message||(e.alert.until>e.time?e.alert.title+' · '+e.alert.detail:'点击建筑接管，按住空地瞄准开火；右键退出。Shift 多选 / 双击同类 / Ctrl+A 所有攻击塔。')}}</p>
  <section class="command-deck" aria-label="联机操作栏">
   <div class="deck-heading"><div><small>联合指挥</small><strong>{{modeLabel}}</strong></div><span class="deploy-state">{{!connected?'连接已断开':!canAct?'战斗操作已暂停':(me?.cooldown??0)>0?'投放冷却 '+me!.cooldown.toFixed(1)+' 秒':'投放已就绪'}}</span><button :class="{active:!kind&&!liveSelection.length}" @click="cancel">选择 / 自动防御 <kbd>Esc</kbd></button></div>
   <div class="tray" aria-label="建造建筑"><button v-for="(b,k) in config.buildings" v-show="e.buildingUnlocked(k)" :key="k" :disabled="k==='decoy'&&!isHost" :class="{active:kind===k,unaffordable:!!buildStatus(k)}" :aria-pressed="kind===k" :title="b.description+(buildStatus(k)?' · '+buildStatus(k):'')" @click="selectKind(k)"><span class="build-icon" aria-hidden="true">{{b.icon}}</span><span class="build-copy"><b>{{b.name}}</b><small>{{b.cost}} G <span v-if="buildStatus(k)">· {{buildStatus(k)}}</span></small></span></button></div>
   <div class="squad-row"><span class="section-label">我的编队</span><div class="squad-list"><div v-for="(group,i) in liveSquads" :key="i" class="squad-slot"><button :disabled="!group.length" :aria-pressed="!kind&&group.length>0&&group.length===liveSelection.length&&group.every(id=>selection.includes(id))" @click="selectSquad(i)">部队 {{i+1}} <kbd>F{{i+1}}</kbd><small>{{group.length}} 座</small></button><button class="squad-save" :disabled="!liveSelection.length" :title="'将当前选择加入部队 '+(i+1)+'；Shift 点击替换'" :aria-label="'加入部队 '+(i+1)" @click="saveSquad(i,$event.shiftKey)">＋</button></div></div><details class="control-help"><summary>操作说明</summary><p>点击自己的建筑接管，按住空地瞄准开火；右键 / Esc 恢复自动防御。Shift 点击多选，双击同类，Ctrl+A 选择全部攻击塔。</p><p>＋ / Ctrl+1—5 加入编队；Shift 点击＋ / Ctrl+Shift+1—5 替换；F1—F5 选择编队。编队仅保留本局存活建筑。</p></details></div>
   <div v-if="selected" class="selection-panel"><div class="selection-info"><strong>{{config.buildings[selected.type].name}} <small>已选 {{liveSelection.length}} 座</small></strong><span>{{Math.ceil(selected.hp)}} / {{Math.ceil(e.stats(selected).hp)}} HP · {{selected.settled?'已落稳':'下落中'}}</span></div><div class="selection-actions"><button v-for="(b,i) in config.buildings[selected.type].branches" :key="i" :disabled="upgradeDisabled(i)" :title="b.description" @click="command({type:'upgradeMany',ids:liveSelection.map(b=>b.id),branch:i})"><b>{{b.name}}</b><small>{{upgradeGroup(i)?.buildings.length?'升级 '+upgradeGroup(i)!.buildings.length+' 座 · '+upgradeGroup(i)!.cost+' G':'暂无可升级建筑'}}</small></button><button :class="{active:relocate}" :disabled="!canAct||!selected.settled" @click="relocate=!relocate;stop()">{{relocate?'取消吊装':'吊装位移'}}<small>{{relocate?'点击战场目标格':(config.schedule.craneCost??35)+' G · 需就绪吊装站'}}</small></button><button class="danger" :disabled="!canAct||!selected.settled" @click="command({type:'demolish',id:selected.id});cancel()">拆除选中建筑<small>仅此座 · 返还 {{e.refund(selected)}} G · 0.3 秒后执行</small></button></div></div>
   <p v-else class="deck-hint">{{kind?config.buildings[kind].description+' · 点击战场投放，右键取消。':'选择建筑卡片开始建造，或点击自己的建筑进行接管、升级与吊装。'}}</p>
  </section>
 </template><p class="message" v-if="!e">{{error}}</p>
</main>
</template>
<style scoped>
.invite{padding:16px;border:1px solid #617558;border-radius:8px}.invite a{color:#8bdeed;overflow-wrap:anywhere}.lan{min-height:100vh;background:#0b1512;color:#d8e5cb;padding:16px;font-family:'Microsoft YaHei',sans-serif}.lan header,.bar,.tray{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.lan header{justify-content:space-between}.lobby{max-width:800px;margin:50px auto;padding:30px;background:#1a291f;border:1px solid #52644c;border-radius:14px}.lobby p{line-height:1.8;color:#aebfa5}label{display:inline-flex;gap:12px;align-items:center;margin:10px 8px}input,select,button{background:#22362c;color:#d8e5cb;border:1px solid #617558;padding:9px;border-radius:5px}button{cursor:pointer}button:hover,button.active{background:#49604a}button:disabled{opacity:.5}.bar{padding:10px 0}.arena{position:relative;width:100%;height:min(64vh,720px);min-height:330px}canvas{width:100%;height:100%;touch-action:none}.notice{position:absolute;top:25%;left:20%;width:60%;text-align:center;padding:24px;background:#102019ed;border:1px solid #91b184}.notice button{margin:8px}.boss{position:absolute;top:12px;left:25%;width:50%;text-align:center;background:#291318}.boss progress{width:100%;accent-color:#d62c3b}.message{min-height:24px;color:#edbd83}.tray button{font-size:12px;padding:8px}.bar label input{width:100px}

.command-deck{border:1px solid #40584c;border-radius:12px;background:linear-gradient(135deg,#182b23,#102019);overflow:hidden;margin-top:10px;box-shadow:0 8px 26px #0003}.deck-heading{display:flex;align-items:center;gap:16px;padding:12px 16px;border-bottom:1px solid #344b3e}.deck-heading>div{display:flex;align-items:center;gap:12px}.deck-heading small,.section-label{color:#9bb7a7;font-size:12px}.deck-heading strong{color:#e0edc5}.deploy-state{margin-left:auto;font-size:12px;color:#d9c48c;font-variant-numeric:tabular-nums}kbd{font:10px monospace;border:1px solid #64816c;border-radius:3px;padding:2px 4px;color:#b7ccbb;margin-left:5px}.command-deck .tray{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:7px;padding:12px 16px}.command-deck .tray button{display:flex;align-items:center;gap:10px;text-align:left;min-height:58px;background:#1b3026;border-color:#3a5143}.build-icon{font-size:25px;color:#b9d68d;width:28px;text-align:center}.build-copy{display:grid;gap:6px}.build-copy small{font-size:11px;color:#b7cbbd}.command-deck .tray button.unaffordable small{color:#e2ad83}.command-deck button.active,.squad-slot button[aria-pressed="true"]{background:#3a5033;border-color:#b5d780;box-shadow:inset 0 0 0 1px #b5d780}.squad-row{display:flex;align-items:center;gap:12px;padding:10px 16px;border-top:1px solid #344b3e;flex-wrap:wrap}.squad-list{display:flex;gap:8px;flex-wrap:wrap}.squad-slot{display:flex;gap:3px}.squad-slot button{font-size:12px}.squad-slot small{margin-left:8px;color:#a6bcab}.squad-save{padding:8px}.control-help{margin-left:auto;max-width:100%;font-size:12px;color:#a9c0ae}.control-help summary{cursor:pointer;padding:8px}.control-help p{line-height:1.7;max-width:650px}.selection-panel{display:flex;align-items:center;gap:18px;padding:12px 16px;border-top:1px solid #344b3e;background:#0b181180;flex-wrap:wrap}.selection-info{display:grid;gap:8px;min-width:180px}.selection-info span,.selection-info small{font-size:12px;color:#a9c0ae}.selection-actions{display:flex;gap:8px;flex-wrap:wrap;flex:1}.selection-actions button{display:grid;gap:6px;flex:1;min-width:130px;font-size:12px}.selection-actions small{font-size:11px;color:#b6c8bb}.selection-actions .danger{border-color:#805a4c;color:#f2baa3}.deck-hint{padding:12px 16px;margin:0;border-top:1px solid #344b3e;color:#a9c0ae;font-size:12px;line-height:1.7}.lan button:focus-visible,.control-help summary:focus-visible{outline:2px solid #d7ecac;outline-offset:3px}.lan button:hover:not(:disabled){border-color:#a2bd8e}.lan button:disabled{cursor:not-allowed}.player-chip{padding:5px 9px;background:#1b2a22;border-radius:5px;font-size:12px}.lan .arena{height:clamp(330px,49vh,720px)}
@media(max-width:760px){.lan{padding:10px}.deck-heading{flex-wrap:wrap;gap:10px}.deck-heading>div{flex-wrap:wrap}.deploy-state{margin-left:0}.command-deck .tray{grid-template-columns:repeat(3,minmax(0,1fr));padding:10px;gap:6px}.command-deck .tray button{padding:8px;gap:5px}.build-icon{font-size:18px;width:20px;flex-shrink:0}.build-copy b{font-size:11px}.build-copy small{font-size:10px}.squad-row,.selection-panel{padding:10px}.control-help{margin-left:0}.lan header{gap:10px}.bar{gap:8px}.lobby{padding:16px}.notice{left:5%;width:90%;box-sizing:border-box}}
@media(max-width:420px){.command-deck .tray{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
