<script setup lang="ts">
import {computed,nextTick,onMounted,onUnmounted,ref,shallowRef} from 'vue';
import {Engine} from '../game/engine';import {Renderer} from '../game/render/canvas';
import config from '../../../content/game-config.json' with {type:'json'};import {enemyLore} from '../game/render/enemies';import {EVENTS} from '../game/incidents';
const emit=defineEmits<{finish:[]}>();
const chapters=[
 {title:'你的第一场防守',text:'守住左侧核心，抵挡右侧不断增强的敌人。在经济、地面火力、防空与维修之间持续取舍，坚持得越久越好。',tips:['先完成 4 个实操，再按目录查阅全部建筑、敌人和事件。','练习使用独立战场，不修改你的金币和存档。随时跳过，也可以从设置重新打开。']},
 {title:'投放与支撑',text:'先选择城墙，再点击练习战场。建筑从顶部落下，落稳后才工作；普通建筑沿目标列堆叠。',tips:['砸击敌人：在敌人即将经过的列提前投放建筑，下落途中碰到敌人即可造成砸击伤害。注意预判敌人移动，并确保下落路径不会先被已有建筑挡住。','砸击伤害取决于建筑类型，可通过「重压投放」强化提高；同一次下落对同一敌人只结算一次，落稳后不会持续砸击。','数字 1—9、0、-、[、] 选择建筑；右键取消。投放有金币费用与冷却。','桥梁可点击指定高度水平铺设，需要稳定支撑。失去全部支撑的桥段及上层建筑会下落，坠落不伤友军。']},
 {title:'点击接管与瞄准',text:'接管练习箭塔，然后点击战场向敌人开火。正式游戏点击防御塔直接接管，指向敌人并按住左键持续射击。',tips:['自动防御无需操作；接管后等待你的开火命令。右键 / E 退出，Space 暂停。点击另一座塔直接切换。','手动操控仍受射程、最小射程、冷却、遮挡及对空／对地限制，不会额外增加伤害。']},
 {title:'分支升级与回收',text:'建筑有两条升级方向，只能选择其中一条。查看费用和实际属性，再决定如何分工。',tips:['Shift + 点击多选，在侧栏按方向 1 或 2 统一升级；不同建筑的同一方向含义可能不同。','按住拆除 0.3 秒回收部分投资，回收额受当前生命影响。拆除支撑前先考虑上层建筑。']},
 {title:'建立你的部队',text:'Shift 多选建筑后，加入 5 个编队之一。编队可包含生产和辅助建筑；接管时只有已落稳的武器塔参与瞄准。',tips:['Ctrl + A 接管所有已落稳攻击塔；F1—F5 选择并接管；Ctrl + F1—F5 追加成员；Ctrl + Shift + F1—F5 替换编队。','也可点部队按钮后点击加入、替换或清空。同一建筑可属于多个部队，编队随战局保存，忽略已摧毁成员。','整队瞄准同一点，各塔独立判断可否命中。右键退出整队手控，恢复自动防御。']},
 {title:'建筑与升级图册',text:'展开下面的设施卡片，查看全部建筑的用途和升级方向。具体数值以当前战局侧栏为准。',tips:['狙击塔所有难度最多 20 座，拦截阵列最多 4 座，下落中的建筑也占名额。','吊装站将建筑直接移动到有支撑的空格，可放入桥梁下方。起终点均须在同一就绪吊装站范围内，花费 35 G 并进入冷却。','拦截阵列可拦截部分实体炸弹和岩弹，不能拦截激光、震波、巨型陨石、飞船本体或坠落残骸。']},
 {title:'经济与长期强化',text:'矿场、击杀奖励与被动收入支持重建。不要把全部经济堆在一处，也不要为了产钱放弃即时防御。',tips:['超过前 6 座与同列堆叠只降低后建矿场收益，不拖累已有矿场；侧栏显示原产能、损失与经济总产能；矿区爆破会针对矿场。','周期强化与击败 Boss 提供强化选择，选择时暂停；先读效果再确认。','维修站恢复附近结构，增幅器强化附近火力，冰霜塔控制敌人。分散辅助阵地，留钱重建。']},
 {title:'难度、射界与时间',text:'普通和困难增加敌人生命、伤害及数量速率，可在设置中切换。',tips:['简单 / 普通：子弹、箭矢、炮弹穿透全部友方建筑。','困难：只有子弹穿城墙，箭矢与炮弹可穿其他友方建筑。抬高炮位改善射界；敌方及反弹弹体不享受穿透。','敌人和 Boss 每分钟强化，第 10 分钟后增长加快；后续 Boss 额外成长。在场敌人保持生命比例同步成长。','每分钟经历常态、强袭和缓和阶段，留意倒计时。暂停不增长难度；困难首个 Boss 为地面巨兽。']},
 {title:'敌军与协同',text:'以下包含全部怪物的行为与应对方式。敌人的角色决定你应当优先使用哪种火力。',tips:['空投单位下降时是空中目标，落地后改用地面火力。','指挥虫组织护盾掩护，护盾真实消耗；堡垒吸引自动防空，手动瞄准可以绕过。','自爆飞船集结 3 艘或等待 10 秒后齐袭高价值设施，提前击落没有伤害爆炸；堡垒坠爆会伤害建筑和地面虫群。']},
 {title:'Boss 与部位破坏',text:'Boss 技能有文字、落点与倒计时提示，很多技能造成范围伤害，不能只靠前墙拖延。',tips:['母舰火控面板可选择舰体、机库、导弹舱或主核心。破坏机库减少增援，破坏导弹舱停止后续齐射。','母舰投弹后核心短暂暴露，封闭时瞄准核心收益低；击毁后仍须撤离残骸坠落区域。','沙虫潜地不可攻击，钻出会摧毁标记通道内建筑；提前吊装或回收，出土时集中火力。','虫后繁殖并喷酸，雷暴 Boss 落雷覆盖多个目标。地面火力与防空都需要冗余。']},
 {title:'突发事件与补给',text:'预警是行动窗口。观察标记范围，决定拦截、移动、回收还是承受冲击。',tips:['军械箱有回收时限：4 格内有建筑、3 格内无敌人时累计守护 20 秒，获得 150 G 与一次强化。敌人会阻止回收并破坏箱子。','上层结构可能先挡住爆炸。保留机动预算，不要让一次事件摧毁全部经济。']},
 {title:'保存、设置与快捷键',text:'每 15 秒自动保存，也可在菜单保存退出。继续战局后先确认阵地，再按 Space 恢复。',tips:['切换窗口自动暂停；离线时保留浏览器备份，冲突时按提示选择来源，可导出存档。','离线分享版的存档仅在当前浏览器，转发游戏文件不会自动转发你的进度。','设置支持宽阔 / 经典布局、五种背景、音量和减少动态效果。布局不改变坐标与射程。','新局可勾选双线测试模式：10 分钟开启左侧 20 列建造区，20 秒后左翼进攻。通过左右按钮切换视角，两线始终持续战斗，共用金币和核心。','F1—F5 选队，Ctrl + F 追加，Ctrl + Shift + F 替换；Shift 点击多选；右键取消建造或操控；Space 暂停。']},
 {title:'出发前检查',text:'第一条防线不必复杂：前墙、地面武器、矿场、防空，再逐步增加维修和机动能力。',tips:['混合火力：不要全靠炮击，也不要忽视天空。','分散经济：避免单列堆叠，留钱应付爆破与重建。','组建部队：防空与地面火力分组，危险目标出现时快速接管。','看预警：沙虫、残骸和轰炸出现时，优先保住关键设施。']}
];
const step=ref(0),done=ref<number[]>([]),feedback=ref(''),armed=ref(false),canvas=ref<HTMLCanvasElement>(),practice=shallowRef<Engine>();let renderer:Renderer|undefined,raf=0;
const chapter=computed(()=>chapters[step.value]);
function advance(n=step.value+1){step.value=n;feedback.value='';armed.value=false;void resetPractice();}
function add(e:Engine,type:string,x:number){const p=e.config.buildings[type];e.s.buildings.push({id:e.s.nextEntityId++,type,branch:-1,spent:p.cost,x,y:.5,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:0});}
async function resetPractice(){if(step.value<1||step.value>4){practice.value=undefined;return;}const e=new Engine(config,123,'tutorial-only');e.s.gold=3000;e.s.nextBoss=e.s.nextEvent=e.s.nextPerk=99999;e.s.spawnCredit=-99999;if(step.value>1){add(e,'ballista',18.5);add(e,'ballista',19.5);e.spawn('siege',false,22,.65);}practice.value=e;await nextTick();if(canvas.value)renderer=new Renderer(canvas.value);}
function run(n:number){for(let i=0;i<n;i++)practice.value!.step();}
function success(text:string){feedback.value=text;if(!done.value.includes(step.value))done.value.push(step.value);}
function practiceClick(){const e=practice.value;if(!e||!armed.value)return;if(step.value===1){e.command({type:'drop',kind:'wall',column:20});run(250);success('✓ 城墙已落稳，费用和冷却按真实规则结算。');}else if(step.value===2){const target=e.s.enemies[0];if(target){e.aim={x:target.x,y:target.y,fire:true};run(90);e.aim.fire=false;success('✓ 已执行手动射击；右键退出后恢复自动防御。');}}armed.value=false;}
function takeControl(){practice.value?.control(practice.value.s.buildings[0].id??0);armed.value=true;feedback.value='已接管，请点击战场发射。';}
function upgrade(branch:number){const e=practice.value!;e.command({type:'upgrade',id:e.s.buildings[0].id,branch});run(1);success('✓ 已升级：'+e.stats(e.s.buildings[0]).name);}
function formSquad(){const e=practice.value!;e.assignSquad(0,e.s.buildings.map(b=>b.id));e.controlMany(e.squadMembers(0));success('✓ 部队 1 已编入并接管 2 座箭塔。正式战局按 F1 快速选中。');}
function draw(){raf=requestAnimationFrame(draw);if(renderer&&practice.value)renderer.draw(practice.value,step.value===1?20:-1,step.value===1&&armed.value?'wall':'',practice.value.controlled,true,0,practice.value.controlledIds,'city');}
onMounted(draw);onUnmounted(()=>cancelAnimationFrame(raf));
</script>
<template><div class="academy" aria-label="指挥学院" @keydown.esc.prevent="emit('finish')"><header class="academy-top"><div><small>WARWALL / 指挥学院</small><h2>从筑墙到指挥整条防线</h2></div><button @click="emit('finish')">跳过引导</button></header><div class="academy-body"><nav aria-label="引导章节"><button v-for="(c,i) in chapters" :class="{active:step===i}" :aria-current="step===i?'step':undefined" @click="advance(i)"><span>{{String(i+1).padStart(2,'0')}}</span>{{c.title}}<small v-if="done.includes(i)">✓</small></button></nav><article><div class="eyebrow">{{step>=1&&step<=4?'实操训练':'指挥手册'}} · {{step+1}} / {{chapters.length}}</div><h3 aria-live="polite">{{chapter.title}}</h3><p>{{chapter.text}}</p><div v-if="step>=1&&step<=4" class="academy-practice"><canvas ref="canvas" aria-label="独立练习战场" @pointerdown="practiceClick" @contextmenu.prevent="practice?.control(0)"></canvas><div class="practice-tools"><button v-if="step===1" :disabled="done.includes(1)" @click="armed=true;feedback='已选择城墙，点击战场投放到高亮列。'">选择城墙</button><button v-if="step===2" @click="takeControl">接管练习箭塔</button><template v-if="step===3"><button v-for="(b,i) in config.buildings.ballista.branches" :disabled="practice?.s.buildings[0].branch!==-1" @click="upgrade(i)">{{b.name}}</button></template><button v-if="step===4" @click="formSquad">编入部队 1 并接管</button><button @click="done=done.filter(i=>i!==step);feedback='';armed=false;resetPractice()">重置练习</button></div><p role="status">{{feedback||'独立训练场 · 点击操作开始练习'}}</p></div><ul><li v-for="tip in chapter.tips">{{tip}}</li></ul><div v-if="step===5" class="academy-reference"><details v-for="b in config.buildings"><summary>{{b.icon}} {{b.name}} · {{b.cost}} G</summary><p>{{b.description}}</p><p>升级：{{b.branches.map(a=>a.name).join(' / ')}}</p></details></div><div v-if="step===6" class="academy-reference"><details v-for="perk in config.perks"><summary>{{perk.name}}</summary><p>{{perk.description}} · 最多 {{perk.max}} 次</p></details></div><div v-if="step===8" class="academy-reference"><details v-for="(a,k) in config.enemies"><summary>{{a.name}} · {{enemyLore[k].role}}</summary><p>{{enemyLore[k].behavior}}</p><p>应对：{{enemyLore[k].counter}}</p></details></div><div v-if="step===10" class="academy-reference"><details v-for="event in EVENTS"><summary>{{event.title}}</summary><p>{{event.detail}}</p></details></div></article></div><footer><span>实操完成 {{done.length}} / 4 · 目录可随时跳转</span><button :disabled="step===0" @click="advance(step-1)">上一步</button><button class="primary" @click="step===chapters.length-1?emit('finish'):advance()">{{step===chapters.length-1?'完成引导':'下一章 →'}}</button></footer></div></template>
<style scoped>
.academy-top{display:flex;justify-content:space-between;align-items:center;gap:16px;border-bottom:1px solid #536348;padding-bottom:14px}.academy-top h2{margin:6px 0!important;font-size:22px!important}.academy-top small{letter-spacing:2px;color:#c7d49d}.academy-top button{white-space:nowrap}.academy-body{display:grid;grid-template-columns:178px minmax(0,1fr);height:min(60vh,600px);margin-top:16px;gap:24px}.academy nav{overflow:auto;display:flex;flex-direction:column;gap:5px}.academy nav button{text-align:left;font-size:12px;padding:11px 8px;display:flex;gap:7px}.academy nav span{color:#91a482}.academy nav .active{border-color:#d2dba0;background:#35432c}.academy article{overflow:auto;padding-right:10px}.academy article h3{font-size:26px;margin:10px 0}.academy article p,.academy li{font-size:13px;line-height:1.85}.academy ul{padding-left:19px}.academy li{margin:10px 0;color:#bbc8ae}.academy footer{display:flex;align-items:center;gap:10px;margin-top:18px}.academy footer span{flex:1;color:#9ca88e;font-size:12px}.academy-practice{background:#101b18;padding:10px;border:1px solid #4b6048}.academy-practice canvas{width:100%;height:200px;display:block;cursor:crosshair}.practice-tools{display:flex;flex-wrap:wrap;gap:8px}.practice-tools button{font-size:12px;padding:8px 12px}.academy-practice p{margin:8px 0 0;color:#dbd9a3}.academy-reference details{border:1px solid #43543c;padding:12px;margin:8px 0}.academy-reference summary{cursor:pointer;color:#d3dfb6}.academy-reference p{margin:10px 0 0}@media(max-width:800px){.academy-body{grid-template-columns:135px minmax(0,1fr);gap:12px}.academy nav button{font-size:11px}.academy footer span{display:none}}
</style>
