import {test,expect} from '@playwright/test';import {Engine} from '../../src/game/engine';import {readFileSync} from 'node:fs';
const config=JSON.parse(readFileSync('../content/game-config.json','utf8'));
test('campaign omits survival unlock announcements but keeps core warnings; survival keeps unlocks',async({page})=>{
 const unlock=Object.values(config.enemies).filter((p:any)=>!p.boss&&p.unlock>15).sort((a:any,b:any)=>a.unlock-b.unlock)[0] as any;
 const campaign=new Engine(config,123,'campaign-warning');campaign.startCampaign(0);campaign.s.tick=(unlock.unlock-5)*60;
 await mock(page,campaign.snapshot());await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.mission-strip')).toBeVisible();await expect(page.locator('.warning')).toHaveCount(0);
 campaign.s.coreHp=800;await page.unroute('**/api/v1/**');await mock(page,campaign.snapshot());await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.warning')).toContainText('核心生命危急');
 const survival=new Engine(config,123,'survival-warning');survival.s.tick=(unlock.unlock-5)*60;await page.unroute('**/api/v1/**');await mock(page,survival.snapshot());await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.warning')).toContainText(unlock.name+'将在 5 秒后加入刷怪池');
});
async function mock(page:any,initial:any=null,cleared=0){const store={snapshot:initial,settings:{musicVolume:0,sfxVolume:0,tutorialSeen:true,campaignCleared:cleared}};await page.route('**/api/v1/**',(r:any)=>{const p=new URL(r.request().url()).pathname;if(r.request().method()==='PUT'){if(p.endsWith('/settings'))store.settings=r.request().postDataJSON();if(p.endsWith('/save'))store.snapshot=r.request().postDataJSON().snapshot;}const data=p.endsWith('/config')?config:p.endsWith('/settings')?store.settings:p.endsWith('/save')&&store.snapshot?{revision:0,snapshot:store.snapshot}:null;return r.fulfill({status:data?200:204,contentType:'application/json',body:data?JSON.stringify(data):undefined});});await page.goto('/');return store;}
test('campaign entry presents maps, locks later chapters, gives briefing and restricts build tray',async({page},info)=>{const store=await mock(page);await page.getByRole('button',{name:/故事战役/}).click();await expect(page.locator('.campaign-map nav button')).toHaveCount(5);await page.locator('.campaign-map nav button').last().click();await expect(page.getByRole('button',{name:'先完成上一关'})).toBeDisabled();await page.locator('.campaign-map nav button').first().click();await page.screenshot({path:`../docs/campaign-map-${info.project.name}.png`});await page.getByRole('button',{name:/出击 ·/}).click();await expect(page.locator('.mission-tip')).toContainText('投放建筑也能砸击');await page.getByRole('button',{name:'开始 / 继续战役'}).click();await expect(page.locator('.mission-strip')).toContainText('余烬哨站');await expect(page.locator('.building-card').filter({hasText:'狙击塔'})).toBeDisabled();await expect(page.locator('.building-card').filter({hasText:'城墙'})).toBeEnabled();expect(store.snapshot.campaign.stage).toBe(0);await page.screenshot({path:`../docs/campaign-first-${info.project.name}.png`});});
test('chapter victory persists unlock and advances with next chapter briefing',async({page})=>{const e=new Engine(config,123,'chapter-win');e.startCampaign(0);e.s.campaign!.spawned=1;e.s.campaign!.won=true;e.s.bossKills=e.s.bossCount=1;e.s.tick=10000;const store=await mock(page,e.snapshot());await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.campaign-victory')).toBeVisible();await expect.poll(()=>store.settings.campaignCleared).toBe(1);await page.getByRole('button',{name:/前往 灰烬之城/}).click();await page.getByRole('button',{name:'开始 / 继续战役'}).click();await expect(page.locator('.mission-strip')).toContainText('重燃城市');await expect(page.locator('.building-card').filter({hasText:'防空塔'})).toBeEnabled();expect(store.snapshot.campaign.stage).toBe(1);});
test('final victory uses its own ending screen and survives reload',async({page},info)=>{const e=new Engine(config,123,'final-win');e.startCampaign(4);e.s.campaign!.spawned=3;e.s.campaign!.won=true;e.s.bossKills=e.s.bossCount=3;e.s.tick=40000;const errors:string[]=[];page.on('pageerror',a=>errors.push(a.message));const store=await mock(page,e.snapshot(),4);await page.getByRole('button',{name:/继续防守/}).click();await expect(page.getByRole('heading',{name:'黎明，终于抵达。'})).toBeVisible();await expect.poll(()=>store.settings.campaignCleared).toBe(5);await expect(page.locator('.victory-route span')).toHaveCount(5);await page.screenshot({path:`../docs/campaign-finale-${info.project.name}.png`});await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.campaign-victory.finale')).toBeVisible();expect(errors).toEqual([]);});
