import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';import {Engine} from '../../src/game/engine';
const config=JSON.parse(readFileSync('../content/game-config.json','utf8'));
test('difficulty choices explain penetration and persist a current-game change',async({page},info)=>{
 const e=new Engine(config,1,'difficulty-ui');const saves:any[]=[];const errors:string[]=[];page.on('pageerror',a=>errors.push(a.message));
 await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname;if(p.endsWith('/save')&&r.request().method()==='PUT')saves.push(r.request().postDataJSON());const data=p.endsWith('/config')?config:p.endsWith('/save')?{revision:0,snapshot:e.snapshot()}:p.endsWith('/settings')?{musicVolume:0,sfxVolume:0,reducedMotion:true,tutorialSeen:true}:null;return r.fulfill({status:data?200:204,contentType:'application/json',body:data?JSON.stringify(data):undefined});});
 await page.goto('/');await page.getByLabel('新局难度').selectOption('hard');await expect(page.locator('.difficulty-choice')).toContainText('仅子弹穿城墙');await page.screenshot({path:`../docs/difficulty-menu-${info.project.name}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:/继续防守/}).click();await page.getByRole('button',{name:'⚙ 设置'}).click();await page.getByLabel('战局难度',{exact:true}).selectOption('hard');await expect.poll(()=>saves.at(-1)?.snapshot.difficulty).toBe('hard');await expect(page.locator('.difficulty-choice')).toContainText('困难仅子弹穿城墙');await page.getByRole('button',{name:'完成',exact:true}).click();await expect(page.locator('.hud')).toContainText('困难');expect(errors).toEqual([]);
});
test('all revised monster portraits remain distinct',async({page},info)=>{await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname,data=p.endsWith('/config')?config:p.endsWith('/settings')?{musicVolume:0,sfxVolume:0,reducedMotion:true,tutorialSeen:true}:null;return r.fulfill({status:data?200:204,contentType:'application/json',body:data?JSON.stringify(data):undefined});});await page.goto('/');await page.getByRole('button',{name:/怪物图鉴/}).click();await page.locator('.guide-list button').filter({hasText:'异形母舰'}).click();await expect(page.locator('.guide-name h3')).toHaveText('异形母舰');await page.screenshot({path:`../docs/carrier-redesign-${info.project.name}.png`});});
