import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';import {Engine} from '../../src/game/engine';
const config=JSON.parse(readFileSync('../content/game-config.json','utf8'));
test('building variations, multi-upgrade, manual control, warnings and new guide entries',async({page},info)=>{
 const e=new Engine(config,123,'expansion-ui');e.s.gold=5000;e.s.nextPerk=99999;
 for(const [i,type] of Object.keys(config.buildings).entries())for(let j=0;j<3;j++){const branch=j-1,p={...config.buildings[type],...(branch>=0?config.buildings[type].branches[branch]:{})};e.s.buildings.push({id:e.s.nextEntityId++,type,x:4.5+i,y:.5+j,branch,spent:p.cost,hp:p.hp*(j===0?1:j===1?.6:.25),settled:true,v:0,fallId:1,hit:[],cooldown:100});}
 const errors:string[]=[];page.on('pageerror',x=>errors.push(x.message));
 await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname;const data=p.endsWith('/config')?config:p.endsWith('/save')?{revision:0,snapshot:e.snapshot(),savedAt:new Date().toISOString()}:p.endsWith('/settings')?{musicVolume:0,sfxVolume:0,reducedMotion:false,tutorialSeen:true}:null;return r.fulfill({status:data?200:204,contentType:'application/json',body:data?JSON.stringify(data):undefined});});
 await page.goto('/');await page.getByRole('button',{name:/怪物图鉴/}).click();await expect(page.locator('.guide-list button')).toHaveCount(Object.keys(config.enemies).length);for(const name of ['散阵指挥虫','跃袭兽','隔爆甲兽','护甲虫','酸液虫']){await page.locator('.guide-list button').filter({hasText:name}).click();await expect(page.locator('.guide-name h3')).toHaveText(name);}await page.getByRole('button',{name:'关闭怪物图鉴'}).click();await page.getByRole('button',{name:/继续防守/}).click();await page.getByRole('button',{name:/继续 Space/}).click();
 const bounds=await page.locator('canvas').boundingBox();const s=Math.min(bounds!.width/36,bounds!.height/16);const point=(x:number,y:number)=>({x:bounds!.x+(bounds!.width-36*s)/2+x*s,y:bounds!.y+(bounds!.height-16*s)/2+(16-y)*s});
 await page.mouse.click(point(4.5,.5).x,point(4.5,.5).y);await page.keyboard.down('Shift');await page.mouse.click(point(5.5,.5).x,point(5.5,.5).y);await page.keyboard.up('Shift');await expect(page.locator('.bulk-upgrade')).toContainText('合计 160 G');await page.getByRole('button',{name:'统一升级方向 1'}).click();await expect(page.locator('.bulk-upgrade')).toContainText('可升级 0 座');await page.getByRole('button',{name:/操控此塔/}).click();await expect(page.locator('.manual-hint')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.manual-hint')).toHaveCount(0);await page.screenshot({path:`../docs/expansion-${info.project.name}.png`});expect(errors).toEqual([]);
});
test('incident warning is visible before the attack',async({page},info)=>{const e=new Engine(config,1,'incident');e.s.event={kind:'missiles',remaining:6,columns:[1,5,9]};await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname,data=p.endsWith('/config')?config:p.endsWith('/save')?{revision:0,snapshot:e.snapshot()}:p.endsWith('/settings')?{musicVolume:0,sfxVolume:0,reducedMotion:true,tutorialSeen:true}:null;return r.fulfill({status:data?200:204,contentType:'application/json',body:data?JSON.stringify(data):undefined});});await page.goto('/');await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.incident-banner')).toContainText('导弹齐射');await expect(page.locator('.incident-banner')).toContainText('6 秒');await page.screenshot({path:`../docs/incident-${info.project.name}.png`});e.s.event=null;e.s.bossWarning=10;await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.incident-banner')).toContainText('BOSS 接近');});
