import {test,expect} from '@playwright/test';import {Engine} from '../../src/game/engine';import {readFileSync} from 'node:fs';
const config=JSON.parse(readFileSync('../content/game-config.json','utf8'));
test('achievement, locked cinematic, checkpoint reload and giant storm battle',async({page},info)=>{
 await page.addInitScript(()=>{const Base=window.AudioContext;window.AudioContext=class extends Base{createBufferSource(){(window as any).__oceanBuffers=((window as any).__oceanBuffers??0)+1;return super.createBufferSource();}};});
 const e=new Engine(config,123,'reveal-ui');e.startCampaign(4);e.s.tick=610*60;e.s.campaign!.spawned=2;e.s.campaign!.carrierCrashed=true;e.s.campaign!.revealFrame=0;e.s.bossKills=e.s.bossCount=2;e.s.nextEvent=e.s.nextPerk=999999;
 for(let col=8;col<=17;col++)for(let layer=0;layer<6;layer++)e.s.buildings.push({id:e.s.nextEntityId++,type:'wall',branch:-1,spent:45,x:col+.5,y:layer+.5,v:0,hp:720,settled:true,fallId:1,hit:[],cooldown:0});
 const store={snapshot:e.snapshot(),settings:{tutorialSeen:true,musicVolume:.1,sfxVolume:.2,campaignCleared:4,falseEndingAchievement:false}};const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname;if(r.request().method()==='PUT'){if(p.endsWith('/save'))store.snapshot=r.request().postDataJSON().snapshot;if(p.endsWith('/settings'))store.settings=r.request().postDataJSON();}const data=p.endsWith('/config')?config:p.endsWith('/settings')?store.settings:p.endsWith('/save')?{revision:0,snapshot:store.snapshot}:null;return r.fulfill({status:data?200:204,contentType:'application/json',body:data?JSON.stringify(data):undefined});});
 await page.goto('/');await page.getByRole('button',{name:/继续防守/}).click();await expect(page.getByRole('heading',{name:'结束了？'})).toBeVisible();await expect(page.locator('.cinematic-input-lock')).toBeVisible();await page.keyboard.press('Space');await page.keyboard.press('Control+a');await expect(page.getByRole('button',{name:'继续观看过场'})).toHaveCount(0);await expect.poll(()=>store.settings.falseEndingAchievement).toBe(true);await page.screenshot({path:`../docs/reveal-achievement-${info.project.name}.png`});
 await expect.poll(()=>store.snapshot.campaign!.revealFrame??0,{timeout:12000}).toBeGreaterThanOrEqual(240);expect(store.snapshot.tick).toBe(e.s.tick);expect(store.snapshot.gold).toBe(e.s.gold);await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await expect(page.getByRole('heading',{name:'结束了？'})).toHaveCount(0);await expect(page.locator('.cinematic-input-lock')).toBeVisible();await page.screenshot({path:`../docs/reveal-wreck-${info.project.name}.png`});
 await expect(page.locator('.cinematic-input-lock')).toHaveCount(0,{timeout:18000});await expect.poll(()=>store.snapshot.campaign!.storm).toBe(true);expect(store.snapshot.enemies.filter(a=>a.type==='leviathan')).toHaveLength(1);await expect(page.getByRole('progressbar',{name:'深渊潮汐领主生命'})).toHaveAttribute('aria-valuemax',String(config.enemies.leviathan.hp));await page.screenshot({path:`../docs/reveal-storm-${info.project.name}.png`});await page.locator('.battle canvas').hover({position:{x:400,y:250}});await page.waitForTimeout(100);await page.screenshot({path:`../docs/reveal-interaction-${info.project.name}.png`});await page.getByRole('button',{name:'⚙ 设置'}).click();await expect(page.locator('.achievement-record')).toContainText('结束了？');expect(await page.evaluate(()=>(window as any).__oceanBuffers??0)).toBeGreaterThanOrEqual(3);expect(errors).toEqual([]);
});
