import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const config=JSON.parse(readFileSync('../content/game-config.json','utf8'));
test('two players share buildings with separate wallets and owner colors',async({browser},info)=>{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),host=await context.newPage(),guest=await context.newPage();
 const errors:string[]=[];let world:any;
 for(const page of [host,guest]){
  page.on('pageerror',e=>errors.push(e.message));
  page.on('websocket',ws=>ws.on('framereceived',event=>{const m=JSON.parse(String(event.payload));if(m.type==='state')world=m.world;}));
  await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname;return r.fulfill({contentType:'application/json',body:JSON.stringify(p.endsWith('config')?config:p.endsWith('settings')?{tutorialSeen:true}:null)});});
  await page.goto('http://127.0.0.1:8011/?lan=');
  await page.getByLabel('服务地址').fill('http://127.0.0.1:8011');
 }
 await host.getByLabel('你的称呼').fill('蓝队');await host.getByRole('button',{name:'创建房间'}).click();
 const room=host.getByRole('heading',{name:/房间码/});await expect(room).toBeVisible();const code=(await room.innerText()).split(' ').at(-1)!;
 const invite=host.locator('.invite a').first();await expect(invite).toBeVisible();const inviteUrl=new URL((await invite.getAttribute('href'))!);expect(inviteUrl.hostname).not.toBe('127.0.0.1');expect(inviteUrl.port).toBe('8011');expect(inviteUrl.searchParams.get('lan')).toBe(code);
 await guest.getByLabel('你的称呼').fill('金队');await guest.getByPlaceholder('六位房间码').fill(code);await guest.getByRole('button',{name:'加入房间'}).click();
 await expect(host.getByRole('button',{name:'开始合作（2 人）'})).toBeVisible();await host.getByRole('button',{name:'开始合作（2 人）'}).click();
 await expect(guest.locator('canvas')).toBeVisible();
 await expect(host.locator('.tray button').filter({hasText:config.buildings.decoy.name})).toBeEnabled();
 const guestDecoy=guest.locator('.tray button').filter({hasText:config.buildings.decoy.name});await expect(guestDecoy).toBeDisabled();await expect(guestDecoy).toContainText('仅房主可建造');
 await host.bringToFront();if(await host.getByRole('button',{name:'继续战斗',exact:true}).count())await host.getByRole('button',{name:'继续战斗',exact:true}).click();
 await host.locator('.tray button').filter({hasText:config.buildings.wall.name}).click();
 const rect=(await host.locator('canvas').boundingBox())!,scale=Math.min(rect.width/36,rect.height/16),ox=(rect.width-36*scale)/2;
 await host.mouse.click(rect.x+ox+8.5*scale,rect.y+rect.height/2);
 await expect.poll(()=>world?.buildings?.length).toBe(1);
 await expect(host.locator('.bar').first()).toContainText('你的金币 255 G');
 const firstOwner=world.buildings[0].owner;
 // Browser automation can operate the guest without foregrounding it; the host remains active.
 await guest.locator('.tray button').filter({hasText:config.buildings.wall.name}).click();
 const r=(await guest.locator('canvas').boundingBox())!,gs=Math.min(r.width/36,r.height/16);
 await guest.locator('canvas').dispatchEvent('pointerdown',{button:0,pointerId:1,clientX:r.x+(r.width-36*gs)/2+9.5*gs,clientY:r.y+r.height/2});
 await expect.poll(()=>world?.buildings?.length).toBe(2);
 await expect(guest.locator('.bar').first()).toContainText('你的金币 255 G');
 expect(world.buildings[1].owner).not.toBe(firstOwner);expect(world.coop.players[0].gold).toBeCloseTo(world.coop.players[1].gold,1);
 expect(world.coop.players[0].color).not.toBe(world.coop.players[1].color);
 await expect(host.getByRole('region',{name:'联机操作栏'})).toBeVisible();
 await host.getByRole('button',{name:/选择 \/ 自动防御/}).click();
 await expect.poll(()=>world.buildings[0].settled).toBe(true);
 const wall=world.buildings[0];
 await host.mouse.click(rect.x+ox+wall.x*scale,rect.y+(rect.height-16*scale)/2+(16-wall.y)*scale);
 await expect(host.locator('.selection-panel')).toBeVisible();
 await host.getByRole('button',{name:'加入部队 1',exact:true}).click();
 await expect(host.locator('.squad-slot').first()).toContainText('1 座');
 await host.getByRole('button',{name:/吊装位移/}).click();
 await expect(host.locator('.deck-heading')).toContainText('吊装位移');
 await host.locator('.tray button').filter({hasText:config.buildings.wall.name}).click();
 await expect(host.locator('.deck-heading')).toContainText('建造');
 await host.locator('.squad-slot').first().getByRole('button').first().click();
 await expect(host.locator('.deck-heading')).toContainText('手动接管 · 1 座');
 await host.keyboard.press('Escape');
 await expect(host.locator('.deck-heading strong')).toHaveText('自动防御');
 await host.keyboard.press('F1');
 await expect(host.locator('.deck-heading')).toContainText('手动接管 · 1 座');
 await guest.setViewportSize({width:600,height:900});
 expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await guest.screenshot({path:`../docs/lan-toolbar-narrow-${info.project.name}.png`});
 await host.screenshot({path:`../docs/lan-${info.project.name}.png`});expect(errors).toEqual([]);
 await host.getByRole('button',{name:'关闭房间 / 返回首页'}).click();await expect(guest.locator('header')).toContainText(/结束|断开/);
 await context.close();
});
