import {test,expect} from '@playwright/test';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {readFileSync} from 'node:fs';import {Engine} from '../../src/game/engine';
const file=pathToFileURL(resolve('../release/战墙-分享版/战墙-双击即玩.html')).href;
test('offline campaign victory saves unlock progress and can continue the next chapter',async({page})=>{await page.route(/^https?:/,r=>r.abort());await page.goto(file);await expect(page.getByRole('button',{name:'建立新防线'})).toBeEnabled();const config=JSON.parse(readFileSync('../content/game-config.json','utf8')),e=new Engine(config,123,'offline-chapter');e.startCampaign(0);e.s.campaign!.spawned=1;e.s.campaign!.won=true;e.s.bossKills=e.s.bossCount=1;e.s.tick=10000;await page.evaluate(snapshot=>new Promise<void>((resolve,reject)=>{const r=indexedDB.open('warwall-portable-game',1);r.onsuccess=()=>{const db=r.result,tx=db.transaction('state','readwrite');tx.objectStore('state').put({revision:0,snapshot,savedAt:new Date().toISOString(),settings:{musicVolume:0,sfxVolume:0,tutorialSeen:true,campaignCleared:0},runs:[]},'game');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};r.onerror=()=>reject(r.error);}),e.snapshot());await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await page.getByRole('button',{name:/前往 灰烬之城/}).click();await page.getByRole('button',{name:'开始 / 继续战役'}).click();await expect(page.locator('.mission-strip')).toContainText('重燃城市');await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await expect(page.locator('.mission-strip')).toContainText('重燃城市');});
test('single local HTML plays and restores progress and settings without any network',async({page})=>{
 const errors:string[]=[],network:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.route(/^https?:/,r=>r.abort());
 await page.goto(file);await page.getByRole('button',{name:'跳过引导'}).click();await expect(page.getByRole('button',{name:'建立新防线'})).toBeEnabled();await page.getByRole('button',{name:'建立新防线'}).click();await expect(page.locator('.building-card').first()).toBeEnabled();await page.keyboard.press('Digit1');const box=(await page.locator('canvas').boundingBox())!,s=Math.min(box.width/36,box.height/16);await page.mouse.click(box.x+(box.width-36*s)/2+10.5*s,box.y+(box.height-16*s)/2+15.5*s);await page.waitForTimeout(1400);
 await page.getByRole('button',{name:'⚙ 设置'}).click();await page.getByLabel('战局难度',{exact:true}).selectOption('normal');await page.locator('input[type=checkbox]').check();await page.getByRole('button',{name:'完成',exact:true}).click();await page.getByRole('button',{name:'游戏菜单'}).click();await page.getByRole('button',{name:'保存并返回主菜单'}).click();await expect(page.getByRole('button',{name:/继续防守/})).toBeEnabled();await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await expect(page.getByText('模拟已暂停')).toBeVisible();await expect(page.locator('.sector-stats strong').first()).toHaveText('01');await expect(page.locator('.hud')).toContainText('普通');await page.getByRole('button',{name:'⚙ 设置'}).click();await expect(page.locator('input[type=checkbox]')).toBeChecked();expect(errors).toEqual([]);expect(network).toEqual([]);
});
test('portable settlement records history once and clears the matching save',async({page})=>{
 await page.route(/^https?:/,r=>r.abort());await page.goto(file);await expect(page.getByRole('button',{name:'建立新防线'})).toBeEnabled();const config=JSON.parse(readFileSync('../content/game-config.json','utf8')),e=new Engine(config,123,'portable-doomed');e.s.coreHp=1;e.spawn('grunt',false,3.3);
 await page.evaluate(snapshot=>new Promise<void>((resolve,reject)=>{const r=indexedDB.open('warwall-portable-game',1);r.onsuccess=()=>{const db=r.result,tx=db.transaction('state','readwrite');tx.objectStore('state').put({revision:0,snapshot,savedAt:new Date().toISOString(),settings:{musicVolume:0,sfxVolume:0,reducedMotion:true,tutorialSeen:true},runs:[]},'game');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};r.onerror=()=>reject(r.error);}),e.snapshot());
 await page.reload();await page.getByRole('button',{name:/继续防守/}).click();await page.getByRole('button',{name:/继续 Space/}).click();await expect(page.getByText('核心熄灭，意志不灭。')).toBeVisible();await page.waitForTimeout(300);await page.reload();await expect(page.getByRole('button',{name:/继续防守/})).toBeDisabled();await page.getByRole('button',{name:/历史战绩/}).click();await expect(page.locator('.history-table tbody tr')).toHaveCount(1);
});
