/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Save */
        get: operations["get_save_api_v1_save_get"];
        /** Put Save */
        put: operations["put_save_api_v1_save_put"];
        post?: never;
        /** Delete Save */
        delete: operations["delete_save_api_v1_save_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_api_v1_runs_get"];
        put?: never;
        /** Post Run */
        post: operations["post_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Building */
        Building: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Branch */
            branch: number;
            /** Spent */
            spent: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** V */
            v: number;
            /** Hp */
            hp: number;
            /** Settled */
            settled: boolean;
            /** Fallid */
            fallId: number;
            /** Hit */
            hit: number[];
            /** Cooldown */
            cooldown: number;
        };
        /** BuildingConfig */
        BuildingConfig: {
            /** Name */
            name: string;
            /** Cost */
            cost: number;
            /** Hp */
            hp: number;
            /** Impact */
            impact: number;
            /** Interval */
            interval: number;
            /** Range */
            range: number;
            /** Branches */
            branches: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        /** CampaignState */
        CampaignState: {
            /** Timelineversion */
            timelineVersion?: (2 | 3) | null;
            /** Revealframe */
            revealFrame?: number | null;
            /**
             * Carriercrashed
             * @default false
             */
            carrierCrashed: boolean;
            /**
             * Storm
             * @default false
             */
            storm: boolean;
            /** Stage */
            stage: number;
            /**
             * Spawned
             * @default 0
             */
            spawned: number;
            /**
             * Won
             * @default false
             */
            won: boolean;
        };
        /** CarrierParts */
        CarrierParts: {
            /** Hangar */
            hangar: number;
            /** Missiles */
            missiles: number;
            /** Max */
            max: number;
        };
        /** Enemy */
        Enemy: {
            /** Side */
            side?: "left" | null;
            /** Squad */
            squad?: number | null;
            parts?: components["schemas"]["CarrierParts"] | null;
            /** Weakuntil */
            weakUntil?: number | null;
            /**
             * Descent
             * @default false
             */
            descent: boolean;
            /** Special */
            special?: number | null;
            /** Secondary */
            secondary?: number | null;
            /**
             * Attackanim
             * @default 0
             */
            attackAnim: number;
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Hp */
            hp: number;
            /** Maxhp */
            maxHp: number;
            /** Shield */
            shield: number;
            /** Armor */
            armor: number;
            /** Attackscale */
            attackScale: number;
            /** Speedscale */
            speedScale: number;
            /** Reward */
            reward: number;
            /**
             * Elite
             * @enum {string}
             */
            elite: "" | "shield" | "armor" | "brood";
            /** Cooldown */
            cooldown: number;
            /** Slows */
            slows: components["schemas"]["Slow"][];
            /** Skill */
            skill: number;
            /** Summon */
            summon: number;
            /**
             * State
             * @enum {string}
             */
            state: "walk" | "charge" | "dash" | "fuse" | "leap" | "recover" | "burrow" | "erupt" | "exposed" | "rally";
            /** Timer */
            timer: number;
            /** Distance */
            distance: number;
            /** Target */
            target: number;
        };
        /** GameConfig */
        GameConfig: {
            /**
             * Balancerevision
             * @default 1
             */
            balanceRevision: number;
            /**
             * Configversion
             * @constant
             */
            configVersion: 1;
            /** World */
            world: {
                [key: string]: number;
            };
            /** Buildings */
            buildings: {
                [key: string]: components["schemas"]["BuildingConfig"];
            };
            /** Enemies */
            enemies: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Perks */
            perks: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Schedule */
            schedule: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Incident */
        Incident: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "missiles" | "airdrop" | "meteor" | "breach" | "sabotage" | "siege" | "supply";
            /** Remaining */
            remaining: number;
            /** Columns */
            columns: number[];
        };
        /** Projection */
        Projection: {
            /** Owner */
            owner: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Remaining */
            remaining: number;
        };
        /** Run */
        Run: {
            /** Runid */
            runId: string;
            /** Durationticks */
            durationTicks: number;
            /** Kills */
            kills: number;
            /** Bosskills */
            bossKills: number;
            /** Maxthreat */
            maxThreat: number;
            /** Survivalseconds */
            survivalSeconds: number;
            /** Score */
            score: number;
            /** Endedat */
            endedAt: string;
        };
        /** RunRequest */
        RunRequest: {
            /** Runid */
            runId: string;
            /** Durationticks */
            durationTicks: number;
            /** Kills */
            kills: number;
            /** Bosskills */
            bossKills: number;
            /** Maxthreat */
            maxThreat: number;
        };
        /** Runs */
        Runs: {
            /** Items */
            items: components["schemas"]["Run"][];
            /** Bestscore */
            bestScore: number;
        };
        /** SalvageCrate */
        SalvageCrate: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Hp */
            hp: number;
            /** Remaining */
            remaining: number;
            /** Progress */
            progress: number;
            /** Falling */
            falling: boolean;
        };
        /** SaveMeta */
        SaveMeta: {
            /** Revision */
            revision: number;
            /** Savedat */
            savedAt: string;
        };
        /** SaveRequest */
        SaveRequest: {
            /** Expectedrevision */
            expectedRevision: number;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** SaveResource */
        SaveResource: {
            /** Revision */
            revision: number;
            /** Savedat */
            savedAt: string;
            snapshot: components["schemas"]["Snapshot"];
        };
        /** Settings */
        Settings: {
            /**
             * Musicvolume
             * @default 0.3
             */
            musicVolume: number;
            /**
             * Sfxvolume
             * @default 0.7
             */
            sfxVolume: number;
            /**
             * Reducedmotion
             * @default false
             */
            reducedMotion: boolean;
            /**
             * Tutorialseen
             * @default false
             */
            tutorialSeen: boolean;
            /**
             * Campaigncleared
             * @default 0
             */
            campaignCleared: number;
            /**
             * Falseendingachievement
             * @default false
             */
            falseEndingAchievement: boolean;
            /**
             * Layout
             * @default expanded
             * @enum {string}
             */
            layout: "expanded" | "classic";
            /**
             * Background
             * @default city
             * @enum {string}
             */
            background: "city" | "harbor" | "desert" | "snow" | "classic";
        };
        /** Shot */
        Shot: {
            /** Phase */
            phase?: ("warning" | "flight") | null;
            /** Visual */
            visual?: string | null;
            /** Originx */
            originX?: number | null;
            /** Originy */
            originY?: number | null;
            /** Id */
            id: number;
            /** Owner */
            owner: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "mortar" | "bomb" | "cannon" | "arrow" | "bullet" | "rock" | "shockwave" | "laser" | "wreck";
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Remaining */
            remaining: number;
            /** Duration */
            duration: number;
            /** Damage */
            damage: number;
            /** Radius */
            radius: number;
        };
        /** Slow */
        Slow: {
            /** Amount */
            amount: number;
            /** Until */
            until: number;
        };
        /** Snapshot */
        Snapshot: {
            projection?: components["schemas"]["Projection"] | null;
            campaign?: components["schemas"]["CampaignState"] | null;
            /**
             * Testmode
             * @default false
             */
            testMode: boolean;
            /**
             * Leftopened
             * @default false
             */
            leftOpened: boolean;
            /** Nextleft */
            nextLeft?: number | null;
            /** Squads */
            squads?: number[][];
            crate?: components["schemas"]["SalvageCrate"] | null;
            /**
             * Balancerevision
             * @default 1
             */
            balanceRevision: number;
            /**
             * Difficulty
             * @default easy
             * @enum {string}
             */
            difficulty: "easy" | "normal" | "hard";
            /** Nextevent */
            nextEvent?: number | null;
            /**
             * Eventcount
             * @default 0
             */
            eventCount: number;
            /**
             * Eventdebt
             * @default 0
             */
            eventDebt: number;
            event?: components["schemas"]["Incident"] | null;
            /** Schemaversion */
            schemaVersion: number;
            /** Configversion */
            configVersion: number;
            /** Runid */
            runId: string;
            /** Seed */
            seed: number;
            /** Rng */
            rng: number;
            /** Nextentityid */
            nextEntityId: number;
            /** Revision */
            revision: number;
            /** Tick */
            tick: number;
            /** Gold */
            gold: number;
            /** Corehp */
            coreHp: number;
            /** Maxthreat */
            maxThreat: number;
            /** Kills */
            kills: number;
            /** Bosskills */
            bossKills: number;
            /**
             * Alive
             * @constant
             */
            alive: true;
            /** Buildings */
            buildings: components["schemas"]["Building"][];
            /** Enemies */
            enemies: components["schemas"]["Enemy"][];
            /** Shots */
            shots: components["schemas"]["Shot"][];
            /** Spawncredit */
            spawnCredit: number;
            /** Bossrequests */
            bossRequests: number;
            /** Bosswarning */
            bossWarning: number;
            /** Bosscount */
            bossCount: number;
            /** Lastbossdeath */
            lastBossDeath: number;
            /** Nextboss */
            nextBoss: number;
            /** Nextperk */
            nextPerk: number;
            /** Passive */
            passive: number;
            /** Perks */
            perks: {
                [key: string]: number;
            };
            /** Perkqueue */
            perkQueue: number;
            /** Candidates */
            candidates: string[];
            /** Dropcooldown */
            dropCooldown: number;
            /** Commands */
            commands: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameConfig"];
                };
            };
        };
    };
    get_save_api_v1_save_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResource"] | null;
                };
            };
        };
    };
    put_save_api_v1_save_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_save_api_v1_save_delete: {
        parameters: {
            query: {
                runId: string;
                expectedRevision: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    put_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
