import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import config from '../../content/game-config.json';import type {Config} from '../src/game/types';
const make=()=>{const e=new Engine(config as Config,123,'boss-expansion');e.s.difficulty='normal';return e;};const steps=(e:Engine,n:number)=>{for(let i=0;i<n;i++)e.step();};
function building(e:Engine,type:string,x:number,y=.5){const p=e.config.buildings[type],b={id:e.s.nextEntityId++,type,branch:-1,spent:p.cost,x,y,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:100};e.s.buildings.push(b);return b;}
it('sniper cap counts falling towers, prevents queued overspending and frees a slot on death',()=>{const e=make();e.s.gold=2000;for(let i=0;i<19;i++)building(e,'sniper',3.5+i);e.command({type:'drop',kind:'sniper',column:22});e.command({type:'drop',kind:'sniper',column:23});e.step();expect(e.buildingCount('sniper')).toBe(20);expect(e.s.gold).toBe(1810);expect(e.invalid('sniper',23)).toContain('上限');e.s.buildings[0].hp=0;e.s.dropCooldown=0;e.step();expect(e.invalid('sniper',23)).toBe('');});
it('grandfathers old excess snipers without deleting them or allowing additional towers',()=>{const e=make();for(let i=0;i<21;i++)building(e,'sniper',3.5+i);const copy=new Engine(config as Config,1,'',e.snapshot());expect(copy.buildingCount('sniper')).toBe(21);expect(copy.invalid('sniper',12)).toContain('上限');});
it('worm warns first then destroys the entire vertical corridor, sparing other columns and core',()=>{const e=make();for(const x of [9.5,10.5,11.5,14.5])for(let y=.5;y<6;y++)building(e,'wall',x,y);e.s.buildings.find(b=>b.x===10.5)!.spent=999;e.spawn('sandworm',false);e.step();const w=e.s.enemies[0];expect(w.state).toBe('burrow');expect(e.targetable(w)).toBe(false);steps(e,298);expect(e.s.buildings).toHaveLength(24);steps(e,165);expect(w.state).toBe('exposed');expect(e.s.buildings.every(b=>b.x===14.5)).toBe(true);expect(e.s.coreHp).toBe(3000);});
it('worm eruption resumes deterministically and its death stops destruction',()=>{const e=make();for(let y=.5;y<10;y++)building(e,'wall',10.5,y);e.spawn('sandworm',false);steps(e,325);const copy=new Engine(config as Config,1,'',e.snapshot());copy.paused=false;steps(e,80);steps(copy,80);expect(e.snapshot()).toEqual(copy.snapshot());const remaining=e.s.buildings.length;e.s.enemies[0].hp=0;e.step();expect(e.s.buildings.length).toBe(remaining);});
it('queen summons ground units and tempest warns before lightning with one boss at a time',()=>{for(const type of ['queen','tempest']){const e=make();building(e,'wall',10.5);e.spawn(type,false,25);e.spawn('sandworm',false);expect(e.s.enemies).toHaveLength(1);e.s.enemies[0].special=0;e.s.enemies[0].secondary=0;e.step();if(type==='queen')expect(e.s.enemies.filter(a=>!e.config.enemies[a.type].boss)).toHaveLength(4);else expect(e.s.shots.some(s=>s.visual==='lightning'&&s.phase==='warning')).toBe(true);expect(e.s.buildings[0].hp).toBe(config.buildings.wall.hp);}});
it('meteor event emits real falling rocks and breach units consume later spawn budget',()=>{const e=make();e.s.event={kind:'meteor',remaining:1/60,columns:[8,12,16]};e.step();expect(e.s.shots).toHaveLength(3);expect(e.s.shots.every(s=>s.phase==='flight'&&s.visual==='meteor')).toBe(true);const b=make();b.s.event={kind:'breach',remaining:1/60,columns:[8,12,16]};b.step();expect(b.s.enemies).toHaveLength(6);expect(b.s.eventDebt).toBe(6);});
it('boss rotation includes all five boss types',()=>{const seen=[];const e=make();e.s.nextEvent=99999;e.s.nextPerk=99999;for(let i=0;i<5;i++){e.s.enemies=[];e.s.bossCount=i;e.s.bossWarning=.001;e.s.bossRequests=1;e.step();seen.push(e.s.enemies.find(a=>e.config.enemies[a.type].boss)?.type);}expect(seen).toEqual(['beast','carrier','sandworm','queen','tempest']);});
it('hard first boss is always beast, including a restored warning and explicit carrier request',()=>{
 const e=make();e.setDifficulty('hard');e.spawn('carrier',false,35,11);expect(e.s.enemies[0].type).toBe('beast');expect(e.s.enemies[0].y).toBe(config.enemies.beast.height/2);expect(e.s.bossCount).toBe(1);
 e.s.enemies=[];e.spawn('carrier',false);expect(e.s.enemies[0].type).toBe('carrier');
 const fresh=make();fresh.setDifficulty('hard');fresh.s.bossWarning=.001;fresh.s.bossRequests=1;const copy=new Engine(config as Config,1,'',fresh.snapshot());copy.paused=false;copy.step();expect(copy.s.enemies.find(a=>copy.config.enemies[a.type].boss)?.type).toBe('beast');
});
