// Fixed pre-balance numeric fixture for mechanics; balance.test.ts exercises current data.
import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import config from '../../content/balance-v1.json';import type {Config,Difficulty} from '../src/game/types';
const make=()=>new Engine(config as Config,123,'difficulty');const steps=(e:Engine,n:number)=>{for(let i=0;i<n;i++)e.step();};
function build(e:Engine,type:string,x:number,y=.5){const p=e.config.buildings[type],b={id:e.s.nextEntityId++,type,x,y,hp:p.hp,branch:-1,spent:p.cost,v:0,settled:true,fallId:1,hit:[],cooldown:0};e.s.buildings.push(b);return b;}
for(const mode of ['easy','normal','hard'] as Difficulty[])for(const weapon of ['ballista','cannon','mortar','sniper'])it(`${mode} ${weapon} respects wall penetration in actual flight`,()=>{const e=make();e.setDifficulty(mode);build(e,weapon,10.5);for(let y=.5;y<5;y++)build(e,'wall',13.5,y);e.spawn('siege',false,17);const hp=e.s.enemies[0].hp;steps(e,65);expect(e.s.enemies[0].hp<hp).toBe(true);expect(e.s.buildings.filter(b=>b.type==='wall').every(b=>b.hp===650)).toBe(true);});
for(const weapon of ['ballista','cannon','mortar','sniper'])it(`hard ${weapon} passes non-wall friendly buildings`,()=>{const e=make();e.setDifficulty('hard');build(e,weapon,10.5);for(let y=.5;y<5;y++)build(e,'mine',13.5,y);e.spawn('siege',false,17);const hp=e.s.enemies[0].hp;steps(e,65);expect(e.s.enemies[0].hp).toBeLessThan(hp);});
it('sniper fires a persisted bullet and damage waits until impact',()=>{const e=make();build(e,'sniper',5.5);e.spawn('siege',false,28);e.step();expect(e.s.enemies[0].hp).toBe(320);expect(e.s.shots[0].kind).toBe('bullet');const copy=new Engine(config as Config,1,'',e.snapshot());copy.paused=false;steps(e,40);steps(copy,40);expect(e.snapshot()).toEqual(copy.snapshot());expect(e.s.enemies[0].hp).toBe(180);});
it('difficulty preserves enemy damage ratio, scales attacks and survives reload',()=>{const e=make();e.spawn('grunt',false);e.s.enemies[0].hp=30;e.setDifficulty('hard');expect(e.s.enemies[0].hp).toBe(63);expect(e.s.enemies[0].maxHp).toBe(126);expect(e.s.enemies[0].attackScale).toBe(1.6);const copy=new Engine(config as Config,1,'',e.snapshot());expect(copy.s.difficulty).toBe('hard');e.setDifficulty('easy');expect(e.s.enemies[0].hp).toBe(30);});
it('normal and hard increase spawn rate without changing the enemy cap',()=>{const counts=[];for(const d of ['easy','normal','hard'] as Difficulty[]){const e=make();e.setDifficulty(d);steps(e,20*60);counts.push(e.s.enemies.length);}expect(counts[1]).toBeGreaterThan(counts[0]);expect(counts[2]).toBeGreaterThan(counts[1]);});
it('carrier summons escorts and paratroopers before reaching its old hover point',()=>{const e=make();e.spawn('carrier',false,29);const boss=e.s.enemies[0];boss.summon=0;boss.skill=0;boss.secondary=0;e.step();expect(e.s.enemies.filter(a=>a.type==='flyer')).toHaveLength(3);expect(e.s.enemies.some(a=>a.type==='spitter'&&a.descent)).toBe(true);expect(e.s.shots.filter(s=>s.visual==='missile')).toHaveLength(4);expect(e.s.shots.some(s=>s.damage===145&&s.radius===1.7)).toBe(true);});
it('temporary errors expire and do not revive from a save',()=>{const e=make();e.s.gold=0;e.command({type:'drop',kind:'wall',column:5});e.step();expect(e.message).not.toBe('');steps(e,181);expect(e.message).toBe('');e.notify('test');expect(new Engine(config as Config,1,'',e.snapshot()).message).toBe('');});
it('hard frost passes walls and other friendly buildings',()=>{for(const type of ['wall','mine']){const e=make();e.setDifficulty('hard');build(e,'frost',10.5);build(e,type,11.5);e.spawn('grunt',false,13);e.step();expect(e.s.enemies[0].slows.length>0).toBe(true);}});
