import {it,expect} from 'vitest';
import {Engine} from '../src/game/engine';
import config from '../../content/game-config.json';
function add(e:Engine,col:number,branch=-1){const p=e.config.buildings.mine;const b={id:e.s.nextEntityId++,type:'mine',branch,spent:p.cost,x:col+.5,y:.5,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:0};e.s.buildings.push(b);return b;}
it('adding mixed upgraded and stacked mines always increases total without reducing older outputs',()=>{const e=new Engine(config);for(let i=0;i<70;i++){const old=e.s.buildings.map(b=>e.mineIncome(b)),total=e.economy().total,col=i%8,preview=e.minePreview(col),b=add(e,col);expect(e.mineIncome(b)).toBe(preview.actual);expect(e.economy().total-total).toBeCloseTo(preview.rate);expect(e.economy().total).toBeGreaterThan(total);expect(e.s.buildings.slice(0,-1).map(b=>e.mineIncome(b))).toEqual(old);b.branch=i%3-1;}});
it('falling mines reserve rank but produce nothing, and destroyed mines release their tier',()=>{const e=new Engine(config),first=add(e,0),second=add(e,0);const income=e.mineIncome(second);first.settled=false;expect(e.mineIncome(second)).toBe(income);expect(e.economy().count).toBe(1);first.hp=0;expect(e.mineIncome(second)).toBeGreaterThan(income);});
it('totals account for intervals, upgrades, perks and loss and survive save restoration',()=>{const e=new Engine(config);e.s.perks.mining=2;e.s.perks.subsidy=1;for(let i=0;i<10;i++)add(e,i%3,i%3-1);const a=e.economy();expect(a.raw-a.loss).toBeCloseTo(a.actual);expect(a.total).toBeCloseTo(a.actual+a.passive);expect(a.passive).toBe((config.schedule.passiveGold+e.perk('subsidy'))/config.schedule.passiveEvery*60);const restored=new Engine(config,1,'',e.snapshot());expect(restored.economy()).toEqual(a);});
it('a working mine pays the displayed amount and upgrade cannot reduce income',()=>{const e=new Engine(config),b=add(e,10);e.s.nextBoss=e.s.nextEvent=e.s.nextPerk=999999;const before=e.s.gold,n=e.mineIncome(b);e.step();expect(e.s.gold-before).toBe(n);const base=e.mineOutput(b).rate;b.branch=0;expect(e.mineOutput(b).rate).toBeGreaterThanOrEqual(base);b.branch=1;expect(e.mineOutput(b).rate).toBeGreaterThanOrEqual(base);});

it('lord arrival triples displayed and paid mine and passive income, persisting across reload',()=>{const e=new Engine(config);e.startCampaign(4);const b=add(e,10);const before=e.economy(),mine=e.mineIncome(b);e.s.campaign!.revealFrame=720;e.spawn('leviathan',false,12,7);const after=e.economy();expect(after.total).toBeCloseTo(before.total*3);expect(after.raw).toBeCloseTo(before.raw*3);expect(after.loss).toBeCloseTo(before.loss*3);expect(e.mineIncome(b)).toBe(mine*3);const copy=new Engine(config,1,'',e.snapshot());expect(copy.economy()).toEqual(after);e.s.passive=config.schedule.passiveEvery-1/60;e.s.nextEvent=e.s.nextPerk=999999;const gold=e.s.gold;e.step();expect(e.s.gold-gold).toBe(mine*3+(config.schedule.passiveGold+e.perk('subsidy'))*4.5);});

it('only final chapter gets 1.5x from the start, with exact fractional payments and save restore',()=>{const regular=new Engine(config),final=new Engine(config);final.startCampaign(4);const a=add(regular,10),b=add(final,10);expect(final.economy().total).toBeCloseTo(regular.economy().total*1.5);expect(final.mineIncome(b)).toBe(regular.mineIncome(a)*1.5);expect(new Engine(config,1,'',final.snapshot()).economy().total).toBe(final.economy().total);const earlier=new Engine(config);earlier.startCampaign(3);expect(earlier.economyMultiplier).toBe(1);});

it('finale eight-minute boost changes payouts at the exact boundary and does not stack on reload',()=>{const e=new Engine(config);e.startCampaign(4);e.s.campaign!.spawned=1;e.s.bossKills=1;e.s.tick=480*60-1;e.s.nextEvent=e.s.nextPerk=999999;const b=add(e,10),income=e.mineIncome(b),before=e.economy();expect(before.multiplier).toBe(1.5);const gold=e.s.gold;e.step();expect(e.economyMultiplier).toBe(3);expect(e.s.gold-gold).toBe(income*2);expect(e.economy().total).toBeCloseTo(before.total*2);expect(e.minePreview(11).actual).toBeGreaterThan(0);const restored=new Engine(config,1,'',e.snapshot());expect(restored.economy()).toEqual(e.economy());e.s.campaign!.storm=true;expect(e.economyMultiplier).toBe(9);const other=new Engine(config);other.startCampaign(3);other.s.tick=600*60;expect(other.economyMultiplier).toBe(1);const survival=new Engine(config);survival.s.tick=600*60;expect(survival.economyMultiplier).toBe(1);});
