// Fixed pre-balance numeric fixture for mechanics; balance.test.ts exercises current data.
﻿import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import {enemyProjectilePosition} from '../src/game/enemy-projectiles';import type {Config,Building} from '../src/game/types';import config from '../../content/balance-v1.json';
const make=()=>new Engine(config as Config,123,'enemy-test');
function wall(e:Engine,x:number,y=.5){const b:Building={id:e.s.nextEntityId++,type:'wall',branch:-1,spent:40,x,y,v:0,hp:650,settled:true,fallId:1,hit:[],cooldown:0};e.s.buildings.push(b);return b;}
function steps(e:Engine,n:number){for(let i=0;i<n;i++)e.step();}
it('bomb warning releases a physical projectile at the moving owner and hits once',()=>{const e=make(),b=wall(e,10.5);e.spawn('bombardier',false,11);const owner=e.s.enemies[0];owner.cooldown=0;e.step();expect(e.s.shots[0].phase).toBe('warning');expect(b.hp).toBe(650);steps(e,90);const s=e.s.shots[0];expect(s.phase).toBe('flight');expect(Math.abs(s.originX!-owner.x)).toBeLessThan(.1);const start=enemyProjectilePosition(s,0);expect(start.y).toBeCloseTo(9.65);steps(e,60);expect(b.hp).toBe(595);expect(e.s.shots.length).toBe(0);steps(e,30);expect(b.hp).toBe(595);});
it('high-speed bomb sweep hits the first roof instead of tunneling into the core',()=>{const e=make();const b=wall(e,1.5,2.5);e.s.shots.push({id:e.s.nextEntityId++,owner:999,kind:'bomb',phase:'flight',originX:1.5,originY:10,x:1.5,y:0,remaining:1/60,duration:1/60,damage:55,radius:.8});e.step();expect(b.hp).toBe(595);expect(e.s.coreHp).toBe(3000);expect(e.s.shots.length).toBe(0);});
it('boss warnings are cancelled on death but already released bombs remain',()=>{const e=make();e.spawn('carrier',false,18);const owner=e.s.enemies[0];e.s.shots.push({id:e.s.nextEntityId++,owner:owner.id,kind:'laser',phase:'warning',x:1.5,y:0,remaining:1,duration:1,damage:135,radius:.7},{id:e.s.nextEntityId++,owner:owner.id,kind:'bomb',phase:'flight',originX:18,originY:10,x:10,y:0,remaining:.9,duration:.9,damage:55,radius:.8});(e as any).hurtEnemy(owner,99999,'true');expect(e.s.shots.map(s=>s.phase)).toEqual(['flight']);});
it('both bosses telegraph distinct new skills before causing damage',()=>{const e=make();wall(e,7.5);e.spawn('beast',false,9);const a=e.s.enemies[0];a.special=0;a.secondary=0;e.step();expect(e.s.shots.map(s=>s.kind)).toEqual(['shockwave','rock']);expect(e.s.buildings[0].hp).toBe(650);const f=make();wall(f,15.5);f.spawn('carrier',false,18);f.s.enemies[0].special=0;f.s.enemies[0].secondary=0;f.step();expect(f.s.shots.filter(s=>s.kind==='laser').length).toBe(1);expect(f.s.shots.filter(s=>s.visual==='missile').length).toBe(4);expect(f.s.buildings[0].hp).toBe(650);});
it('pause and save restore preserve new cooldowns and physical bomb position',()=>{const e=make();wall(e,15.5);e.spawn('carrier',false,18);e.s.enemies[0].secondary=0;steps(e,80);const restored=new Engine(config as Config,1,'',e.snapshot());const before=restored.snapshot();steps(restored,120);expect(restored.snapshot()).toEqual(before);restored.paused=false;steps(e,100);steps(restored,100);expect(restored.snapshot()).toEqual(e.snapshot());});
it('melee attacks emit distinct impact effects and set the attack pose',()=>{for(const type of ['grunt','runner','siege','beast']){const e=make();const p=e.config.enemies[type];e.spawn(type,false,3+p.width/2);e.step();expect(e.s.enemies[0].attackAnim).toBe(.3);expect(e.effects.some(f=>f.kind.endsWith('Attack'))).toBe(true);}});

