// Fixed pre-balance numeric fixture for mechanics; balance.test.ts exercises current data.
import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import config from '../../content/balance-v1.json';import type {Config} from '../src/game/types';
const make=()=>new Engine(config as Config,123,'expansion');const steps=(e:Engine,n:number)=>{for(let i=0;i<n;i++)e.step();};
function build(e:Engine,type='wall',x=10.5,y=.5){const p=e.config.buildings[type],b={id:e.s.nextEntityId++,type,x,y,hp:p.hp,branch:-1,spent:p.cost,v:0,settled:true,fallId:1,hit:[],cooldown:0};e.s.buildings.push(b);return b;}
it('blast resistance reduces explosions but not arrows',()=>{const e=make();e.spawn('blastbeetle',false,16);const beetle=e.s.enemies[0];e.s.shots.push({id:e.s.nextEntityId++,owner:99,kind:'mortar',x:16,y:.425,remaining:1/60,duration:.8,damage:100,radius:1.3});e.step();expect(beetle.hp).toBeCloseTo(255);});
it('cannon reflection consumes shield and hurts the firing tower only on return',()=>{const e=make(),b=build(e,'cannon');e.spawn('reflector',false,16);e.s.enemies[0].shield=50;e.step();b.cooldown=100;steps(e,22);expect(e.s.shots.some(s=>s.visual==='reflected')).toBe(true);expect(e.s.enemies[0].shield).toBe(0);expect(b.hp).toBe(260);steps(e,70);expect(b.hp).toBeCloseTo(201.5);expect(e.s.shots.length).toBe(0);});
it('broken shields do not reflect mortar shells',()=>{const e=make();e.spawn('reflector',false,16);e.s.enemies[0].shield=0;e.s.shots.push({id:e.s.nextEntityId++,owner:99,kind:'mortar',x:16,y:.425,remaining:1/60,duration:.8,damage:100,radius:1.3});e.step();expect(e.s.enemies[0].hp).toBe(120);expect(e.s.shots).toHaveLength(0);});
it('reflected mortar flight persists and resolves identically after loading',()=>{const e=make(),b=build(e);e.spawn('reflector',false,16);e.s.shots.push({id:e.s.nextEntityId++,owner:b.id,kind:'mortar',x:16,y:.425,remaining:1/60,duration:.8,damage:100,radius:1.3});e.step();expect(e.s.shots[0].visual).toBe('reflected');expect(e.s.enemies[0].shield).toBe(20);const copy=new Engine(config as Config,1,'',e.snapshot());copy.paused=false;steps(e,60);steps(copy,60);expect(copy.snapshot()).toEqual(e.snapshot());expect(b.hp).toBe(585);});
it('marshal spreads nearby followers and stops doing so after death',()=>{const e=make();e.spawn('marshal',false,20);e.spawn('grunt',false,21);e.step();const grunt=e.s.enemies[1];expect(grunt.x).toBe(21);e.s.enemies[0].hp=0;e.step();expect(grunt.x).toBeLessThan(21);});
it('leapers move rapidly then recover without crossing a wall',()=>{const e=make();build(e);e.spawn('leaper',false,12);const a=e.s.enemies[0];a.skill=0;e.step();expect(a.state).toBe('leap');steps(e,40);expect(a.state).toBe('recover');expect(a.x).toBeGreaterThanOrEqual(11.4);});
it('spitters launch physical acid and stop at range',()=>{const e=make(),b=build(e);e.spawn('spitter',false,16);e.step();expect(e.s.enemies[0].x).toBe(16);expect(e.s.shots[0].visual).toBe('acid');expect(b.hp).toBe(650);steps(e,60);expect(b.hp).toBe(626);});
it('boss melee damages adjacent and stacked buildings',()=>{const e=make(),a=build(e),b=build(e,'wall',10.5,1.5);e.spawn('beast',false,11.8);e.step();expect(a.hp).toBeLessThan(650);expect(b.hp).toBeLessThan(650);});
it('events warn before launching and resume deterministically',()=>{const e=make();e.s.nextEvent=0;e.step();expect(e.s.event?.kind).toBe('missiles');expect(e.s.shots).toHaveLength(0);steps(e,100);const copy=new Engine(config as Config,1,'',e.snapshot());copy.paused=false;steps(e,260);steps(copy,260);expect(copy.snapshot()).toEqual(e.snapshot());expect(e.s.shots.filter(s=>s.visual==='missile')).toHaveLength(3);});
it('events defer during boss encounters and pause freezes warnings',()=>{const e=make();e.s.nextEvent=0;e.spawn('beast',false,30);e.step();expect(e.s.event).toBeNull();e.s.enemies=[];e.step();expect(e.s.event).not.toBeNull();e.paused=true;const snapshot=e.snapshot();steps(e,120);expect(e.snapshot()).toEqual(snapshot);});
it('airdrop is interceptable by air towers and landing switches target class',()=>{const e=make();e.s.event={kind:'airdrop',remaining:1/60,columns:[10]};e.step();const a=e.s.enemies[0];expect(a.descent).toBe(true);expect(e.isAir(a)).toBe(true);expect(e.s.eventDebt).toBe(2);const tower=build(e,'anti_air',10.5);a.y=3;e.step();expect(a.hp).toBeLessThan(60);tower.cooldown=100;steps(e,100);expect(a.descent).toBe(false);expect(e.isAir(a)).toBe(false);});
it('manual towers wait for input and obey cooldown',()=>{const e=make(),b=build(e,'ballista');e.spawn('siege',false,16);e.control(b.id);e.step();expect(e.s.shots).toHaveLength(0);e.aim={x:16,y:.55,fire:true};e.step();expect(e.s.shots).toHaveLength(1);e.step();expect(e.s.shots).toHaveLength(1);e.control(0);});
it('bulk upgrade is atomic, deduplicates IDs and preserves damage ratio',()=>{const e=make(),a=build(e),b=build(e,'ballista',11.5);a.hp/=2;e.s.gold=159;e.command({type:'upgradeMany',ids:[a.id,b.id],branch:0});e.step();expect(a.branch).toBe(-1);expect(e.s.gold).toBe(159);e.s.gold=160;e.command({type:'upgradeMany',ids:[a.id,a.id,b.id],branch:0});e.step();expect(e.s.gold).toBe(0);expect(a.hp).toBe(650);expect(b.branch).toBe(0);});
