import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import config from '../../content/game-config.json';
function ready(){const e=new Engine(config,123,'reveal');e.startCampaign(4);e.s.campaign!.spawned=1;e.s.bossKills=e.s.bossCount=1;e.s.nextEvent=e.s.nextPerk=999999;e.s.tick=600*60-1;e.step();return e;}
function frames(e:Engine,n:number){for(let i=0;i<n;i++)e.step();}
function crash(e:Engine){const carrier=e.s.enemies.find(a=>a.type==='carrier')!;(e as any).hurtEnemy(carrier,1e9,'true');for(let i=0;i<600&&!e.cinematic;i++)e.step();expect(e.cinematic).toBe(true);frames(e,600);}
it('10:00 spawns only carrier; its death is insufficient until the wreck hits',()=>{const e=ready();expect(e.s.enemies.map(a=>a.type)).toEqual(['carrier']);expect(e.s.campaign!.spawned).toBe(2);const a=e.s.enemies[0];(e as any).hurtEnemy(a,1e9,'true');e.step();expect(e.cinematic).toBe(false);expect(e.s.shots.some(s=>s.kind==='wreck')).toBe(true);for(let i=0;i<600&&!e.cinematic;i++)e.step();expect(e.s.campaign!.carrierCrashed).toBe(true);expect(e.s.campaign!.revealFrame).toBe(-600);expect(e.s.campaign!.won).toBe(false);});
it('scene freezes combat, gold and commands, cues audio, restores exactly, then spawns one central giant',()=>{const e=ready();crash(e);const gold=e.s.gold,tick=e.s.tick,core=e.s.coreHp;e.command({type:'drop',kind:'wall',column:10});expect(e.s.commands).toHaveLength(0);frames(e,180);expect(e.sounds).toContain('hullCollision');frames(e,60);expect(e.sounds).toContain('oceanSurge');expect([e.s.gold,e.s.tick,e.s.coreHp]).toEqual([gold,tick,core]);const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;frames(e,480);frames(copy,480);expect(copy.snapshot()).toEqual(e.snapshot());expect(e.cinematic).toBe(false);expect(e.s.campaign!.storm).toBe(true);expect(e.s.campaign!.spawned).toBe(3);const giant=e.s.enemies.find(a=>a.type==='leviathan')!;expect([giant.x,giant.y]).toEqual([12,7]);expect(e.s.enemies.filter(a=>a.type==='leviathan')).toHaveLength(1);});
it('central boss is targetable, remains central despite overlapping buildings and victory waits for it',()=>{const e=ready();crash(e);frames(e,720);const p=config.buildings.wall;e.s.buildings.push({id:e.s.nextEntityId++,type:'wall',branch:-1,spent:p.cost,x:12.5,y:.5,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:100});const giant=e.s.enemies.find(a=>a.type==='leviathan')!;e.step();expect(giant.x).toBe(12);expect(e.targetable(giant)).toBe(true);expect(e.s.campaign!.won).toBe(false);(e as any).hurtEnemy(giant,1e9,'true');e.step();expect(e.s.campaign!.won).toBe(true);});
it('dead core and fortress wrecks never trigger the achievement scene',()=>{const e=ready();e.s.coreHp=1;e.s.shots.push({id:e.s.nextEntityId++,owner:999,kind:'wreck',phase:'flight',x:2,y:1,originX:2,originY:1,remaining:.01,duration:1,damage:500,radius:5});e.step();expect(e.s.alive).toBe(false);expect(e.cinematic).toBe(false);const f=ready();f.s.shots.push({id:f.s.nextEntityId++,owner:999,kind:'wreck',visual:'fortress',phase:'flight',x:30,y:0,originX:30,originY:0,remaining:.01,duration:1,damage:10,radius:1});f.step();expect(f.s.campaign!.carrierCrashed).not.toBe(true);expect(f.cinematic).toBe(false);});
it('tower projectiles can damage the giant central hitbox',()=>{const e=ready();crash(e);frames(e,720);const giant=e.s.enemies.find(a=>a.type==='leviathan')!;giant.shield=0;giant.special=giant.secondary=999;const p=config.buildings.sniper;e.s.buildings.push({id:e.s.nextEntityId++,type:'sniper',branch:-1,spent:p.cost,x:5.5,y:.5,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:0});const hp=giant.hp;frames(e,120);expect(giant.hp).toBeLessThan(hp);expect(giant.x).toBe(12);});

it('new aftermath delays discovery four seconds and keeps achievement nine seconds before the wreck moves',()=>{const e=ready();e.s.campaign!.carrierCrashed=true;(e as any).startReveal();const tick=e.s.tick,gold=e.s.gold;frames(e,239);expect(e.s.campaign!.revealFrame).toBe(-361);expect(e.sounds).not.toContain('upgrade');frames(e,1);expect(e.sounds).toContain('upgrade');const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;frames(e,539);frames(copy,539);expect(copy.snapshot()).toEqual(e.snapshot());expect(e.sounds).not.toContain('hullCollision');frames(e,1);expect(e.sounds).toContain('hullCollision');expect([e.s.tick,e.s.gold]).toEqual([tick,gold]);expect(e.s.enemies.some(a=>a.type==='leviathan')).toBe(false);});

it('lord arrival grants gold once and halves deployment cooldowns across saves',()=>{const e=ready();crash(e);frames(e,719);e.s.dropCooldown=1;const p=config.buildings.crane;e.s.buildings.push({id:e.s.nextEntityId++,type:'crane',branch:-1,spent:p.cost,x:5.5,y:.5,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:8});const gold=e.s.gold;e.step();expect(e.s.gold).toBe(gold+1000);expect(e.s.dropCooldown).toBe(.5);expect(e.s.buildings[0].cooldown).toBe(4);expect(e.deploymentSpeed).toBe(2);const copy=new Engine(config,1,'',e.snapshot());expect(copy.s.gold).toBe(e.s.gold);expect(copy.s.dropCooldown).toBe(.5);expect(copy.deploymentSpeed).toBe(2);copy.paused=false;copy.s.dropCooldown=0;copy.command({type:'drop',kind:'wall',column:8});copy.step();expect(copy.s.dropCooldown).toBeCloseTo(config.world.deployCooldown/2-1/60);});
