// Fixed pre-balance numeric fixture for mechanics; balance.test.ts exercises current data.
import {it,expect} from 'vitest';
import {Engine} from '../src/game/engine';import config from '../../content/balance-v1.json';import type {Config,Building} from '../src/game/types';
const make=()=>{const e=new Engine(config as Config,123);e.s.gold=5000;return e;};
const step=(e:Engine,n=1)=>{for(let i=0;i<n;i++)e.step();};
const add=(e:Engine,type:string,x:number,y:number)=>{const p=e.config.buildings[type];const b:Building={id:e.s.nextEntityId++,type,x,y,branch:-1,spent:p.cost,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:0};e.s.buildings.push(b);return b;};
it('bridges extend horizontally from a core anchor and carry a dropped tower',()=>{const e=make();e.command({type:'drop',kind:'bridge',column:3,layer:1});step(e,73);e.command({type:'drop',kind:'bridge',column:4,layer:1});step(e,73);e.command({type:'drop',kind:'sniper',column:4});step(e,140);expect(e.s.buildings.map(b=>b.y)).toEqual([1.5,1.5,2.5]);expect(e.s.buildings.every(b=>b.settled)).toBe(true);});
it('unsupported bridge purchase fails without spending and occupied cells are rejected',()=>{const e=make();const gold=e.s.gold;e.command({type:'drop',kind:'bridge',column:8,layer:4});step(e);expect(e.s.gold).toBe(gold);expect(e.s.buildings.length).toBe(0);expect(e.invalid('bridge',1,1)).toContain('占用');expect(e.invalid('bridge',3,12)).toContain('高度');});
it('severed bridges and their towers collapse; floating cycles never self-support',()=>{const e=make();const root=add(e,'bridge',3.5,1.5);add(e,'bridge',4.5,1.5);add(e,'bridge',5.5,1.5);add(e,'sniper',5.5,2.5);root.hp=0;step(e,120);expect(e.s.buildings.map(b=>b.y)).toEqual([.5,.5,1.5]);expect(e.s.buildings.every(b=>b.hp===e.stats(b).hp)).toBe(true);});
it('an alternate anchor preserves a bridge after one support is lost',()=>{const e=make();const a=add(e,'bridge',3.5,1.5);add(e,'bridge',4.5,1.5);add(e,'wall',5.5,.5);add(e,'wall',5.5,1.5);a.hp=0;step(e,60);expect(e.s.buildings.find(b=>b.type==='bridge')?.y).toBe(1.5);});
it('cannon splash ignores armor, hits clustered ground enemies and excludes flyers',()=>{const e=make();add(e,'cannon',10.5,.5);e.spawn('siege',false,16);e.spawn('siege',false,16.7);e.spawn('flyer',false,16,.5);step(e,30);expect(e.s.enemies.filter(a=>a.type==='siege').map(a=>a.hp)).toEqual([230,230]);expect(e.s.enemies.find(a=>a.type==='flyer')?.hp).toBe(65);});
it('sniper reaches distant targets, respects armor and pierces friendly walls',()=>{const e=make();add(e,'sniper',5.5,.5);e.spawn('siege',false,28);step(e,40);expect(e.s.enemies[0].hp).toBe(180);const blocked=make();add(blocked,'sniper',5.5,.5);add(blocked,'wall',7.5,.5);blocked.spawn('siege',false,28);step(blocked,40);expect(blocked.s.enemies[0].hp).toBe(180);});
it('bridge and cannon state continues deterministically through save restore',()=>{const e=make();add(e,'bridge',3.5,1.5);add(e,'cannon',3.5,2.5);e.spawn('siege',false,10);step(e,4);const loaded=new Engine(config as Config,1,'',e.snapshot());loaded.paused=false;step(e,60);step(loaded,60);expect(loaded.snapshot()).toEqual(e.snapshot());});
