import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import config from '../../content/game-config.json';
const make=()=>{const e=new Engine(config,123,'pressure');e.s.nextBoss=99999;e.s.nextPerk=99999;e.s.nextEvent=99999;return e;};
const steps=(e:Engine,n:number)=>{for(let i=0;i<n;i++)e.step();};
function add(e:Engine,type:string,x:number,y=.5){const p=e.config.buildings[type];const b={id:e.s.nextEntityId++,type,x,y,branch:-1,spent:p.cost,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:100};e.s.buildings.push(b);return b;}
it('mine saturation reduces fleet income and vertical stacking reduces it further',()=>{const e=make(),first=add(e,'mine',3.5);expect(e.mineIncome(first)).toBe(config.buildings.mine.production);for(let i=1;i<12;i++)add(e,'mine',3.5+i);const dispersed=e.mineIncome(first);expect(dispersed).toBeLessThan(config.buildings.mine.production);for(let i=1;i<12;i++){e.s.buildings[i].x=3.5;e.s.buildings[i].y=i+.5;}expect(e.mineIncome(first)).toBeLessThan(dispersed);first.cooldown=0;const gold=e.s.gold,income=e.mineIncome(first);e.step();expect(e.s.gold-gold).toBe(income);});
it('economic strike warns before damaging only mines in selected columns',()=>{const e=make(),m=add(e,'mine',10.5),safe=add(e,'mine',15.5),wall=add(e,'wall',11.5);e.s.event={kind:'sabotage',remaining:6,columns:[10]};steps(e,299);expect(m.hp).toBe(config.buildings.mine.hp);steps(e,62);expect(m.hp).toBeLessThan(config.buildings.mine.hp);expect(safe.hp).toBe(config.buildings.mine.hp);expect(wall.hp).toBe(config.buildings.wall.hp);});
it('meteor starts on-screen over the marked column and hits the roof',()=>{const e=make();const roof=add(e,'wall',10.5);e.s.event={kind:'meteor',remaining:1/60,columns:[10]};e.step();const shot=e.s.shots[0];expect(shot.originX).toBe(10.5);expect(shot.originY).toBe(14);expect(shot.duration).toBeGreaterThanOrEqual(3);steps(e,230);expect(roof.hp).toBeLessThan(config.buildings.wall.hp);});
it('airdrop has reserved capacity and visibly descends even when ordinary spawns hit their cap',()=>{const e=make();for(let i=0;i<180;i++)e.spawn('grunt',false);expect(e.s.enemies.length).toBe(168);e.s.event={kind:'airdrop',remaining:1/60,columns:[10,16,22]};e.step();const drops=e.s.enemies.filter(a=>a.descent);expect(drops.length).toBe(6);expect(drops.every(a=>a.y>11&&a.y<14&&a.x>=10&&a.x<24)).toBe(true);expect(e.s.eventDebt).toBe(6);});
it('long-lived boss no longer starves events and all seven incident kinds rotate',()=>{const e=make();e.spawn('carrier',false);e.s.tick=240*60;e.s.nextEvent=190;e.step();expect(e.s.event?.kind).toBe('supply');const kinds=[];for(let i=0;i<7;i++){const f=make();add(f,'mine',10.5);f.s.nextEvent=0;f.s.eventCount=i;f.step();kinds.push(f.s.event?.kind);}expect(kinds).toEqual(['supply','missiles','airdrop','meteor','sabotage','breach','siege']);});
it('all ranged bosses open before approaching the backline and receive a finite entry shield',()=>{for(const type of ['beast','carrier','queen','tempest']){const e=make();add(e,'wall',5.5);e.spawn(type,false);const boss=e.s.enemies[0];expect(boss.shield).toBeCloseTo(boss.maxHp*.3);steps(e,245);expect(boss.x).toBeGreaterThan(30);expect(e.s.shots.some(s=>s.owner===boss.id)).toBe(true);}});
it('elite invasion adds nine mixed shielded enemies, retains the hard cap and survives save reload',()=>{const e=make();e.s.event={kind:'siege',remaining:3,columns:[10,16,22]};const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;steps(e,182);steps(copy,182);expect(e.snapshot()).toEqual(copy.snapshot());expect(e.s.enemies.length).toBe(9);expect(e.s.enemies.every(a=>a.shield>0)).toBe(true);expect(e.s.enemies.some(a=>a.type==='flyer')).toBe(true);expect(e.s.eventDebt).toBe(0);});
it('late health and spawn pressure exceed the previous curve without unbounded entity counts',()=>{const e=make();expect(e.enemyGrowth(30).hp).toBeCloseTo(11.8);expect(e.enemyGrowth(60).hp).toBeCloseTo(53.2);e.s.tick=1800*60;steps(e,60);expect(e.s.enemies.length).toBeGreaterThanOrEqual(3);expect(e.s.enemies.length).toBeLessThanOrEqual(180);});
it('a full legacy battlefield keeps the invasion pending instead of consuming an invisible event',()=>{const e=make();for(let i=0;i<180;i++)e.spawn('grunt',false,35,undefined,true);e.s.event={kind:'airdrop',remaining:1/60,columns:[10,16,22]};e.step();expect(e.s.event?.kind).toBe('airdrop');expect(e.s.enemies.length).toBe(180);e.s.enemies.splice(0,6);steps(e,61);expect(e.s.event).toBeNull();expect(e.s.enemies.filter(a=>a.descent).length).toBe(6);expect(e.s.enemies.length).toBe(180);});
it('economic event becomes a real elite invasion when there are no mines to strike',()=>{const e=make();e.s.eventCount=4;e.s.nextEvent=0;e.step();expect(e.s.event?.kind).toBe('siege');});
