import {it,expect} from 'vitest';import {Engine} from '../src/game/engine';import config from '../../content/game-config.json';
const make=()=>{const e=new Engine(config,123,'tactics');e.s.nextBoss=99999;e.s.nextEvent=99999;e.s.nextPerk=99999;e.s.gold=2000;return e;};const steps=(e:Engine,n:number)=>{for(let i=0;i<n;i++)e.step();};
function add(e:Engine,type:string,x:number,y=.5){const p=e.config.buildings[type],b={id:e.s.nextEntityId++,type,branch:-1,spent:p.cost,x,y,v:0,hp:p.hp,settled:true,fallId:1,hit:[],cooldown:0};e.s.buildings.push(b);return b;}
it('crane relocation preserves upgraded HP and spending, costs gold and collapses former supports',()=>{const e=make(),crane=add(e,'crane',7.5),wall=add(e,'wall',8.5),roof=add(e,'sniper',8.5,1.5);wall.branch=0;wall.hp=300;wall.spent=150;const before=e.s.gold;e.command({type:'relocate',id:wall.id,column:10});e.step();expect(e.s.gold).toBe(before-35);expect(wall.x).toBe(10.5);expect(wall.settled).toBe(true);expect(wall.y).toBe(.5);expect(wall.branch).toBe(0);expect(wall.hp).toBe(300);expect(wall.spent).toBe(150);expect(crane.cooldown).toBeGreaterThan(29);expect(roof.settled).toBe(false);expect(e.relocationError(roof.id,5)).not.toBe('');steps(e,90);expect(wall.settled).toBe(true);expect(roof.y).toBe(.5);});
it('crane rejects invalid destinations atomically and a relocated building save resumes identically',()=>{const e=make();add(e,'crane',5.5);const b=add(e,'wall',6.5);const before=e.s.gold;e.command({type:'relocate',id:b.id,column:23});e.step();expect(e.s.gold).toBe(before);expect(b.x).toBe(6.5);e.command({type:'relocate',id:b.id,column:8});e.step();const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;steps(e,90);steps(copy,90);expect(e.snapshot()).toEqual(copy.snapshot());});
it('crane places a building directly under a supported bridge and restores the queued exact cell',()=>{const e=make();add(e,'crane',6.5);const mine=add(e,'mine',5.5);mine.cooldown=8;add(e,'wall',8.5);add(e,'wall',8.5,1.5);for(const x of [8.5,9.5,10.5])add(e,'bridge',x,2.5);expect(e.top(9)).toBe(3);e.command({type:'relocate',id:mine.id,column:9,layer:0});const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;e.step();copy.step();expect(e.snapshot()).toEqual(copy.snapshot());expect(mine.x).toBe(9.5);expect(mine.y).toBe(.5);expect(mine.settled).toBe(true);expect(mine.cooldown).toBeCloseTo(8-1/60);expect(e.s.buildings.filter(b=>b.type==='bridge').every(b=>b.y===2.5&&b.settled)).toBe(true);expect(e.s.gold).toBe(1965);});
it('invalid occupied, unsupported, self-supported and core destinations do not consume resources',()=>{const e=make();add(e,'crane',6.5);const b=add(e,'wall',5.5);for(const [column,layer] of [[6,0],[1,0],[9,1],[5,1],[9,12]]){expect(e.relocationError(b.id,column,layer)).not.toBe('');e.command({type:'relocate',id:b.id,column,layer});e.step();expect(e.s.gold).toBe(2000);expect(b.x).toBe(5.5);expect(b.y).toBe(.5);}});
it('interceptor removes a flying projectile before impact, respects cooldown and cannot stop wrecks',()=>{const e=make(),b=add(e,'interceptor',10.5);for(const kind of ['bomb','bomb','wreck'])e.s.shots.push({id:e.s.nextEntityId++,owner:999,kind,phase:'flight',originX:10.5,originY:4,x:10.5,y:0,remaining:3,duration:3,damage:100,radius:1});e.step();expect(e.s.shots.length).toBe(2);expect(e.s.shots.some(s=>s.kind==='wreck')).toBe(true);expect(b.cooldown).toBeGreaterThan(2);e.step();expect(e.s.shots.length).toBe(2);expect(b.hp).toBe(config.buildings.interceptor.hp);});
it('carrier hangar and missile compartments can be destroyed without instantly killing the hull',()=>{const e=make();e.spawn('carrier',false);const a=e.s.enemies[0];a.shield=0;e.partTarget='hangar';(e as any).hurtEnemy(a,a.parts!.max+5,'true');expect(a.parts!.hangar).toBe(0);expect(a.hp).toBeGreaterThan(0);e.partTarget='missiles';(e as any).hurtEnemy(a,a.parts!.max+5,'true');expect(a.parts!.missiles).toBe(0);a.secondary=0;a.summon=0;e.step();expect(e.s.shots.filter(s=>s.visual==='missile')).toHaveLength(0);expect(e.s.enemies.filter(s=>s.type==='flyer')).toHaveLength(1);expect(e.s.enemies.some(s=>s.type==='spitter')).toBe(false);});
it('core exposure increases aimed damage while a sealed core reduces it',()=>{const e=make();e.spawn('carrier',false);const a=e.s.enemies[0];a.shield=0;e.partTarget='core';const hp=a.hp;(e as any).hurtEnemy(a,100,'true');expect(hp-a.hp).toBeCloseTo(65);a.weakUntil=10;const old=a.hp;(e as any).hurtEnemy(a,100,'true');expect(old-a.hp).toBeCloseTo(160);});
it('explicit part targeting prioritizes a carrier in range over a closer flyer',()=>{const e=make();add(e,'anti_air',10.5);e.spawn('carrier',false,14,5);e.spawn('flyer',false,12,3);const carrier=e.s.enemies[0],flyer=e.s.enemies[1];carrier.shield=0;e.partTarget='hangar';const before=carrier.parts!.hangar,hp=flyer.hp;e.step();expect(carrier.parts!.hangar).toBeLessThan(before);expect(flyer.hp).toBe(hp);});
it('carrier death schedules one visible delayed wreck that damages nearby structures after falling',()=>{const e=make(),a=add(e,'wall',10.5),b=add(e,'wall',12.5),safe=add(e,'wall',18.5);e.spawn('carrier',false,10.5,8);const boss=e.s.enemies[0];(e as any).hurtEnemy(boss,999999,'true');(e as any).hurtEnemy(boss,999999,'true');expect(e.s.shots.filter(s=>s.kind==='wreck')).toHaveLength(1);expect(e.s.bossKills).toBe(1);expect(e.s.perkQueue).toBe(1);e.s.perkQueue=0;steps(e,170);expect(a.hp).toBe(config.buildings.wall.hp);const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;steps(e,200);steps(copy,200);expect(e.snapshot()).toEqual(copy.snapshot());expect(a.hp).toBeLessThan(config.buildings.wall.hp);expect(b.hp).toBeLessThan(config.buildings.wall.hp);expect(safe.hp).toBe(config.buildings.wall.hp);expect(e.s.shots.some(s=>s.kind==='wreck')).toBe(false);});
it('high-speed suicide ship warns then sweeps into buildings; shooting it down prevents explosion',()=>{const e=make(),b=add(e,'wall',10.5);e.spawn('suicide_ship',false,30,5);e.step();const ship=e.s.enemies[0];expect(ship.state).toBe('charge');steps(e,80);expect(b.hp).toBe(config.buildings.wall.hp);steps(e,280);expect(b.hp).toBeLessThan(config.buildings.wall.hp);expect(e.s.enemies.some(a=>a.type==='suicide_ship')).toBe(false);const f=make(),safe=add(f,'wall',10.5);f.spawn('suicide_ship',false,11,1);(f as any).hurtEnemy(f.s.enemies[0],999999,'true');f.step();expect(safe.hp).toBe(config.buildings.wall.hp);});
it('suicide ship chooses valuable backline over a nearby costly wall and flies above a low front wall',()=>{const e=make(),wall=add(e,'wall',22.5),mine=add(e,'mine',10.5);wall.spent=9999;mine.spent=300;const tower=add(e,'sniper',17.5);tower.cooldown=100;e.spawn('suicide_ship',false,30,8);e.step();expect(e.s.enemies[0].target).toBe(mine.id);steps(e,320);expect(mine.hp).toBeLessThan(config.buildings.mine.hp);expect(wall.hp).toBe(config.buildings.wall.hp);});
it('suicide ship retargets destroyed facilities with a fresh warning and preserves target on reload',()=>{const e=make(),mine=add(e,'mine',10.5),tower=add(e,'sniper',17.5);mine.spent=400;tower.cooldown=100;e.spawn('suicide_ship',false,30,8);e.step();mine.hp=0;e.step();expect(e.s.enemies[0].target).toBe(tower.id);expect(e.s.enemies[0].timer).toBe(config.enemies.suicide_ship.interval);const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;steps(e,20);steps(copy,20);expect(e.snapshot()).toEqual(copy.snapshot());});
it('supply needs a nearby defended building and awards gold and one perk exactly once',()=>{const e=make();add(e,'wall',20.5);e.s.event={kind:'supply',remaining:1/60,columns:[20]};e.step();expect(e.s.crate?.falling).toBe(true);steps(e,400);expect(e.s.crate?.falling).toBe(false);const copy=new Engine(config,1,'',e.snapshot());copy.paused=false;steps(e,1250);steps(copy,1250);expect(e.snapshot()).toEqual(copy.snapshot());expect(e.s.crate).toBeNull();expect(e.s.perkQueue).toBe(1);expect(e.s.gold).toBeGreaterThanOrEqual(2150);});
it('abandoned supply expires and nearby enemies prevent collection',()=>{const e=make();e.s.crate={x:20.5,y:.6,hp:350,remaining:2,progress:0,falling:false};steps(e,121);expect(e.s.crate).toBeNull();expect(e.s.perkQueue).toBe(0);const f=make();add(f,'wall',20.5);f.s.crate={x:20.5,y:1.6,hp:350,remaining:45,progress:0,falling:false};f.spawn('grunt',false,21.5);steps(f,60);expect(f.s.crate!.progress).toBe(0);expect(f.s.crate!.hp).toBeLessThan(350);});
