import {OceanAudio} from './ocean-audio';
import {Ambience} from './ambience';
export class AudioSystem {
 private ocean:OceanAudio|null=null;
 private ambience:Ambience|null=null;private ctx:AudioContext|null=null;last=-1;private compressor:DynamicsCompressorNode|null=null;
 unlock(){try{if(!this.ctx){this.ctx=new AudioContext();this.compressor=this.ctx.createDynamicsCompressor();this.compressor.threshold.value=-12;this.compressor.ratio.value=5;this.compressor.connect(this.ctx.destination);}void this.ctx.resume();}catch{/* Audio unavailable is nonfatal. */}}
 music(volume:number,running:boolean){if(!this.ctx)return;try{if(!this.ambience)this.ambience=new Ambience(this.ctx);this.ambience.update(volume,running);}catch{}}
 storm(volume:number,active:boolean){if(!this.ctx||!this.compressor)return;try{this.ocean??=new OceanAudio(this.ctx,this.compressor);this.ocean.storm(volume,active);}catch{}}
 play(kind:string,volume:number){if(['hullCollision','oceanSurge','thunder'].includes(kind)){if(this.ctx&&this.compressor&&volume){this.ocean??=new OceanAudio(this.ctx,this.compressor);this.ocean.play(kind,volume);}return;}if(kind==='mechBurst'||kind==='wreckBlast')kind='explosion';const c=this.ctx;if(!c||!volume||c.currentTime-this.last<.045)return;this.last=c.currentTime;if(kind==='alarm'){for(const offset of [0,.3]){const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+offset;o.type='triangle';o.frequency.setValueAtTime(280,t);o.frequency.exponentialRampToValueAtTime(650,t+.2);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,volume*.15),t+.04);g.gain.exponentialRampToValueAtTime(.0001,t+.28);o.connect(g);g.connect(this.compressor!);o.start(t);o.stop(t+.3);o.onended=()=>{o.disconnect();g.disconnect();};}return;}const o=c.createOscillator(),g=c.createGain();o.type=kind==='explosion'?'sawtooth':'triangle';const f:Record<string,number>={drop:180,gold:900,kill:600,upgrade:1000,explosion:150,failure:160,alarm:350};o.frequency.setValueAtTime(f[kind]||250,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,(f[kind]||250)*.5),c.currentTime+.14);g.gain.setValueAtTime(volume*.22,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.18);o.connect(g);g.connect(this.compressor!);o.start();o.stop(c.currentTime+.2);o.onended=()=>{o.disconnect();g.disconnect();};}
 close(){void this.ctx?.close();this.ctx=null;this.ambience=null;this.ocean=null;this.compressor=null;}
}
