import type {Engine} from '../engine';
const colors:Record<string,string>={wall:'#9aab9d',ballista:'#dcba74',mortar:'#e89668',anti_air:'#a8d9cc',mine:'#e6c775',repair:'#90c9a1',frost:'#86c6e6',amplifier:'#baace1'};
export class Renderer {
 ctx:CanvasRenderingContext2D;scale=1;ox=0;oy=0;
 constructor(public canvas:HTMLCanvasElement){this.ctx=canvas.getContext('2d')!;}
 point(clientX:number,clientY:number){const r=this.canvas.getBoundingClientRect();return {x:(clientX-r.left-this.ox)/this.scale,y:16-(clientY-r.top-this.oy)/this.scale};}
 draw(e:Engine,hover:number,kind:string,selected:number,reduced:boolean){const c=this.ctx,rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(this.canvas.width!==Math.round(rect.width*dpr)||this.canvas.height!==Math.round(rect.height*dpr)){this.canvas.width=Math.round(rect.width*dpr);this.canvas.height=Math.round(rect.height*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#101a19';c.fillRect(0,0,rect.width,rect.height);this.scale=Math.min(rect.width/36,rect.height/16);this.ox=(rect.width-36*this.scale)/2;this.oy=(rect.height-16*this.scale)/2;const s=this.scale,X=(x:number)=>this.ox+x*s,Y=(y:number)=>this.oy+(16-y)*s;
 const line=(x:number,y:number,tx:number,ty:number,color:string,width=1)=>{c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(X(x),Y(y));c.lineTo(X(tx),Y(ty));c.stroke();};
 const circle=(x:number,y:number,r:number,color:string,fill=false)=>{c.beginPath();c.arc(X(x),Y(y),r*s,0,Math.PI*2);if(fill){c.fillStyle=color;c.fill();}else{c.strokeStyle=color;c.lineWidth=1;c.stroke();}};
 const label=(text:string,x:number,y:number,color='#8faaa1',size=11)=>{c.font=`${size}px 'Segoe UI', 'Microsoft YaHei', sans-serif`;c.fillStyle=color;c.fillText(text,X(x),Y(y));};
 const bg=c.createLinearGradient(0,Y(16),0,Y(0));bg.addColorStop(0,'#101918');bg.addColorStop(1,'#24332c');c.fillStyle=bg;c.fillRect(X(0),Y(16),36*s,16*s);
 // Deterministic silhouettes: hills, ruined towers and overhead cables.
 c.fillStyle='#1d2a25';c.beginPath();c.moveTo(X(0),Y(0));for(let i=0;i<=36;i++)c.lineTo(X(i),Y(4+Math.sin(i*.5)*1.6+Math.cos(i*1.7)*.5));c.lineTo(X(36),Y(0));c.fill();
 for(let i=0;i<15;i++){const x=i*2.7,h=2+(i*7%5)*.6;c.fillStyle='#17241f';c.fillRect(X(x),Y(h),s*.9,h*s);c.fillRect(X(x-.15),Y(h+.25),s*1.2,s*.2);}
 for(let x=0;x<=36;x++)line(x,0,x,16,x<=24?'#8ba78e0c':'#bb8a6907');for(let y=0;y<=16;y++)line(0,y,36,y,'#8ba78e0c');line(24,0,24,16,'#c19b5544');
 c.fillStyle='#cba86a09';c.fillRect(X(24),Y(16),12*s,16*s);line(0,0,36,0,'#849178',3);label('防 御 建 造 区',.5,15.15,'#718579',10);label('24 / 敌军入侵区 →',25,15.15,'#a78c68',10);
 for(let i=0;i<24;i++)label(String(i+1).padStart(2,'0'),i+.25,.12,'#9cad8360',9);
 // Core: protected reactor housing.
 c.fillStyle='#263a31';c.strokeStyle=e.s.coreHp<=900?'#ee846b':'#b3d59a';c.lineWidth=2;c.fillRect(X(1),Y(2),2*s,2*s);c.strokeRect(X(1)+1,Y(2)+1,2*s-2,2*s-2);circle(2,1,.63,'#bada9560');circle(2,1,.33,'#c8e7a0',true);line(1.2,1,2.8,1,'#d2edaa');line(2,.2,2,1.8,'#d2edaa');label('核心',1.5,2.25,'#c3d5b6',10);
 if(kind&&hover>=0&&hover<24){const invalid=e.invalid(kind,hover),top=e.top(hover),color=invalid?'#ee846b':'#d4dcb0';c.fillStyle=invalid?'#ee846b0c':'#d4dcb00c';c.fillRect(X(hover),Y(16),s,16*s);c.setLineDash([4,5]);line(hover+.5,14.5,hover+.5,top+1,color+'80');c.strokeStyle=color;c.strokeRect(X(hover)+2,Y(top+1)+2,s-4,s-4);c.setLineDash([]);const p=e.config.buildings[kind];if(p.range)circle(hover+.5,top+.5,p.range,color+'30');label(invalid||`${p.name} · ${p.cost} G`,Math.min(hover,19),Math.min(15,top+1.5),color,11);}
 for(const b of e.s.buildings){const p=e.stats(b),color=colors[b.type],x=X(b.x-.5),y=Y(b.y+.5);c.fillStyle='#1c2c27';c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle=b.id===selected?'#f3e7b1':color;c.lineWidth=b.id===selected?2:1;c.strokeRect(x+2,y+2,s-4,s-4);c.fillStyle=color+'18';c.fillRect(x+4,y+4,s-8,s-8);const xx=b.x,yy=b.y;
 if(b.type==='wall'){for(let j=-1;j<=1;j++)line(xx-.35,yy+j*.23,xx+.35,yy+j*.23,color);line(xx,yy-.4,xx,yy+.4,color);}else if(b.type==='ballista'){line(xx-.25,yy-.22,xx+.4,yy+.1,color,3);line(xx+.08,yy-.27,xx+.22,yy+.35,color,2);line(xx-.2,yy-.3,xx,yy+.1,color,2);}else if(b.type==='mortar'){circle(xx,yy-.15,.2,color,true);line(xx,yy-.1,xx+.25,yy+.32,color,5);}else if(b.type==='anti_air'){line(xx-.2,yy-.25,xx+.2,yy+.28,color,2);line(xx+.02,yy-.3,xx+.4,yy+.23,color,2);circle(xx,yy,.17,color);}else if(b.type==='mine'){c.beginPath();c.moveTo(X(xx),Y(yy+.3));c.lineTo(X(xx+.25),Y(yy));c.lineTo(X(xx),Y(yy-.3));c.lineTo(X(xx-.25),Y(yy));c.closePath();c.stroke();}else if(b.type==='repair'){line(xx-.25,yy,xx+.25,yy,color,4);line(xx,yy-.25,xx,yy+.25,color,4);}else if(b.type==='frost'){for(let a=0;a<3;a++){const dx=Math.cos(a*Math.PI/3)*.32,dy=Math.sin(a*Math.PI/3)*.32;line(xx-dx,yy-dy,xx+dx,yy+dy,color,2);}}else{circle(xx,yy,.28,color);circle(xx,yy,.12,color,true);}
 if(b.branch>=0){c.fillStyle='#e2cb8d';c.fillRect(x+s-8,y+4,4,4);}if(b.hp<p.hp||b.id===selected||Math.floor(b.x)===hover){c.fillStyle='#0b1412';c.fillRect(x+2,y-5,s-4,3);c.fillStyle=b.hp<p.hp*.3?'#e98772':color;c.fillRect(x+2,y-5,(s-4)*b.hp/p.hp,3);}if(b.id===selected&&p.range)circle(b.x,b.y,p.range,color+'45');if(e.demolition){const base=e.s.buildings.find(a=>a.id===e.demolition!.id);if(base&&b.x===base.x&&b.y>base.y){c.fillStyle='#f0b86b44';c.fillRect(x,y,s,s);}}}
 for(const e1 of e.s.enemies){const p=e.config.enemies[e1.type],x=X(e1.x),y=Y(e1.y),w=p.width*s,h=p.height*s;const color=p.boss?'#e38d72':e1.elite?'#dcc594':p.air?'#b6a0b7':e1.type==='runner'?'#d9b078':e1.type==='bomber'?'#ed9775':'#b69d8b';c.fillStyle=color;c.strokeStyle=color;c.lineWidth=2;c.beginPath();if(e1.type==='carrier'){c.moveTo(x-w/2,y);c.lineTo(x-w*.3,y-h*.35);c.lineTo(x+w*.3,y-h*.35);c.lineTo(x+w/2,y);c.lineTo(x+w*.2,y+h*.3);c.lineTo(x-w*.2,y+h*.3);}else if(p.air){c.moveTo(x-w*.7,y-h*.3);c.lineTo(x,y+h*.2);c.lineTo(x+w*.7,y-h*.3);c.lineTo(x,y+h*.45);}else if(e1.type==='bomber'){c.arc(x,y,w*.5,0,Math.PI*2);}else{c.moveTo(x-w/2,y+h/2);c.lineTo(x-w*.4,y-h*.2);c.lineTo(x,y-h/2);c.lineTo(x+w*.45,y-h*.25);c.lineTo(x+w/2,y+h/2);}c.closePath();c.fill();c.fillStyle='#23302a';c.fillRect(x-w*.32,y-h*.1,w*.36,Math.max(2,h*.1));if(!p.air){line(e1.x-p.width*.28,e1.y-p.height*.3,e1.x-p.width*.35,e1.y-p.height*.6,color,2);line(e1.x+p.width*.25,e1.y-p.height*.3,e1.x+p.width*.35,e1.y-p.height*.6,color,2);}if(e1.hp<e1.maxHp||p.boss||e1.elite){c.fillStyle='#091410';c.fillRect(x-w/2,y-h/2-7,w,3);c.fillStyle=color;c.fillRect(x-w/2,y-h/2-7,w*e1.hp/e1.maxHp,3);}if(e1.shield>0){circle(e1.x,e1.y,Math.max(p.width,p.height)*.7,'#a0c9e2');}if(e1.elite)label(e1.elite==='shield'?'◇':'▰',e1.x-.2,e1.y+p.height*.5+.4,'#e8d99c',10);if(e1.state==='fuse'||e1.state==='charge'){circle(e1.x,e1.y,e1.state==='fuse'?1.4:1.8,'#ffb884');label(`${e1.state==='fuse'?'自爆':'冲撞'} ${Math.max(0,e1.timer).toFixed(1)}`,e1.x-1,e1.y+1.5,'#ffd0a0',11);}}
 for(const shot of e.s.shots){if(shot.kind==='bomb'){c.fillStyle='#e9926920';c.fillRect(X(shot.x-.5),Y(14),s,14*s);line(shot.x,14,shot.x,0,'#ed9f6d99',2);label(`▼ ${shot.remaining.toFixed(1)}`,shot.x-.45,13.5,'#ffc999',10);}else{circle(shot.x,shot.y,shot.radius,'#dbaf7470');circle(shot.x,shot.y+Math.sin(shot.remaining/shot.duration*Math.PI)*4,.09,'#ffce89',true);}}
 for(const f of e.effects){if(f.kind==='explosion'){circle(f.x,f.y,reduced?.6:(.55-f.life)*3,'#edb57eaa');circle(f.x,f.y,.35,'#ffc89155',true);}else if(f.kind==='frost')circle(f.x,f.y,Math.abs(f.tx-f.x),'#9bdcff55');else if(f.kind==='gold'||f.kind==='kill')label(f.text||'',f.x,f.y+1,'#e3c987',12);else if(f.kind==='dust'){if(!reduced)circle(f.x,f.y-.4,.3,'#b1bd8955');}else if(f.kind==='repair')line(f.x,f.y,f.tx,f.ty,'#93d3a6aa',2);else if(f.kind==='upgrade')circle(f.x,f.y,.7,'#e5d098');else if(f.tx!==f.x||f.ty!==f.y)line(f.x,f.y,f.tx,f.ty,f.kind==='enemyShot'?'#e48d70':f.kind==='anti_air'?'#a9d8d4':'#edd0a3',1.5);}
 }
}
