import {buildingDetails} from './building-details';
import {drawBridge} from './bridge';
import {drawEnemyAttacks} from './enemy-effects';
import {supportedBuildings} from '../systems/support';
import {drawWeapon,drawShell,drawBlast} from './weapons';
import {drawEnemy} from './enemies';
import type {Engine} from '../engine';
const colors:Record<string,string>={bridge:'#b4bf8e',cannon:'#dfa06d',sniper:'#bdd3dd',wall:'#9aab9d',ballista:'#dcba74',mortar:'#e89668',anti_air:'#a8d9cc',mine:'#e6c775',repair:'#90c9a1',frost:'#86c6e6',amplifier:'#baace1'};
export class Renderer {
 ctx:CanvasRenderingContext2D;scale=1;ox=0;oy=0;
 constructor(public canvas:HTMLCanvasElement){this.ctx=canvas.getContext('2d')!;}
 point(clientX:number,clientY:number){const r=this.canvas.getBoundingClientRect();return {x:(clientX-r.left-this.ox)/this.scale,y:16-(clientY-r.top-this.oy)/this.scale};}
 draw(e:Engine,hover:number,kind:string,selected:number,reduced:boolean,hoverLayer=0,selection:number[]=[]){const c=this.ctx,rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(this.canvas.width!==Math.round(rect.width*dpr)||this.canvas.height!==Math.round(rect.height*dpr)){this.canvas.width=Math.round(rect.width*dpr);this.canvas.height=Math.round(rect.height*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#101a19';c.fillRect(0,0,rect.width,rect.height);this.scale=Math.min(rect.width/36,rect.height/16);this.ox=(rect.width-36*this.scale)/2;this.oy=(rect.height-16*this.scale)/2;const s=this.scale,X=(x:number)=>this.ox+x*s,Y=(y:number)=>this.oy+(16-y)*s;
 const line=(x:number,y:number,tx:number,ty:number,color:string,width=1)=>{c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(X(x),Y(y));c.lineTo(X(tx),Y(ty));c.stroke();};
 const circle=(x:number,y:number,r:number,color:string,fill=false)=>{c.beginPath();c.arc(X(x),Y(y),r*s,0,Math.PI*2);if(fill){c.fillStyle=color;c.fill();}else{c.strokeStyle=color;c.lineWidth=1;c.stroke();}};
 const label=(text:string,x:number,y:number,color='#8faaa1',size=11)=>{c.font=`${size}px 'Segoe UI', 'Microsoft YaHei', sans-serif`;c.fillStyle=color;c.fillText(text,X(x),Y(y));};
 const bg=c.createLinearGradient(0,Y(16),0,Y(0));bg.addColorStop(0,'#101918');bg.addColorStop(1,'#24332c');c.fillStyle=bg;c.fillRect(X(0),Y(16),36*s,16*s);
 // Deterministic silhouettes: hills, ruined towers and overhead cables.
 c.fillStyle='#1d2a25';c.beginPath();c.moveTo(X(0),Y(0));for(let i=0;i<=36;i++)c.lineTo(X(i),Y(4+Math.sin(i*.5)*1.6+Math.cos(i*1.7)*.5));c.lineTo(X(36),Y(0));c.fill();
 for(let i=0;i<15;i++){const x=i*2.7,h=2+(i*7%5)*.6;c.fillStyle='#17241f';c.fillRect(X(x),Y(h),s*.9,h*s);c.fillRect(X(x-.15),Y(h+.25),s*1.2,s*.2);}
 for(let x=0;x<=36;x++)line(x,0,x,16,x<=24?'#8ba78e0c':'#bb8a6907');for(let y=0;y<=16;y++)line(0,y,36,y,'#8ba78e0c');line(24,0,24,16,'#c19b5544');
 c.fillStyle='#cba86a09';c.fillRect(X(24),Y(16),12*s,16*s);line(0,0,36,0,'#849178',3);label('防 御 建 造 区',.5,15.15,'#718579',10);label('24 / 敌军入侵区 →',25,15.15,'#a78c68',10);
 for(let i=0;i<24;i++)label(String(i+1).padStart(2,'0'),i+.25,.12,'#9cad8360',9);
 // Core: protected reactor housing.
 c.fillStyle='#263a31';c.strokeStyle=e.s.coreHp<=900?'#ee846b':'#b3d59a';c.lineWidth=2;c.fillRect(X(1),Y(2),2*s,2*s);c.strokeRect(X(1)+1,Y(2)+1,2*s-2,2*s-2);circle(2,1,.63,'#bada9560');circle(2,1,.33,'#c8e7a0',true);line(1.2,1,2.8,1,'#d2edaa');line(2,.2,2,1.8,'#d2edaa');label('核心',1.5,2.25,'#c3d5b6',10);
 if(kind&&hover>=0&&hover<24){const invalid=e.invalid(kind,hover,hoverLayer),top=kind==='bridge'?Math.max(0,Math.min(11,hoverLayer)):e.top(hover),color=invalid?'#ee846b':'#d4dcb0';c.fillStyle=invalid?'#ee846b0c':'#d4dcb00c';c.fillRect(X(hover),Y(16),s,16*s);c.setLineDash([4,5]);line(hover+.5,14.5,hover+.5,top+1,color+'80');c.strokeStyle=color;c.strokeRect(X(hover)+2,Y(top+1)+2,s-4,s-4);c.setLineDash([]);const p=e.config.buildings[kind];if(p.range)circle(hover+.5,top+.5,p.range,color+'30');label(invalid||`${p.name} · ${p.cost} G`,Math.min(hover,19),Math.min(15,top+1.5),color,11);}
 const afterRemoval=e.demolition?supportedBuildings(e.s.buildings.filter(b=>b.id!==e.demolition!.id)):null;for(const b of e.s.buildings){const p=e.stats(b),color=colors[b.type],x=X(b.x-.5),y=Y(b.y+.5);c.fillStyle=b.type==='bridge'?'#00000000':'#1c2c27';c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle=b.id===selected?'#f3e7b1':b.type==='bridge'?'#00000000':color;c.lineWidth=b.id===selected?2:1;c.strokeRect(x+2,y+2,s-4,s-4);c.fillStyle=b.type==='bridge'?'#00000000':color+'18';c.fillRect(x+4,y+4,s-8,s-8);const xx=b.x,yy=b.y;
 if(b.type==='bridge'){drawBridge(c,b,e.s.buildings,X(b.x),Y(b.y),s);}else if(b.type==='wall'){for(let j=-1;j<=1;j++)line(xx-.35,yy+j*.23,xx+.35,yy+j*.23,color);line(xx,yy-.4,xx,yy+.4,color);}else if(['ballista','mortar','anti_air','cannon','sniper'].includes(b.type)){drawWeapon(c,e,b,s,X,Y,reduced);}else if(b.type==='mine'){c.beginPath();c.moveTo(X(xx),Y(yy+.3));c.lineTo(X(xx+.25),Y(yy));c.lineTo(X(xx),Y(yy-.3));c.lineTo(X(xx-.25),Y(yy));c.closePath();c.stroke();}else if(b.type==='repair'){line(xx-.25,yy,xx+.25,yy,color,4);line(xx,yy-.25,xx,yy+.25,color,4);}else if(b.type==='frost'){for(let a=0;a<3;a++){const dx=Math.cos(a*Math.PI/3)*.32,dy=Math.sin(a*Math.PI/3)*.32;line(xx-dx,yy-dy,xx+dx,yy+dy,color,2);}}else{circle(xx,yy,.28,color);circle(xx,yy,.12,color,true);}
 buildingDetails(c,b,p.hp,X(b.x),Y(b.y),s,e.time,reduced);if(selection.includes(b.id)||e.controlled===b.id){c.strokeStyle=e.controlled===b.id?'#8ceaff':'#f6dc96';c.lineWidth=2;c.strokeRect(x,y,s,s);}
 if(b.branch>=0){c.fillStyle='#e2cb8d';c.fillRect(x+s-8,y+4,4,4);}if(b.hp<p.hp||b.id===selected||Math.floor(b.x)===hover){c.fillStyle='#0b1412';c.fillRect(x+2,y-5,s-4,3);c.fillStyle=b.hp<p.hp*.3?'#e98772':color;c.fillRect(x+2,y-5,(s-4)*b.hp/p.hp,3);}if(b.id===selected&&p.range)circle(b.x,b.y,p.range,color+'45');if(e.demolition){const base=e.s.buildings.find(a=>a.id===e.demolition!.id);if(base&&b.id!==base.id&&b.settled&&!afterRemoval?.has(b.id)){c.fillStyle='#f0b86b44';c.fillRect(x,y,s,s);}}}
 for(const e1 of e.s.enemies){const p=e.config.enemies[e1.type],x=X(e1.x),y=Y(e1.y),w=p.width*s,h=p.height*s;const color=p.boss?'#e38d72':e1.elite?'#dcc594':p.air?'#b6a0b7':e1.type==='runner'?'#d9b078':e1.type==='bomber'?'#ed9775':'#b69d8b';drawEnemy(c,e1.type,x,y,w,h,e.time+e1.id*.31,reduced,e1.attackAnim||0,e1.state);if(e1.hp<e1.maxHp||p.boss||e1.elite){c.fillStyle='#091410';c.fillRect(x-w/2,y-h/2-7,w,3);c.fillStyle=color;c.fillRect(x-w/2,y-h/2-7,w*e1.hp/e1.maxHp,3);}if(e1.type==='marshal'){circle(e1.x,e1.y,e.config.schedule.marshalRadius,'#d9b8ff25');}if(e1.descent){c.strokeStyle='#cebca1';c.lineWidth=1;c.beginPath();c.arc(x,y-h*.8,w*.9,Math.PI,Math.PI*2);c.stroke();line(e1.x-.7,e1.y+.7,e1.x,e1.y,'#cebca1');line(e1.x+.7,e1.y+.7,e1.x,e1.y,'#cebca1');}if(e1.shield>0){circle(e1.x,e1.y,Math.max(p.width,p.height)*.7,'#a0c9e2');}if(e1.elite)label(e1.elite==='shield'?'◇':'▰',e1.x-.2,e1.y+p.height*.5+.4,'#e8d99c',10);if(e1.state==='fuse'||e1.state==='charge'){circle(e1.x,e1.y,e1.state==='fuse'?1.4:1.8,'#ffb884');label(`${e1.state==='fuse'?'自爆':'冲撞'} ${Math.max(0,e1.timer).toFixed(1)}`,e1.x-1,e1.y+1.5,'#ffd0a0',11);}}
 for(const shot of e.s.shots){if(['mortar','cannon','arrow','bullet'].includes(shot.kind)){if(shot.kind==='mortar')circle(shot.x,shot.y,shot.radius,'#dbaf7470');const source=e.s.buildings.find(b=>b.id===shot.owner);drawShell(c,{...shot,originX:shot.originX??source?.x,originY:shot.originY??source?.y},s,X,Y,reduced);}}
 drawEnemyAttacks(c,e,s,X,Y,reduced);
 if(e.s.event)for(const col of e.s.event.columns){const air=e.s.event.kind==='airdrop';c.fillStyle=air?'#88cde21c':'#ff89542a';c.fillRect(X(col),Y(16),s,16*s);circle(col+.5,air?2:0,air?.8:e.config.schedule.eventMissileRadius,air?'#a8e0eb':'#ffb878');label((air?'空降':'轰炸')+' '+Math.ceil(e.s.event.remaining),col,3,air?'#a8e0eb':'#ffb878');}
 if(e.controlled){const b=e.s.buildings.find(b=>b.id===e.controlled);if(b){circle(b.x,b.y,e.stats(b).range,'#8ceaff55');line(b.x,b.y,e.aim.x,e.aim.y,'#8ceaff55');circle(e.aim.x,e.aim.y,.3,'#bceeff');line(e.aim.x-.5,e.aim.y,e.aim.x+.5,e.aim.y,'#bceeff');line(e.aim.x,e.aim.y-.5,e.aim.x,e.aim.y+.5,'#bceeff');}}

 for(const f of e.effects){if(f.kind==='summon'){circle(f.x,f.y,1.4,'#a8f0e7');circle(f.x,f.y,.7,'#d3ffff');}else if(f.kind==='reflect'||f.kind==='shieldBreak'){circle(f.x,f.y,.8,'#b3eaff');label(f.kind==='reflect'?'弹道反转':'护盾击破',f.x-.8,f.y+1,'#b3eaff');}else if(f.kind==='sniper'){circle(f.x,f.y,.15,'#e7f7ff');}else if(f.kind==='explosion'){drawBlast(c,X(f.x),Y(f.y),s,f.life,reduced);}else if(f.kind==='frost')circle(f.x,f.y,Math.abs(f.tx-f.x),'#9bdcff55');else if(f.kind==='gold'||f.kind==='kill')label(f.text||'',f.x,f.y+1,'#e3c987',12);else if(f.kind==='dust'){if(!reduced)circle(f.x,f.y-.4,.3,'#b1bd8955');}else if(f.kind==='repair')line(f.x,f.y,f.tx,f.ty,'#93d3a6aa',2);else if(f.kind==='upgrade')circle(f.x,f.y,.7,'#e5d098');else if(!['ballista','mortar','cannon','clawAttack','runnerAttack','beastAttack','siegeAttack','flyerAttack','bossLaser','shockwave','bombRelease'].includes(f.kind)&&(f.tx!==f.x||f.ty!==f.y))line(f.x,f.y,f.tx,f.ty,f.kind==='enemyShot'?'#e48d70':f.kind==='anti_air'?'#a9d8d4':'#edd0a3',1.5);}
 }
}
