import type {Engine} from '../engine';
import {drawEnemy} from './enemies';
import {enemyProjectilePosition} from '../enemy-projectiles';
export function drawTactics(c:CanvasRenderingContext2D,e:Engine,s:number,X:(n:number)=>number,Y:(n:number)=>number,reduced:boolean,hover:number,layer:number){
 const line=(x:number,y:number,tx:number,ty:number,color:string,width=1)=>{c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(X(x),Y(y));c.lineTo(X(tx),Y(ty));c.stroke();};
 const label=(text:string,x:number,y:number,color='#f8cf97')=>{c.fillStyle=color;c.font='11px Microsoft YaHei';c.fillText(text,X(x),Y(y));};
 for(const a of e.s.enemies){if(a.type==='burrow_nest'){label(a.state==='burrow'?`孵化兽破土 ${Math.ceil(a.timer)}s`:`虫巢孵化 ${Math.ceil(Math.max(0,a.summon))}s`,Math.max(1,a.x-2),a.y+2,'#f3d191');if(a.state==='burrow'){c.fillStyle='#e4ab5c28';c.fillRect(X(a.x-1.5),Y(3),s*3,s*3);}}if(a.state==='erupt'&&a.type!=='sandworm'){label('破土中',a.x-.7,a.y+1,'#efc786');}if(a.type==='suicide_ship'&&a.state!=='walk'&&a.state!=='rally'){const target=e.s.buildings.find(b=>b.id===a.target&&b.hp>0)??{x:2,y:1};c.setLineDash([5,4]);line(a.x,a.y,target.x,target.y,'#ff8e6f',2);c.setLineDash([]);label(a.state==='charge'?`自爆冲撞 ${Math.max(0,a.timer).toFixed(1)}s`:'高速冲撞中',Math.min(29,a.x-1),a.y+1.2);}
  if(a.type==='reflector'&&!a.descent&&a.shield>0&&e.commanderFor(a)){c.fillStyle='#7dddec15';c.strokeStyle='#8fe7ed80';c.lineWidth=1.5;c.beginPath();c.arc(X(a.x),Y(a.y),s*(e.config.schedule.shieldCoverRadius??2.6),0,Math.PI*2);c.fill();c.stroke();label('护盾掩护',a.x-1,a.y+3,'#a3edf0');}
  if(a.type==='fortress'&&e.commanderFor(a))label('防空诱饵',a.x-1,a.y+1.8,'#ffcb86');
  if(a.type==='suicide_ship'&&a.state==='rally'){const group=e.s.enemies.filter(b=>b.state==='rally'&&b.squad===a.squad);if(group[0]?.id===a.id)label(`集结 ${group.length}/${e.config.schedule.squadSize??3} · ${Math.ceil(Math.max(0,Math.min(...group.map(b=>b.timer))))}s`,a.x-1,a.y+1.2,'#e1b6fc');const commander=e.s.enemies.find(b=>b.id===a.squad);if(commander){c.setLineDash([2,6]);line(a.x,a.y,commander.x,commander.y,'#dbadf550');c.setLineDash([]);}}
  if(a.type==='carrier'&&a.parts){for(const [i,key] of (['hangar','missiles'] as const).entries()){const x=a.x+(i===0?-.7:.7);c.fillStyle=a.parts[key]>0?'#8ae4ec':'#242c2b';c.fillRect(X(x)-5,Y(a.y)-3,10,6);label(key==='hangar'?'机库':'导弹',x-.5,a.y-.8,a.parts[key]>0?'#91dce3':'#a18579');}if(e.time<(a.weakUntil??0)){c.strokeStyle='#ffda81';c.lineWidth=3;c.beginPath();c.arc(X(a.x),Y(a.y),s*.4,0,Math.PI*2);c.stroke();label('核心暴露 ×1.6',a.x-1.4,a.y+1.8);}}
 }
 for(const shot of e.s.shots){if(shot.kind!=='wreck')continue;const warning=shot.phase==='warning',t=warning?0:Math.max(0,Math.min(1,1-shot.remaining/shot.duration)),p=enemyProjectilePosition(shot,t);c.fillStyle='#ff805025';c.fillRect(X(shot.x-shot.radius),Y(16),shot.radius*2*s,16*s);c.setLineDash([6,4]);line(shot.x-shot.radius,0,shot.x-shot.radius,16,'#ffb476');line(shot.x+shot.radius,0,shot.x+shot.radius,16,'#ffb476');c.setLineDash([]);c.save();c.translate(X(p.x),Y(p.y));c.rotate(reduced?.15:.15+t*.65);drawEnemy(c,shot.visual==='fortress'?'fortress':'carrier',0,0,3.7*s,2*s,e.time,true);c.restore();for(let i=0;i<4;i++){c.fillStyle=i%2?'#ffb55b':'#ffd994';c.beginPath();c.arc(X(p.x+(i-1.5)*.55),Y(p.y+.2+(reduced?.15:Math.sin(e.time*12+i)*.18)),s*.16,0,Math.PI*2);c.fill();}label(warning?`${shot.visual==='fortress'?'堡垒':'母舰'}残骸 ${Math.ceil(shot.remaining)} 秒后坠落`:'残骸坠落 · 大范围爆炸',Math.max(1,Math.min(25,shot.x-3)),3);}
 const box=e.s.crate;if(box){c.fillStyle='#c7ba70';c.strokeStyle='#fff1b0';c.lineWidth=2;c.fillRect(X(box.x-.45),Y(box.y+.4),s*.9,s*.8);c.strokeRect(X(box.x-.45),Y(box.y+.4),s*.9,s*.8);line(box.x-.4,box.y,box.x+.4,box.y,'#5c613f',2);line(box.x,box.y-.35,box.x,box.y+.35,'#5c613f',2);if(box.falling){c.beginPath();c.arc(X(box.x),Y(box.y+.7),s*.75,Math.PI,Math.PI*2);c.stroke();line(box.x-.75,box.y+.7,box.x,box.y+.4,'#f0e3b0');line(box.x+.75,box.y+.7,box.x,box.y+.4,'#f0e3b0');}label(box.falling?'军械箱降落':`回收 ${Math.floor(box.progress)}/20 · ${Math.ceil(box.remaining)}秒`,box.x-1.5,box.y+1.7);}
 if(e.relocating&&hover>=e.minColumn&&hover<24){const error=e.relocationError(e.relocating,hover,layer);c.strokeStyle=error?'#f39680':'#92dbe0';c.setLineDash([4,4]);c.strokeRect(X(hover),Y(layer+1),s,s);c.setLineDash([]);label(error||'点击此格直接移位 · 35 G',Math.min(hover,18),Math.min(15,layer+1.5));}
 for(const f of e.effects){if(f.kind==='intercept'){line(f.x,f.y,f.tx,f.ty,'#a5f9ff',3);label('拦截',f.tx,f.ty+.4,'#b8faff');}if(f.kind==='mechBurst'||f.kind==='wreckBlast'){const total=f.kind==='wreckBlast'?1.5:.9,t=1-f.life/total,size=f.kind==='wreckBlast'?4:1;for(let i=0;i<8;i++){const a=i*Math.PI/4,r=size*(.2+t);c.globalAlpha=Math.max(0,1-t);line(f.x+Math.cos(a)*r*.4,f.y+Math.sin(a)*r*.4,f.x+Math.cos(a)*r,f.y+Math.sin(a)*r,i%2?'#ffac60':'#fff2b7',reduced?2:4);}c.globalAlpha=1;c.strokeStyle='#ffc18b';c.lineWidth=2;c.beginPath();c.ellipse(X(f.x),Y(f.y),s*size*(.3+t),s*size*(.15+t*.4),0,0,Math.PI*2);c.stroke();}}
}
