<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,shallowRef,nextTick} from 'vue';
import bundledConfig from '../../content/game-config.json' with {type:'json'};
import {EVENTS} from './game/incidents';
import EnemyGuide from './components/EnemyGuide.vue';
import {Engine} from './game/engine';import {Renderer} from './game/render/canvas';import {AudioSystem} from './game/render/audio';
import type {Config,World,Difficulty} from './game/types';import {useSession} from './stores/session';import {api,localGet,localPut} from './api/client';import {SaveQueue,validateSnapshot} from './game/persistence';
const portable=import.meta.env.VITE_PORTABLE==='true';
const ui=useSession(),config=shallowRef<Config>(),engine=shallowRef<Engine>(),canvas=ref<HTMLCanvasElement>(),version=ref(0),hover=ref(-1),hoverLayer=ref(0),ready=ref(false),saved=shallowRef<World|null>(null),serverSave=shallowRef<World|null>(null),error=ref(''),busy=ref(false),small=ref(false),duplicate=ref(false),runs=ref<any[]>([]),best=ref(0),dev=import.meta.env.DEV,devType=ref('grunt'),perf=ref({fps:60,ms:0});
const chosenDifficulty=ref<Difficulty>('easy');const difficultyNames={easy:'简单',normal:'普通',hard:'困难'};
const selection=ref<number[]>([]);const group=computed(()=>{void version.value;return engine.value?.upgradeSelection(selection.value,0);});
const dramatic=computed(()=>{void version.value;const e=engine.value;if(!e)return null;if(e.s.event)return {title:EVENTS[e.s.event.kind].title,detail:'距抵达 '+Math.ceil(e.s.event.remaining)+' 秒 · 注意战场标记'};const worm=e.s.enemies.find(a=>a.type==='sandworm'&&a.state==='burrow'&&a.hp>0);if(worm)return {title:'裂地沙虫 / 建筑下方巨震',detail:'距钻出 '+Math.ceil(worm.timer)+' 秒 · 红色通道内建筑将被摧毁'};if(e.s.bossWarning>=0)return {title:'巨型敌军信号 / BOSS 接近',detail:'距抵达 '+Math.ceil(e.s.bossWarning)+' 秒 · 调整阵型、检查防空'};return e.alert.until>e.time?e.alert:null;});
let renderer:Renderer|undefined,raf=0,last=0,acc=0,lastSave=0,ended='',channel:BroadcastChannel|undefined,frames=0,measure=0,measureAt=0,lastAlarm=0;const audio=new AudioSystem();
const saves=new SaveQueue(m=>ui.saveStatus=m,()=>{if(engine.value)engine.value.paused=true;ui.modal='conflict';void refreshServer();},r=>{if(engine.value)engine.value.s.revision=r;});
const state=computed(()=>{void version.value;return engine.value?{...engine.value.s}:undefined;}),selected=computed(()=>{void version.value;const b=engine.value?.s.buildings.find(b=>b.id===ui.selectedId);return b?{...b}:undefined;}),stats=computed(()=>selected.value&&engine.value?.stats(selected.value));
const clock=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const phase=computed(()=>{const t=(state.value?.tick||0)/60%60;return t<35?`强袭将在 ${Math.ceil(35-t)} 秒后到来`:t<50?`强袭进行中 · 剩余 ${Math.ceil(50-t)} 秒`:`缓和阶段 · 强袭倒计时 ${Math.ceil(95-t)} 秒`;});
const warning=computed(()=>{if(!state.value||!config.value)return '';if(dramatic.value)return '';const t=state.value.tick/60;const n=Object.values(config.value.enemies).filter(p=>!p.boss&&p.unlock>t&&p.unlock-t<=15).sort((a,b)=>a.unlock-b.unlock)[0];return n?`${n.name}将在 ${Math.ceil(n.unlock-t)} 秒后加入刷怪池`:state.value.coreHp<=900?'核心生命危急 · 请立即维修':engine.value?.message||'';});
async function refreshServer(){try{const {data,revision}=await api<{revision:number;snapshot:World}>('/save');serverSave.value=data?.snapshot||null;return data?.revision??revision;}catch{return null;}}
async function boot(){error.value='';try{const {data}=await api<Config>('/config');if(data.configVersion!==1||!data.buildings.wall||!data.enemies.carrier)throw Error('配置不兼容');config.value=data;await localPut('config',data);ui.saveStatus=portable?'离线版 · 存档在此浏览器':'存档服务已连接';}catch{config.value=await localGet<Config>('config')||undefined;ui.saveStatus='服务离线 · 使用浏览器缓存';}if(config.value)config.value={...config.value,enemies:{...bundledConfig.enemies,...config.value.enemies},schedule:{...bundledConfig.schedule,...config.value.schedule}};if(!config.value){error.value='未连接本地服务。请先启动 backend，再点击重试连接。';return;}
 try{const {data}=await api<typeof ui.settings>('/settings');ui.settings=data;}catch{const s=await localGet<typeof ui.settings>('settings');if(s)ui.settings=s;}
 const local=await localGet<World>('save'),revision=await refreshServer();if(revision!==null)saves.revision=revision;else saves.revision=local?.revision||0;
 saved.value=serverSave.value;if(local?.alive){const different=serverSave.value&&local.runId!==serverSave.value.runId;const staleBase=revision!==null&&local.revision!==revision&&local.tick>(serverSave.value?.tick??-1);if(different||staleBase){saved.value=local;saves.blocked=true;ui.modal='conflict';}else saved.value=local.tick>=(serverSave.value?.tick??0)?local:serverSave.value;}
 ready.value=true;await submitPending();}
async function saveSettings(){await localPut('settings',{...ui.settings});try{await api('/settings','PUT',{...ui.settings});}catch{ui.saveStatus='设置仅保存在浏览器';}}
function openModal(name:string){stopFire();if(engine.value){engine.value.paused=true;engine.value.demolition=null;}ui.modal=name;audio.unlock();}
function changeDifficulty(ev:Event){const d=(ev.target as HTMLSelectElement).value as Difficulty;chosenDifficulty.value=d;if(engine.value){engine.value.setDifficulty(d);version.value++;void save();}}
function closeModal(){const was=ui.modal;ui.modal='';if(was==='tutorial'&&!ui.settings.tutorialSeen){ui.settings.tutorialSeen=true;void saveSettings();if(engine.value)engine.value.paused=false;}}
async function newGame(){audio.unlock();if(saved.value){ui.modal='overwrite';return;}await startGame();}
async function startGame(){if(!config.value||busy.value)return;busy.value=true;try{if(saved.value)await localPut('backup',saved.value);const e=new Engine(config.value,20260905,crypto.randomUUID());e.setDifficulty(chosenDifficulty.value);e.s.revision=saves.revision;const ok=await saves.save(e.snapshot());if(!ok){error.value='新游戏尚未替换原存档，请恢复服务后重试。';return;}saved.value=e.snapshot();engine.value=e;ended='';lastSave=0;ui.selectedKind='';ui.selectedId=0;selection.value=[];ui.page='game';ui.modal=ui.settings.tutorialSeen?'':'tutorial';e.paused=!ui.settings.tutorialSeen;await nextTick();renderer=new Renderer(canvas.value!);}finally{busy.value=false;}}
async function continueGame(){if(!config.value||!saved.value)return;try{const e=new Engine(config.value,1,'',validateSnapshot(saved.value,config.value));e.s.revision=saves.revision;engine.value=e;selection.value=[];ui.selectedId=0;ui.page='game';ui.modal='';ui.selectedKind='';lastSave=e.s.tick;await nextTick();renderer=new Renderer(canvas.value!);}catch(e){error.value=(e as Error).message;}}
async function save(){if(!engine.value?.s.alive)return false;saved.value=engine.value.snapshot();return saves.save(saved.value);}
async function saveExit(){busy.value=true;try{if(await save()){ui.page='menu';ui.modal='';engine.value=undefined;renderer=undefined;}else if(!saves.blocked)ui.modal='offline';}finally{busy.value=false;}}
function localExit(){ui.page='menu';ui.modal='';engine.value=undefined;renderer=undefined;}
function togglePause(){const e=engine.value;if(e&&e.s.alive&&!ui.modal&&!small.value&&!duplicate.value){e.paused=!e.paused;e.aim.fire=false;e.demolition=null;version.value++;audio.unlock();}}
function selectKind(k:string){if(engine.value?.running&&!ui.modal){ui.selectedKind=ui.selectedKind===k?'':k;ui.selectedId=0;selection.value=[];engine.value.control(0);audio.unlock();}}
function pointer(ev:PointerEvent){if(!renderer)return;const p=renderer.point(ev.clientX,ev.clientY);hover.value=Math.floor(p.x);hoverLayer.value=Math.floor(p.y);if(engine.value)Object.assign(engine.value.aim,p);}
function drop(ev:PointerEvent){audio.unlock();const e=engine.value;if(!e?.running||ui.modal||ev.button!==0||!renderer)return;const p=renderer.point(ev.clientX,ev.clientY);if(e.controlled){Object.assign(e.aim,p,{fire:true});(ev.currentTarget as HTMLElement).setPointerCapture(ev.pointerId);return;}if(ui.selectedKind)e.command({type:'drop',kind:ui.selectedKind,column:Math.floor(p.x),...(ui.selectedKind==='bridge'?{layer:Math.floor(p.y)}:{})});else {const id=e.s.buildings.find(b=>Math.abs(b.x-p.x)<=.5&&Math.abs(b.y-p.y)<=.5)?.id||0;if(ev.shiftKey&&id){selection.value=selection.value.includes(id)?selection.value.filter(x=>x!==id):[...selection.value,id];}else selection.value=id?[id]:[];ui.selectedId=id;}}
function stopFire(){if(engine.value)engine.value.aim.fire=false;}
function control(){if(engine.value&&selected.value){engine.value.control(engine.value.controlled===selected.value.id?0:selected.value.id);selection.value=[selected.value.id];}}
function bulk(branch:number){engine.value?.command({type:'upgradeMany',ids:[...selection.value],branch});}
function cancel(){ui.selectedKind='';engine.value?.control(0);stopFire();}
function upgrade(branch:number){if(selected.value)engine.value?.command({type:'upgrade',id:selected.value.id,branch});}
function demolish(ev:PointerEvent){if(!selected.value||!engine.value?.running)return;(ev.currentTarget as HTMLElement).setPointerCapture(ev.pointerId);engine.value.command({type:'demolish',id:selected.value.id});}
function stopDemolish(){if(engine.value){engine.value.demolition=null;engine.value.s.commands=engine.value.s.commands.filter(c=>c.type!=='demolish');}}
function choose(id:string){engine.value?.choose(id);version.value++;void save();}
function blur(){stopFire();if(ui.page==='game'&&engine.value?.s.alive){engine.value.paused=true;stopDemolish();version.value++;void save();}}
function resize(){small.value=innerWidth<1280||innerHeight<720;if(small.value)blur();}
function keyboard(ev:KeyboardEvent){if(ui.page!=='game'||ui.modal||state.value?.candidates.length||(ev.target as HTMLElement)?.matches('input,select,textarea'))return;if(ev.code==='Escape'){ev.preventDefault();if(ui.selectedKind||engine.value?.controlled)cancel();else togglePause();}else if(ev.code==='KeyE'){control();}else if(ev.code==='Space'){ev.preventDefault();togglePause();}else if('1234567890-'.includes(ev.key)&&ev.key.length===1&&config.value)selectKind(Object.keys(config.value.buildings)['1234567890-'.indexOf(ev.key)]);}
async function history(){openModal('history');try{const {data}=await api<{items:any[];bestScore:number}>('/runs');runs.value=data.items;best.value=data.bestScore;await localPut('runs',data);}catch{const data=await localGet<{items:any[];bestScore:number}>('runs');runs.value=data?.items||[];best.value=data?.bestScore||0;error.value='战绩服务离线，显示浏览器缓存';}}
async function submitPending(){const pending=await localGet<any[]>('pendingRuns')||[];const left=[];for(const r of pending){try{await api('/runs','POST',r);}catch{left.push(r);}}await localPut('pendingRuns',left);if(left.length)ui.saveStatus='结算待提交 · 已保留本地记录';}
async function finish(){const s=engine.value!.s;if(ended===s.runId)return;ended=s.runId;ui.selectedKind='';saved.value=null;await saves.busy;await localPut('save',null);const pending=await localGet<any[]>('pendingRuns')||[];pending.push({runId:s.runId,durationTicks:s.tick,kills:s.kills,bossKills:s.bossKills,maxThreat:s.maxThreat});await localPut('pendingRuns',pending);await submitPending();const revision=await refreshServer();if(revision!==null)saves.revision=revision;}
async function resolveConflict(local:boolean){const r=await refreshServer();if(r===null){error.value='服务仍不可用，无法安全解决冲突';return;}if(local){if(!saved.value)return;await localPut('serverBackup',serverSave.value);saves.revision=r;saves.blocked=false;if(await saves.save(saved.value))ui.modal='';}else{await saves.busy;saves.blocked=false;saves.revision=r;await localPut('backup',saved.value);saved.value=serverSave.value;await localPut('save',saved.value);engine.value=undefined;ui.page='menu';ui.modal='';}}
async function exportSave(){const value=saved.value||await localGet('backup');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download='warwall-save.json';a.click();URL.revokeObjectURL(a.href);}
function frame(now:number){raf=requestAnimationFrame(frame);const dt=Math.min(.25,(now-last)/1000||0);last=now;const e=engine.value;if(e){const begin=performance.now();if(e.running&&!ui.modal&&!small.value&&!duplicate.value){acc+=dt;let n=0;while(acc>=1/60&&n<8){e.step();acc-=1/60;n++;}if(n===8)acc=0;}else acc=0;measure+=performance.now()-begin;frames++;if(now-measureAt>=1000){perf.value={fps:Math.round(frames*1000/(now-measureAt)),ms:measure/Math.max(frames,1)};frames=0;measure=0;measureAt=now;}version.value++;renderer?.draw(e,hover.value,ui.selectedKind,ui.selectedId,ui.settings.reducedMotion,hoverLayer.value,selection.value);audio.music(ui.settings.musicVolume,e.running&&!ui.modal);const sounds=e.sounds.splice(0);if(sounds.length)audio.play(sounds.includes('failure')?'failure':sounds.includes('alarm')?'alarm':sounds.includes('explosion')?'explosion':sounds[sounds.length-1],ui.settings.sfxVolume);if(e.s.coreHp<=900&&e.time-lastAlarm>5&&e.running){lastAlarm=e.time;audio.play('alarm',ui.settings.sfxVolume);}if(e.s.alive&&e.s.tick-lastSave>=900){lastSave=e.s.tick;void save();}if(!e.s.alive&&ended!==e.s.runId)void finish();}else audio.music(0,false);}
function debugSpawn(){const e=engine.value;if(e){if(e.config.enemies[devType.value].boss&&e.s.enemies.some(a=>e.config.enemies[a.type].boss))return;e.spawn(devType.value);version.value++;}}
function debugPerk(){if(engine.value){engine.value.s.nextPerk=engine.value.time;engine.value.paused=false;}}
onMounted(()=>{resize();window.addEventListener('resize',resize);window.addEventListener('blur',blur);window.addEventListener('keydown',keyboard);document.addEventListener('visibilitychange',visibility);channel=new BroadcastChannel('warwall-active');channel.onmessage=ev=>{if(ev.data==='hello')channel?.postMessage('occupied');if(ev.data==='occupied'){duplicate.value=true;blur();}};channel.postMessage('hello');raf=requestAnimationFrame(frame);void boot().catch(e=>error.value=String(e));});
function visibility(){if(document.hidden)blur();}
onUnmounted(()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('blur',blur);window.removeEventListener('keydown',keyboard);document.removeEventListener('visibilitychange',visibility);channel?.close();audio.close();});
</script>

<template>
 <main :class="['app',ui.page,{'reduced-motion':ui.settings.reducedMotion}]">
  <header class="topbar"><a class="brand" @click="ui.page==='game'?openModal('pause'):null"><span class="brand-mark">▥</span> 战墙 <small>WARWALL</small></a><div class="top-center"><span class="live-dot"></span> {{ui.page==='game'?'防御指挥终端 / SECTOR 01':'单机无限生存 / ENDLESS DEFENSE'}}</div><button class="text-button" @click="openModal('settings')">⚙ 设置</button></header>
  <template v-if="ui.page==='menu'">
   <section class="menu-content"><div class="menu-copy"><div class="eyebrow"><span></span> 最后防线 · 01</div><h1>筑起高墙。<br>守住<span>最后的光。</span></h1><p class="intro">从天而降的堡垒，无休无止的进攻。<br>建造、发展、重构防线，让核心再多跳动一秒。</p><label class="difficulty-choice">战局难度 <select v-model="chosenDifficulty" aria-label="新局难度"><option v-for="(name,id) in difficultyNames" :value="id">{{name}}</option></select><small>{{chosenDifficulty==='hard'?'困难：仅子弹穿城墙；箭矢、炮弹可穿其他友方建筑。':'简单 / 普通：子弹、箭矢、炮弹穿透全部友方建筑。'}}</small></label><div class="menu-actions"><button class="primary" :disabled="!ready||busy" @click="newGame">{{busy?'正在创建…':'建立新防线'}} <span>↗</span></button><button :disabled="!ready||!saved" @click="continueGame">继续防守 <span>{{saved?clock(saved.tick/60):'暂无存档'}}</span></button></div><div class="menu-links"><button :disabled="!config" @click="openModal('bestiary')">怪物图鉴 ↗</button><button @click="history">历史战绩 ↗</button><button @click="openModal('tutorial')">操作说明 ↗</button></div><div class="status"><span class="live-dot"></span>{{ui.saveStatus}}</div><p v-if="error" class="error">{{error}} <button @click="boot">重试连接</button><button v-if="saved" @click="exportSave">导出存档</button></p></div>
   <div class="fortress-art" aria-label="工业堡垒插画"><div class="art-grid"></div><div class="art-title">防线档案 <span>WW—001</span></div><div class="moon"></div><div class="far-city"><i v-for="n in 14" :key="n" :style="{height:(25+n*17%90)+'px'}"></i></div><div class="tower t1"><div class="gun"></div><b>➶</b><b>▥</b><b>▥</b></div><div class="tower t2"><div class="gun"></div><b>◒</b><b>◎</b><b>▥</b><b>▥</b><b>▥</b></div><div class="tower t3"><b>⌁</b><b>▥</b></div><div class="reactor"><span>✧</span><small>CORE / ONLINE</small></div><div class="ground"></div><div class="art-tag"><span class="live-dot"></span> 核心在线 <strong>100%</strong></div><div class="art-bottom">重力搭建 / 持续生存 <span>36 × 16</span></div></div>
   </section><footer><span>每一次坍塌，都是重建的开始。</span><span>V1.0 <i>•</i> 本地运行，无需账号</span></footer>
  </template>
  <template v-else-if="state && engine && config">
   <section class="hud"><div class="hud-item gold"><small>可用金币</small><strong>◇ {{state.gold}} <em>G</em></strong></div><div class="hud-item core"><small>核心完整度 <span>{{Math.ceil(state.coreHp/config.world.coreHp*100)}}%</span></small><strong>{{Math.ceil(state.coreHp)}} <em>/ {{config.world.coreHp}}</em></strong><div class="meter"><i :style="{width:state.coreHp/config.world.coreHp*100+'%'}"></i></div></div><div class="hud-item"><small>生存时间</small><strong>{{clock(state.tick/60)}}</strong></div><div class="hud-item"><small>{{difficultyNames[state.difficulty||'easy']}} · 威胁等级</small><strong><em>LV.</em> {{state.maxThreat.toString().padStart(2,'0')}}</strong></div><div class="assault"><span :class="{'hot':state.tick/60%60>=35&&state.tick/60%60<50}">◈ {{phase}}</span><small>击杀 {{state.kills}} · Boss {{state.bossKills}}</small></div><button class="pause-button" @click="togglePause">{{engine.paused?'▶ 继续':'Ⅱ 暂停'}} <kbd>Space</kbd></button><button class="icon-button" title="游戏菜单" aria-label="游戏菜单" @click="openModal('pause')">☰</button></section>
   <section class="battle-layout"><div class="battle"><div class="battle-label"><span>战区 01 <i>/</i> 灰烬边境</span><span>{{ui.selectedKind?'投放模式 · 右键取消':'指挥模式 · 点击建筑查看详情'}}</span></div><canvas ref="canvas" @pointermove="pointer" @pointerleave="hover=-1" @pointerdown="drop" @pointerup="stopFire" @pointercancel="stopFire" @lostpointercapture="stopFire" @contextmenu.prevent="cancel"></canvas><div v-if="dramatic" class="incident-banner" role="status"><small>紧急战术通告 / WARNING</small><strong>{{dramatic.title}}</strong><span>{{dramatic.detail}}</span></div><div v-if="engine.controlled" class="manual-hint">手动操控 · 指向敌人并按住左键开火 · E / 右键退出</div><div v-if="warning" class="warning">△ {{warning}}</div><div v-if="engine.paused&&!ui.modal&&!state.candidates.length&&state.alive" class="paused-label"><strong>模拟已暂停</strong><span>按 Space 或点击右上角继续</span></div><div class="battle-caption"><span>↓ 普通建筑投放 · 桥梁水平铺设 · 无坠落损伤</span><span v-if="dev">{{perf.fps}} FPS / {{perf.ms.toFixed(2)}} ms</span><span v-else>固定步长 60 Hz</span></div></div>
    <aside class="details"><div class="section-label">建筑情报 <span>INSPECT</span></div><div v-if="selection.length>1 && group" class="bulk-upgrade"><b>已选择 {{selection.length}} 座 · 可升级 {{group.buildings.length}} 座</b><p>按各建筑对应分支统一升级 · 合计 {{group.cost}} G</p><button v-for="i in [0,1]" :disabled="!engine.running||!group.buildings.length||state.gold<group.cost" @click="bulk(i)">统一升级方向 {{i+1}}</button><small v-for="b in group.buildings" :key="b.id">{{config.buildings[b.type].name}}：{{config.buildings[b.type].branches.map(p=>p.name).join(' / ')}}<br></small></div><template v-if="selected && stats"><button v-if="['ballista','mortar','cannon','sniper','anti_air','frost'].includes(selected.type)" :disabled="!selected.settled" @click="control">{{engine.controlled===selected.id?'退出操控':'操控此塔'}} · E</button><div class="detail-icon">{{stats.icon}}</div><h2>{{stats.name}}</h2><p>{{stats.description}}</p><div class="detail-hp">结构生命 <strong>{{Math.ceil(selected.hp)}} / {{Math.ceil(stats.hp)}}</strong></div><div class="meter"><i :style="{width:selected.hp/stats.hp*100+'%'}"></i></div><dl><dt>当前状态</dt><dd>{{selected.settled?'已落稳 · 工作中':'下落中 · 功能冻结'}}</dd><dt>累计投入</dt><dd>{{selected.spent}} G</dd><dt>有效范围</dt><dd>{{stats.range}} 格</dd></dl><div class="section-label">分支升级 <span>{{selected.branch>=0?'已完成':'二选一'}}</span></div><template v-if="selected.branch<0"><button v-for="(branch,i) in config.buildings[selected.type].branches" :key="i" class="upgrade" :disabled="!engine.running||!selected.settled||state.gold<stats.upgradeCost" @click="upgrade(i)"><b>{{branch.name}} <span>{{stats.upgradeCost}} G</span></b><small>{{Object.entries(branch).filter(([k])=>k!=='name').map(([k,v])=>({hp:'生命',damage:'伤害',interval:'间隔',range:'范围',production:'产量',radius:'爆炸半径',slow:'减速',slowDuration:'减速持续',boost:'增幅',thorns:'反伤'}[k]||k)+' '+v).join(' · ')}}</small></button></template><p v-else>已选择：{{stats.name}}</p><button class="demolish" :disabled="!engine.running||!selected.settled" @pointerdown="demolish" @pointerup="stopDemolish" @pointercancel="stopDemolish" @lostpointercapture="stopDemolish"><i :style="{width:(engine.demolition?.id===selected.id?engine.demolition.elapsed*100:0)+'%'}"></i><span>按住 1 秒拆除 <b>+{{engine.refund(selected)}} G</b></span></button><small class="muted">回收金额随当前生命变化；失去全部支撑的桥段及上层建筑会重新下落。</small></template><template v-else><div class="empty-icon">⌖</div><h3>{{ui.selectedKind?config.buildings[ui.selectedKind].name:'选择你的防线'}}</h3><p>{{ui.selectedKind?config.buildings[ui.selectedKind].description:'点击建筑查看状态；Shift + 点击多选统一升级。选中防御塔后按 E 手动操控。'}}</p><div class="tip"><b>指挥官提示</b><p>城墙在前，火力居高。<br>矿场提供长期收入，防空塔守护天空。</p></div><div class="sector-stats"><span>建筑数量</span><strong>{{state.buildings.length.toString().padStart(2,'0')}}</strong><span>敌军信号</span><strong>{{state.enemies.length.toString().padStart(2,'0')}}</strong></div></template></aside></section>
   <section class="build-tray"><div class="tray-heading"><span>建造序列 <small>选择建筑，然后点击目标列投放</small></span><span>{{state.dropCooldown>0?'吊装就绪倒计时 '+state.dropCooldown.toFixed(1)+'s':'● 吊装系统就绪'}}</span></div><div class="building-cards"><button v-for="(p,k,i) in config.buildings" :key="k" :class="['building-card',{active:ui.selectedKind===k,unaffordable:state.gold<p.cost}]" :disabled="!engine.running||!!ui.modal||engine.buildingCount(String(k))>=engine.buildingLimit(String(k))" :title="p.limit?'最多 '+engine.buildingLimit(String(k))+' 座（含下落中）':''" @click="selectKind(String(k))"><kbd>{{'1234567890-'[i]}}</kbd><span class="building-icon">{{p.icon}}</span><div><strong>{{p.name}}</strong><small>{{p.cost}} <em>G</em><span v-if="p.limit"> · {{engine.buildingCount(String(k))}}/{{engine.buildingLimit(String(k))}}</span></small></div></button></div></section>
   <div class="game-footer"><span>{{ui.saveStatus}}</span><span><kbd>1—9 / 0 / -</kbd> 选建筑 <i>·</i> <kbd>右键</kbd> 取消 <i>·</i> <kbd>Space</kbd> 暂停</span></div>
   <details v-if="dev" class="dev-tools"><summary>开发测试</summary><select v-model="devType"><option v-for="(p,k) in config.enemies" :value="k">{{p.name}}</option></select><button @click="debugSpawn">生成敌人</button><button @click="debugPerk">触发强化</button><button @click="engine.s.coreHp=0;engine.s.alive=false">测试结算</button></details>
  </template>
  <div v-if="ui.modal || state?.candidates.length || state&&!state.alive || small || duplicate" class="overlay">
   <section class="dialog" :class="{'wide':ui.modal==='history'||ui.modal==='bestiary'||state?.candidates.length}">
    <template v-if="small"><div class="eyebrow">调整显示窗口</div><h2>需要更宽阔的战场</h2><p>请将浏览器窗口调整至至少 1280 × 720，或缩小浏览器缩放比例。模拟已暂停。</p></template>
    <template v-else-if="duplicate"><h2>已有指挥终端在线</h2><p>检测到另一个游戏标签页。请关闭本页，返回已有页面继续，避免存档冲突。</p></template>
    <template v-else-if="ui.modal==='conflict'"><h2>选择要保留的防线</h2><p>检测到不同存档或版本冲突，模拟已暂停。选择前将保留被替换存档的浏览器备份。</p><button @click="resolveConflict(true)">保留浏览器存档 · {{clock((saved?.tick||0)/60)}}</button><button @click="resolveConflict(false)">采用服务器存档 · {{clock((serverSave?.tick||0)/60)}}</button><button @click="exportSave">导出浏览器 JSON</button><p class="error">{{error}}</p></template>
    <template v-else-if="state && !state.alive && ui.page==='game'"><div class="eyebrow">防线失守 / SIGNAL LOST</div><h2>核心熄灭，意志不灭。</h2><p>你的堡垒坚持了 {{clock(state.tick/60)}}。下一次，筑得更坚固。</p><div class="result-score">{{Math.floor(state.tick/60)*10+state.kills*5+state.bossKills*500}}<small>本局得分</small></div><div class="result-grid"><span>击杀<strong>{{state.kills}}</strong></span><span>Boss 击杀<strong>{{state.bossKills}}</strong></span><span>最高威胁<strong>{{state.maxThreat}}</strong></span></div><button class="primary" @click="startGame">再次部署 ↗</button><button @click="localExit">返回主菜单</button><small>{{ui.saveStatus}}</small><button v-if="ui.saveStatus.includes('待提交')" @click="submitPending">重试提交战绩</button></template>
    <template v-else-if="state?.candidates.length && !ui.modal"><div class="eyebrow">战地补给 / FIELD UPGRADE</div><h2>让防线更进一步。</h2><p>选择一项强化，立即作用于本局防线。模拟已暂停。</p><div class="perk-cards"><button v-for="id in state.candidates" :key="id" @click="choose(id)"><span>✧</span><h3>{{config?.perks[id]?.name||'应急补给'}}</h3><p>{{config?.perks[id]?.description||'+100 金币'}}</p><small>当前 {{state.perks[id]||0}} 层 · 点击获得 →</small></button></div></template>
    <template v-else-if="ui.modal==='overwrite'"><h2>建立新的防线？</h2><p>已有 {{clock((saved?.tick||0)/60)}} 的进行中存档。新游戏成功保存后将替换它，原存档会保留浏览器备份。</p><button class="primary" :disabled="busy" @click="startGame">确认新游戏</button><button @click="closeModal">保留原防线</button><p class="error">{{error}}</p></template>
    <template v-else-if="ui.modal==='pause'"><div class="eyebrow">指挥暂停</div><h2>防线等待你的命令。</h2><button class="primary" @click="closeModal();togglePause()">继续防守</button><button :disabled="busy" @click="saveExit">{{busy?'正在保存…':'保存并返回主菜单'}}</button><button @click="openModal('settings')">设置</button><button @click="openModal('tutorial')">操作说明</button><small>{{ui.saveStatus}}</small></template>
    <template v-else-if="ui.modal==='offline'"><h2>本地副本已保留</h2><p>{{ui.saveStatus}}。当前进度仅保存在此浏览器，尚未写入后端数据库。</p><button class="primary" @click="localExit">保留浏览器存档并返回</button><button @click="saveExit">重试保存</button><button @click="closeModal">留在战场</button></template>
    <template v-else-if="ui.modal==='bestiary' && config"><EnemyGuide :config="config" @close="closeModal" /></template>
    <template v-else-if="ui.modal==='settings'"><div class="eyebrow">系统设置</div><h2>你的指挥环境。</h2><label class="difficulty-choice">{{engine?'当前战局难度':'新局难度'}}<select :value="engine?.s.difficulty||chosenDifficulty" aria-label="战局难度" @change="changeDifficulty"><option v-for="(name,id) in difficultyNames" :value="id">{{name}}</option></select><small>普通：敌人生命 ×1.45 / 伤害 ×1.25 / 数量速率 ×1.35。困难：×2.1 / ×1.6 / ×1.7。切换立即生效，已发射弹体保留原伤害。狙击塔上限：所有难度均为 20 座；切换后超限的已有塔保留。怪物与 Boss 每分钟持续增强，第 10 分钟后增长加快。</small><strong>困难仅子弹穿城墙，箭矢与炮弹穿过其他建筑；简单、普通穿透全部友方建筑。敌方及反弹弹体不享受穿透。</strong></label><label class="setting">背景音景 <span>{{Math.round(ui.settings.musicVolume*100)}}%</span><input v-model.number="ui.settings.musicVolume" type="range" min="0" max="1" step=".05" @input="audio.unlock();saveSettings()"></label><label class="setting">战斗音效 <span>{{Math.round(ui.settings.sfxVolume*100)}}%</span><input v-model.number="ui.settings.sfxVolume" type="range" min="0" max="1" step=".05" @input="audio.unlock();saveSettings()"></label><button @click="audio.unlock();audio.play('explosion',ui.settings.sfxVolume)">试听战斗音效</button><label class="check"><input v-model="ui.settings.reducedMotion" type="checkbox" @change="saveSettings"> 减少动态效果</label><button class="primary" @click="closeModal">完成</button></template>
    <template v-else-if="ui.modal==='tutorial'"><div class="eyebrow">指挥官手册 / QUICK START</div><h2>一格一格，筑起生机。</h2><ol class="instructions"><li><b>选择与投放</b><p>点击下方建筑，或按 1—9 / 0 / -；点击战场目标列。普通建筑从顶部落下；桥梁点击指定高度直接铺设，可水平延伸并承载上层，失去全部支撑会坠落。虚线框显示落点，投放冷却 1.2 秒。</p></li><li><b>搭建与经济</b><p>地面城墙挡路，困难模式的箭矢和炮弹会被城墙阻挡，可抬高炮位越墙射击；狙击子弹能穿墙。矿场每 10 秒产金币；敌人从右侧持续进攻，及时布置防空。</p></li><li><b>升级与回收</b><p>右键取消投放后，点击建筑升级；Shift + 点击多选，侧栏显示总费用并统一选择分支。选中防御塔按 E 操控，指向敌人并按住左键开火，右键退出；仍受射程、冷却和遮挡限制。按住拆除 1 秒回收部分费用，上层将坠落；坠落不伤友军。</p></li><li><b>暂停与保存</b><p>Space 暂停；切换窗口自动暂停。每 15 秒自动保存，也可从菜单保存退出。再次继续需手动恢复。</p></li></ol><button class="primary" @click="closeModal">明白了，开始指挥 →</button></template>
    <template v-else-if="ui.modal==='history'"><div class="eyebrow">防御档案 / RECENT RUNS</div><h2>每一道防线，都有记录。</h2><p>本地最高分 <strong class="gold">{{best}}</strong></p><div class="history-table"><table><thead><tr><th>结束时间</th><th>生存</th><th>击杀 / Boss</th><th>威胁</th><th>得分</th></tr></thead><tbody><tr v-for="r in runs" :key="r.runId"><td>{{new Date(r.endedAt).toLocaleString()}}</td><td>{{clock(r.survivalSeconds)}}</td><td>{{r.kills}} / {{r.bossKills}}</td><td>{{r.maxThreat}}</td><td>{{r.score}}</td></tr></tbody></table><p v-if="!runs.length">暂无战绩。你的第一道防线，正等待建立。</p></div><button class="primary" @click="closeModal">返回</button></template>
   </section>
  </div>
 </main>
</template>
